### PR TITLE
[Comb] Add ConcatOp custom assembly format to enable nullaries

### LINKED ISSUE #9183: Nullary comb.concat doesn't roundtrip
`"comb.concat"() : () -> (i0)` is valid generic syntax, but doesn't roundtrip through circt-opt - passing it through gives:

```
module {
  %0 = comb.concat  : 
}
```

on which circt-opt errors:

```
<stdin>:2:22: error: expected non-function type
  %0 = comb.concat  : 
                     ^
```

Easiest fix might be to add a concat verifier that rejects the nullary case?

### PR DESCRIPTION
**Pull request by TaoBi22**
Closes #9183 - nullary concats now roundtrip, but other syntax should be unchanged. This keeps the format of the op consistent with other ops in comb (which was an issue with the pure regex approach @uenoku proposed in #9183), but obviously comes at the cost of the extra code, so can swap out for the regex approach if preferred!

### CODE REVIEW

File: lib/Dialect/Comb/CombOps.cpp [hunk 1]
```diff
@@ -503,6 +503,43 @@ LogicalResult ConcatOp::inferReturnTypes(
...
+  llvm::SMLoc allOperandLoc = parser.getCurrentLocation();
+
+  // Parse the operand list, attributes and colon
+  if (parser.parseOperandList(operands) ||
+      parser.parseOptionalAttrDict(result.attributes) || parser.parseColon())
+    return failure();
+
+  // If we have operands, we need to parse the types too
+  if (!operands.empty() && parser.parseTypeList(types))
+    return failure();
```
Comment (cowardsa) [inline lib/Dialect/Comb/CombOps.cpp]: Q: do we need to check that operands.empty() => types.empty()?

File: lib/Dialect/Comb/CombOps.cpp [hunk 2]
```diff
@@ -503,6 +503,43 @@ LogicalResult ConcatOp::inferReturnTypes(
   return success();
 }
 
+ParseResult ConcatOp::parse(OpAsmParser &parser, OperationState &result) {
+  SmallVector<OpAsmParser::UnresolvedOperand, 4> operands;
+  SmallVector<Type, 4> types;
```
Comment (cowardsa) [inline lib/Dialect/Comb/CombOps.cpp:511]: Nit: worth adding a comment to describe the general format? (and state which fields are optional)

File: lib/Dialect/Comb/CombOps.cpp (hunk 1 above)
Comment (TaoBi22) [reply lib/Dialect/Comb/CombOps.cpp]: Oh good point, this gets funky and causes it to try to parse the typelist as an op - I'll add an explicit error, thanks!

File: lib/Dialect/Comb/CombOps.cpp (hunk 2 above)
Comment (TaoBi22) [reply lib/Dialect/Comb/CombOps.cpp:511]: Good point, thanks!

**Comment by TaoBi22** [comment]
In order to make MLIR happy about optionally parsing a typelist, the colon delimiter had to be optional too, so the format for a nullary concat after this PR is now just `comb.concat` rather than `comb.concat :` (which feels more sensible anyway)

File: test/Dialect/Comb/basic.mlir [hunk 3]
```diff
@@ -10,3 +10,9 @@ hw.module @Issue5772(in %arg0: !hw.typealias<@__hw_typedecls::@foo,i1>) {
   // CHECK: comb.concat %arg0 : !hw.typealias<@__hw_typedecls::@foo, i1>
   %0 = comb.concat %arg0 : !hw.typealias<@__hw_typedecls::@foo,i1>
 }
+
+// CHECK-LABEL: @NullaryConcat
+hw.module @NullaryConcat() {
+  // CHECK: comb.concat
+  comb.concat
```
Comment (uenoku) [inline test/Dialect/Comb/basic.mlir]: I'm curios the following example works
```suggestion
  %0 = comb.concat
  %1 = comb.concat %0, %0: i0, i0
```
I believe this causes a parser error? Not ideal but trailing column might be actually necessary 😞

Comment (TaoBi22) [reply test/Dialect/Comb/basic.mlir]: Oh yeah that's a great catch, thank you! Annoyingly there's no infrastructure for an optional typelist without a delimiter but I'll handspin something from what's there and update the test

**Review by uenoku — APPROVED** [review]
Looks good to me.
