### PR TITLE
[FIRRTL][LegacyWiring] Fix insertion point for fieldID.

### LINKED ISSUE #4663: WiringProblem: sub* insertion point, "does not dominate this use"
Test case, "subindex-oops.mlir":
```mlir
firrtl.circuit "Sub" attributes {
  rawAnnotations = [
    {
      class = "firrtl.passes.wiring.SourceAnnotation",
      target = "Sub.Sub.a[0]",
      pin = "test"
    },
    {
      class = "firrtl.passes.wiring.SinkAnnotation",
      target = "Sub.Sub.b[0]",
      pin = "test"
    }]} {
  firrtl.module @Sub() {
    %a = firrtl.wire interesting_name : !firrtl.vector<uint<1>,1>
    %b = firrtl.wire interesting_name : !firrtl.vector<uint<1>,1>
  }
}
```

Error:

```
subindex-oops.mlir:14:10: error: operand #0 does not dominate this use
    %a = firrtl.wire interesting_name : !firrtl.vector<uint<1>,1>
         ^
subindex-oops.mlir:14:10: note: see current operation: %0 = "firrtl.subindex"(%1) {index = 0 : i32} : (!firrtl.vector<uint<1>, 1>) -> !firrtl.uint<1>
subindex-oops.mlir:14:10: note: operand defined here (op in the same block)
```

### PR DESCRIPTION
**Pull request by dtzSiFive**
Fixes #4663.

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/LegacyWiring.cpp [hunk 1]
```diff
@@ -65,14 +65,10 @@ LogicalResult circt::firrtl::applyWiring(const AnnoPathValue &target,
...
-      auto module = cast<FModuleOp>(opResult.getModule());
-      if (clazz == wiringSourceAnnoClass) {
-        builder.setInsertionPointToStart(module.getBodyBlock());
-      } else if (clazz == wiringSinkAnnoClass) {
-        builder.setInsertionPointToEnd(module.getBodyBlock());
-      }
-      targetValue = getValueByFieldID(builder, opResult.getOp()->getResult(0),
-                                      target.fieldIdx);
+      auto *targetBase = opResult.getOp();
+      builder.setInsertionPointAfter(targetBase);
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/Transforms/LegacyWiring.cpp:69]: Possibly:

```c++
builder.setInsertionPointAfterValue(opResult);
```

**Review by seldridge — APPROVED** [review]
LGTM

File: lib/Dialect/FIRRTL/Transforms/LegacyWiring.cpp (hunk 1 above)
Comment (dtzSiFive) [reply lib/Dialect/FIRRTL/Transforms/LegacyWiring.cpp:69]: Whoa!! That exists?!?

```
    /// Sets the insertion point to the node after the specified value. If value                                                                                                                                                                                            
    /// has a defining operation, sets the insertion point to the node after such                                                                                                                                                                                           
    /// defining operation. This will cause subsequent insertions to go right                                                                                                                                                                                               
    /// after it. Otherwise, value is a BlockArgument. Sets the insertion point to                                                                                                                                                                                          
    /// the start of its block.
    void setInsertionPointAfterValue(Value val) {
```

Nice!!

Comment (dtzSiFive) [reply lib/Dialect/FIRRTL/Transforms/LegacyWiring.cpp:69]: Unfortunately, `opResult` is not an `OpResult` despite the name, which would work!  (it's an `OpAnnoTarget`).

Still, thanks for the suggestion, TIL!
