### PR TITLE
[SCFToCalyx] Add special case for pipeline stages with side effects only.

### LINKED ISSUE #3112: [StaticLogicToCalyx] Unused group in execution schedule.
```mlir
// test.mlir
func.func @func(%A: memref<4xi32>, %B: memref<4xi32>, %R: memref<4xi32>) {
  affine.for %i = 0 to 4 {
    %5 = affine.load %A[%i] : memref<4xi32>
    %6 = affine.load %B[%i] : memref<4xi32>
    %7 = arith.muli %5, %6 : i32
    affine.store %7, %R[%i] : memref<4xi32>
  }
  return
}
```

```
 ./build/bin/circt-opt -convert-affine-to-staticlogic test.mlir | ./build/bin/circt-opt --lower-scf-to-calyx
```

```mlir
module {
  func.func @func(%arg0: memref<4xi32>, %arg1: memref<4xi32>, %arg2: memref<4xi32>) {
    %c0 = arith.constant 0 : index
    %c4 = arith.constant 4 : index
    %c1 = arith.constant 1 : index
    staticlogic.pipeline.while II =  1 trip_count =  4 iter_args(%arg3 = %c0) : (index) -> () {
      %0 = arith.cmpi ult, %arg3, %c4 : index
      staticlogic.pipeline.register %0 : i1
    } do {
      %0:3 = staticlogic.pipeline.stage start = 0 {
        %2 = memref.load %arg0[%arg3] : memref<4xi32>
        %3 = memref.load %arg1[%arg3] : memref<4xi32>
        %4 = arith.addi %arg3, %c1 : index
        staticlogic.pipeline.register %2, %3, %4 : i32, i32, index
      } : i32, i32, index
      %1 = staticlogic.pipeline.stage start = 1 {
        %2 = arith.muli %0#0, %0#1 : i32
        staticlogic.pipeline.register %2 : i32
      } : i32
      staticlogic.pipeline.stage start = 4 {
        memref.store %1, %arg2[%arg3] : memref<4xi32>
        staticlogic.pipeline.register 
      }
      staticlogic.pipeline.terminator iter_args(%0#2), results() : (index) -> ()
    }
    return
  }
}
```

```mlir
"builtin.module"() ({
  "calyx.program"() ({
    "calyx.component"() ({
    ^bb0(%arg0: i32, %arg1: i1, %arg2: i32, %arg3: i1, %arg4: i32, %arg5: i1, %arg6: i1, %arg7: i1, %arg8: i1, %arg9: i32, %arg10: i2, %arg11: i1, %arg12: i32, %arg13: i2, %arg14: i1, %arg15: i32, %arg16: i2, %arg17: i1, %arg18: i1):
      %0 = "hw.constant"() {value = 1 : i32} : () -> i32
      %1 = "hw.constant"() {value = 4 : i32} : () -> i32
      %2 = "hw.constant"() {value = 0 : i32} : () -> i32
      %3 = "hw.constant"() {value = true} : () -> i1
      %4:2 = "calyx.std_slice"() {sym_name = "std_slice_2"} : () -> (i32, i2)
      %5:2 = "calyx.std_slice"() {sym_name = "std_slice_1"} : () -> (i32, i2)
      %6:2 = "calyx.std_slice"() {sym_name = "std_slice_0"} : () -> (i32, i2)
      %7:7 = "calyx.std_mult_pipe"() {sym_name = "std_mult_pipe_0"} : () -> (i1, i1, i1, i32, i32, i32, i1)
      %8:3 = "calyx.std_add"() {sym_name = "std_add_0"} : () -> (i32, i32, i32)
      %9:3 = "calyx.std_lt"() {sym_name = "std_lt_0"} : () -> (i32, i32, i1)
      %10:6 = "calyx.register"() {sym_name = "stage_1_register_0_reg"} : () -> (i32, i1, i1, i1, i32, i1)
      %11:6 = "calyx.register"() {sym_name = "stage_0_register_1_reg"} : () -> (i32, i1, i1, i1, i32, i1)
      %12:6 = "calyx.register"() {sym_name = "stage_0_register_0_reg"} : () -> (i32, i1, i1, i1, i32, i1)
      %13:6 = "calyx.register"() {sym_name = "while_0_arg0_reg"} : () -> (i32, i1, i1, i1, i32, i1)
      "calyx.wires"() ({
        "calyx.group"() ({
          "calyx.assign"(%13#0, %2) : (i32, i32) -> ()
          "calyx.assign"(%13#1, %3) : (i1, i1) -> ()
          "calyx.group_done"(%13#5) : (i1) -> ()
        }) {sym_name = "assign_while_0_init_0"} : () -> ()
        "calyx.comb_group"() ({
          "calyx.assign"(%9#0, %13#4) : (i32, i32) -> ()
          "calyx.assign"(%9#1, %1) : (i32, i32) -> ()
        }) {sym_name = "bb0_0"} : () -> ()
        "calyx.group"() ({
          "calyx.assign"(%4#0, %13#4) : (i32, i32) -> ()
          "calyx.assign"(%arg10, %4#1) : (i2, i2) -> ()
          "calyx.assign"(%12#0, %arg0) : (i32, i32) -> ()
          "calyx.assign"(%12#1, %3) : (i1, i1) -> ()
          "calyx.group_done"(%12#5) : (i1) -> ()
        }) {sym_name = "bb0_1"} : () -> ()
        "calyx.group"() ({
          "calyx.assign"(%5#0, %13#4) : (i32, i32) -> ()
          "calyx.assign"(%arg13, %5#1) : (i2, i2) -> ()
          "calyx.assign"(%11#0, %arg2) : (i32, i32) -> ()
          "calyx.assign"(%11#1, %3) : (i1, i1) -> ()
          "calyx.group_done"(%11#5) : (i1) -> ()
        }) {sym_name = "bb0_2"} : () -> ()
        "calyx.group"() ({
          "calyx.assign"(%8#0, %13#4) : (i32, i32) -> ()
          "calyx.assign"(%8#1, %0) : (i32, i32) -> ()
          "calyx.assign"(%13#0, %8#2) : (i32, i32) -> ()
          "calyx.assign"(%13#1, %3) : (i1, i1) -> ()
          "calyx.group_done"(%13#5) : (i1) -> ()
        }) {sym_name = "bb0_3"} : () -> ()
        "calyx.group"() ({
          "calyx.assign"(%7#3, %12#4) : (i32, i32) -> ()
          "calyx.assign"(%7#4, %11#4) : (i32, i32) -> ()
          "calyx.assign"(%10#0, %7#5) : (i32, i32) -> ()
          "calyx.assign"(%10#1, %7#6) : (i1, i1) -> ()
          "calyx.assign"(%7#2, %3) : (i1, i1) -> ()
          "calyx.group_done"(%10#5) : (i1) -> ()
        }) {sym_name = "bb0_4"} : () -> ()
        "calyx.group"() ({
          "calyx.assign"(%6#0, %13#4) : (i32, i32) -> ()
          "calyx.assign"(%arg16, %6#1) : (i2, i2) -> ()
          "calyx.assign"(%arg15, %10#4) : (i32, i32) -> ()
          "calyx.assign"(%arg17, %3) : (i1, i1) -> ()
          "calyx.group_done"(%arg5) : (i1) -> ()
        }) {sym_name = "bb0_5"} : () -> ()
      }) : () -> ()
      "calyx.control"() ({
        "calyx.seq"() ({
          "calyx.par"() ({./bin/circt-opt --lower-scf-to-calyx
            "calyx.enable"() {groupName = @assign_while_0_init_0} : () -> ()
          }) : () -> ()
          "calyx.par"() ({
            "calyx.enable"() {groupName = @bb0_1} : () -> ()
            "calyx.enable"() {groupName = @bb0_2} : () -> ()
            "calyx.enable"() {groupName = @bb0_3} : () -> ()
          }) : () -> ()
          "calyx.par"() ({
            "calyx.enable"() {groupName = @bb0_1} : () -> ()
            "calyx.enable"() {groupName = @bb0_2} : () -> ()
            "calyx.enable"() {groupName = @bb0_3} : () -> ()
            "calyx.enable"() {groupName = @bb0_4} : () -> ()
          }) : () -> ()
          "calyx.while"(%9#2) ({
            "calyx.par"() ({
              "calyx.enable"() {groupName = @bb0_1} : () -> ()
              "calyx.enable"() {groupName = @bb0_2} : () -> ()
              "calyx.enable"() {groupName = @bb0_3} : () -> ()
              "calyx.enable"() {groupName = @bb0_4} : () -> ()
            }) : () -> ()
          }) {bound = 2 : i64, groupName = @bb0_0} : (i1) -> ()
          "calyx.par"() ({
            "calyx.enable"() {groupName = @bb0_4} : () -> ()
          }) : () -> ()
        }) : () -> ()
      }) : () -> ()
    }) {function_type = (i32, i1, i32, i1, i32, i1, i1, i1, i1, i32, i2, i1, i32, i2, i1, i32, i2, i1, i1) -> (), portAttributes = [{mem = {id = 0 : i32, tag = "read_data"}}, {mem = {id = 0 : i32, tag = "done"}}, {mem = {id = 1 : i32, tag = "read_data"}}, {mem = {id = 1 : i32, tag = "done"}}, {mem = {id = 2 : i32, tag = "read_data"}}, {mem = {id = 2 : i32, tag = "done"}}, {clk}, {reset}, {go}, {mem = {id = 0 : i32, tag = "write_data"}}, {mem = {addr_idx = 0 : i32, id = 0 : i32, tag = "addr"}}, {mem = {id = 0 : i32, tag = "write_en"}}, {mem = {id = 1 : i32, tag = "write_data"}}, {mem = {addr_idx = 0 : i32, id = 1 : i32, tag = "addr"}}, {mem = {id = 1 : i32, tag = "write_en"}}, {mem = {id = 2 : i32, tag = "write_data"}}, {mem = {addr_idx = 0 : i32, id = 2 : i32, tag = "addr"}}, {mem = {id = 2 : i32, tag = "write_en"}}, {done}], portDirections = -512 : i19, portNames = ["ext_mem0_read_data", "ext_mem0_done", "ext_mem1_read_data", "ext_mem1_done", "ext_mem2_read_data", "ext_mem2_done", "clk", "reset", "go", "ext_mem0_write_data", "ext_mem0_addr0", "ext_mem0_write_en", "ext_mem1_write_data", "ext_mem1_addr0", "ext_mem1_write_en", "ext_mem2_write_data", "ext_mem2_addr0", "ext_mem2_write_en", "done"], sym_name = "func", toplevel} : () -> ()
  }) {entryPointName = "func"} : () -> ()
}) : () -> ()
```

```
<stdin>:21:9: error: 'calyx.group' op with name: "bb0_5" is unused in the control execution schedule
        memref.store %1, %arg2[%arg3] : memref<4xi32>
```

### PR DESCRIPTION
**Pull request by cgyurgyik**
This is a hot fix for memref::StoreOps to be used unconditionally in a pipeline stage. I'm not really convinced this is the best approach, however I'm also hesitant to commit to any large-scale changes before we separate {SCF, StaticLogic}ToCalyx conversions.

Closes #3112, #3111.

### CODE REVIEW

**Review by mortbopet — APPROVED** [review]
Code LGTM as a hotfix, but really not a big fan of how one needs to explicitly mutate the prologue/epilogue groups. As noted in #3113, that approach would allow for first building the set of pipeline stages, and after that's done, prologue/epilogue is handled simply by using the predicate register.

File: lib/Conversion/SCFToCalyx/SCFToCalyx.cpp [hunk 1]
```diff
@@ -1768,15 +1800,14 @@ class BuildPipelineRegs : public FuncOpPartialLoweringPattern {
...
-                  dyn_cast<staticlogic::PipelineTerminatorOp>(use.getOwner())) {
-            if (use.getOperandNumber() < term.iter_args().size()) {
-              WhileOpInterface whileOp(stage->getParentOp());
-              auto reg = getComponentState().getWhileIterReg(
-                  whileOp, use.getOperandNumber());
-              getComponentState().addPipelineReg(stage, reg, i);
-              isIterArg = true;
-            }
+                  dyn_cast<staticlogic::PipelineTerminatorOp>(use.getOwner());
+              term && operandNo < term.iter_args().size()) {
```
Comment (mikeurbach) [inline lib/Conversion/SCFToCalyx/SCFToCalyx.cpp:1806]: IMO this is doing too much in the condition of an `if`. I don't know if this is LLVM coding standard, but if there is an assignment inside an if condition, I think it is best for this to be the only statement within an if condition (this is why there were nested ifs originally.

File: lib/Conversion/SCFToCalyx/SCFToCalyx.cpp [hunk 2]
```diff
@@ -1815,9 +1846,10 @@ class BuildPipelineGroups : public FuncOpPartialLoweringPattern {
                            PatternRewriter &rewriter) const override {
     for (auto pipeline : funcOp.getOps<staticlogic::PipelineWhileOp>())
       for (auto stage :
-           pipeline.getStagesBlock().getOps<staticlogic::PipelineStageOp>())
+           pipeline.getStagesBlock().getOps<staticlogic::PipelineStageOp>()) {
```
Comment (mikeurbach) [inline lib/Conversion/SCFToCalyx/SCFToCalyx.cpp:1849]: Please don't include style-only changes, these can be committed separately.

File: lib/Conversion/SCFToCalyx/SCFToCalyx.cpp [hunk 3]
```diff
@@ -1827,28 +1859,64 @@ class BuildPipelineGroups : public FuncOpPartialLoweringPattern {
...
+      // Covers the case where there are no values that need to be passed
+      // through to the next stage, e.g., some intermediary store.
+      auto it = llvm::find_if(stage.getBodyBlock(), [&](auto &op) {
+        Optional<calyx::GroupOp> group =
+            getComponentState().getNonPipelinedGroupFrom<calyx::GroupOp>(&op);
+
+        if (!group.hasValue())
+          return false;
+
+        updatePrologueAndEpilogue(*group);
```
Comment (mikeurbach) [inline lib/Conversion/SCFToCalyx/SCFToCalyx.cpp:1902]: This is getting a little wacky... this `updatePrologueAndEpilogue` has side effects, and is used inside the callback to `llvm::find_if`. I think that is an abuse of `find_if`. Please don't use `find_if` in this way, IMO this is being too clever. If you just need to loop through the body, do something like:

```
bool found = false;
for (...) ...
if (found)
   ...
```

File: lib/Conversion/SCFToCalyx/SCFToCalyx.cpp [hunk 4]
```diff
@@ -1057,6 +1086,9 @@ LogicalResult BuildOpGroups::buildOp(PatternRewriter &rewriter,
       storeOp.getLoc(), memoryInterface.writeEn(),
       createConstant(storeOp.getLoc(), rewriter, *getComponent(), 1, 1));
   rewriter.create<calyx::GroupDoneOp>(storeOp.getLoc(), memoryInterface.done());
+
+  getComponentState().registerNonPipelineOperations(storeOp, group);
```
Comment (mikeurbach) [inline lib/Conversion/SCFToCalyx/SCFToCalyx.cpp:1090]: *sigh* I was hoping to avoid more pipeline specific state until some of this is reworked. However, given the current phase ordering of how this pass does partial lowering, I think this is a reasonable fix for the short term. I haven't really thought about if there is a better way to solve this.

File: lib/Conversion/SCFToCalyx/SCFToCalyx.cpp (hunk 1 above)
Comment (mikeurbach) [reply lib/Conversion/SCFToCalyx/SCFToCalyx.cpp:1806]: Is there any meaningful change here or is this just style? Please commit style changes separately from meaningful changes.

File: lib/Conversion/SCFToCalyx/SCFToCalyx.cpp [hunk 5]
```diff
@@ -1827,28 +1859,64 @@ class BuildPipelineGroups : public FuncOpPartialLoweringPattern {
...
+      // through to the next stage, e.g., some intermediary store.
+      auto it = llvm::find_if(stage.getBodyBlock(), [&](auto &op) {
+        Optional<calyx::GroupOp> group =
+            getComponentState().getNonPipelinedGroupFrom<calyx::GroupOp>(&op);
+
+        if (!group.hasValue())
+          return false;
+
+        updatePrologueAndEpilogue(*group);
+        return true;
```
Comment (mikeurbach) [inline lib/Conversion/SCFToCalyx/SCFToCalyx.cpp:1903]: Does this assume there is only one store per group? I don't remember if this pass is going to guarantee that or not... Can you please add a test case or update your test case to include two stores in the same stage?

**Review by mikeurbach — CHANGES_REQUESTED** [review]
Thanks for jumping on this. In general, I think the idea of tracking side-effect only operations that don't need pipeline regs, and having special case handling that exits early for these in buildStageGroups is one reasonable way to fix this in the short term. I think we do want to a) refactor this stuff, and b) implement prologue and epilogue building in a nicer way, but for a short term fix this might make sense. I haven't given much thought to whether there is a more elegant way to fix this given the current state.

However, I have some general concerns with this patch: please remove (feel free to commit separately) all the style changes. Also, please don't use `llvm::find_if` for side-effects.

File: lib/Conversion/SCFToCalyx/SCFToCalyx.cpp (hunk 3 above)
Comment (cgyurgyik) [reply lib/Conversion/SCFToCalyx/SCFToCalyx.cpp:1902]: I see how transforming a "querying-like algorithm" into a state-modifying one is probably frowned upon, but I'm hard-pressed to believe that having some extra mutable state with a for-loop is a better choice.

Another suggestion would be to write some wrapper of `find_if`, e.g., `find_and_apply_if`. WDYT?

File: lib/Conversion/SCFToCalyx/SCFToCalyx.cpp (hunk 1 above)
Comment (cgyurgyik) [reply lib/Conversion/SCFToCalyx/SCFToCalyx.cpp:1806]: > but if there is an assignment inside an if condition, I think it is best for this to be the only statement within an if condition (this is why there were nested ifs originally.

I think C++17's if statement with initializer makes this read quite nicely. We really only care if `A && B` are true, and thus this feels more succinct. It seems odd to write this as nested `if`s. However, both are perfectly valid choices, and probably boil down to what we're accustomed to.

In any case, the style changes were probably me adding some debugging code. I'll fix these.

File: lib/Conversion/SCFToCalyx/SCFToCalyx.cpp (hunk 4 above)
Comment (cgyurgyik) [reply lib/Conversion/SCFToCalyx/SCFToCalyx.cpp:1090]: Yes I think that is the issue as well. There are a lot of inter-dependencies between the two lowering processes, which was nice initially but now is showing its limitations. I think finding a more general solution will become obvious when these are separated.

Comment (mikeurbach) [reply lib/Conversion/SCFToCalyx/SCFToCalyx.cpp:1090]: Yeah, I don't think I will honestly have the cycles to come up with a better approach in the short term, or if there even is one given the current phase ordering. This makes sense to move forward with.

File: lib/Conversion/SCFToCalyx/SCFToCalyx.cpp (hunk 3 above)
Comment (mikeurbach) [reply lib/Conversion/SCFToCalyx/SCFToCalyx.cpp:1902]: Well, this is _local_ mutable state, which in my mind makes this more simple to grok when we're debugging it in 6 months. This pattern isn't unheard of: https://github.com/llvm/circt/search?q=%22bool+found%22&type=code.

I guess I am coming from a mentality of: we are writing C++, it's an icky language, and it's better to write dead simple C code (and more of it) than fancy code (and less of it). The llvm support stuff can help make it more readable in some cases, but this crossed a line I had for readability versus keeping things simple for my mental C interpreter. That said, if you want to use the callback style here, and can come up with a way to make that both terse and simple to understand in the future, I'm all for it.

File: lib/Conversion/SCFToCalyx/SCFToCalyx.cpp (hunk 1 above)
Comment (mikeurbach) [reply lib/Conversion/SCFToCalyx/SCFToCalyx.cpp:1806]: I thought there was a coding standard in LLVM or the Google style guide about not doing anything more than a simple assignment, but I'm not finding it. This might be carrying over a Ruby convention I used... Anyway, I guess this is my somewhat curmudgeonly stance on writing dead simple C++ coming out again.

File: lib/Conversion/SCFToCalyx/SCFToCalyx.cpp (hunk 3 above)
Comment (cgyurgyik) [reply lib/Conversion/SCFToCalyx/SCFToCalyx.cpp:1900]: I'm not sure what you mean by icky. I think the best path forward is always writing safer code. One could say that a the "mental interpreter" is a function of what you're accustomed to seeing. This is a tale as old as time; std::variant versus union, malloc versus unique_ptr, etc. If we don't allow modern C++ features to appear in code, then yes, they will always be difficult to parse.

File: lib/Conversion/SCFToCalyx/SCFToCalyx.cpp (hunk 5 above)
Comment (cgyurgyik) [reply lib/Conversion/SCFToCalyx/SCFToCalyx.cpp]: Good catch! Fixed, updated the test case.

**Review by cgyurgyik — COMMENTED** [review]
This should be good for a second review @mikeurbach .

**Review by mikeurbach — APPROVED** [review]
Thanks! This is looking good to me.

Can't wait to hatchet all this out of SCFToCalyx and then rewrite the prologue/epilogue business as Morten has suggested.
