### PR TITLE
[FIRRTL] Honor NLAs in GCT data tap paths

### LINKED ISSUE #2691: [FIRRTL][GrandCentralTaps] GCTaps doesn't understand non-local annotations produced by dedup
In the following example, we have a similar module `Foo` and `Bar`.  `Foo` has a data tap on it.  `Bar` is later deduplicated with `Foo` and removed.  Some time after this, Tap selects the wrong instance, `bar of Bar` for the DataTap.
```verilog
circuit Top : %[[{
  "class": "sifive.enterprise.grandcentral.DataTapsAnnotation",
  "blackBox": "~Top|DataTap",
  "keys": [
    {
      "class": "sifive.enterprise.grandcentral.ReferenceDataTapKey",
      "source": "~Top|Foo>f",
      "portName": "~Top|DataTap>b"
    }
]}]]
  extmodule DataTap :
    output b : UInt<1>
    defname = DataTap
  module Foo :
    wire f : UInt<1>
    f is invalid
  module Bar :
    wire b : UInt<1>
    b is invalid
  module Top:
    inst foo of Foo
    inst bar of Bar
    inst dataTap of DataTap
```
`./bin/firtool -firrtl-grand-central --dedup ./gc.fir`
```verilog
module DataTap_impl_0(  // ./gc.fir:11:13
  output b);

  assign b = Top.bar.f; // ./gc.fir:11:13
endmodule

module Foo();   // ./gc.fir:14:10, :17:10
  wire f;       // ./gc.fir:15:5, :18:5

  assign f = 1'h0;      // ./gc.fir:16:7, :19:7
endmodule

module Top();   // ./gc.fir:20:10
  wire dataTap_b;       // ./gc.fir:23:5

  Foo foo ();   // ./gc.fir:21:5
  Foo bar ();   // ./gc.fir:22:5
  DataTap_impl_0 dataTap (      // ./gc.fir:23:5
    .b (dataTap_b)
  );
endmodule
```

Some IR dumps:
```mlir
firrtl.circuit "Top"  {
  firrtl.extmodule @DataTap(out b: !firrtl.uint<1> sym @b [{class = "sifive.enterprise.grandcentral.ReferenceDataTapKey", id = 0 : i64, portID = 1 : i64, type = "portName"}]) attributes {annotations = [{class = "sifive.enterprise.grandcentral.DataTapsAnnotation"}, {class = "firrtl.transforms.DontTouchAnnotation"}], defname = "DataTap"}
  firrtl.module @Foo() {
    %f = firrtl.wire sym @f  {annotations = [{class = "sifive.enterprise.grandcentral.ReferenceDataTapKey", id = 0 : i64, portID = 1 : i64, type = "source"}]} : !firrtl.uint<1>
    %invalid_ui1 = firrtl.invalidvalue : !firrtl.uint<1>
    firrtl.connect %f, %invalid_ui1 : !firrtl.uint<1>, !firrtl.uint<1>
  }
  firrtl.module @Bar() {
    %b = firrtl.wire  : !firrtl.uint<1>
    %invalid_ui1 = firrtl.invalidvalue : !firrtl.uint<1>
    firrtl.connect %b, %invalid_ui1 : !firrtl.uint<1>, !firrtl.uint<1>
  }
  firrtl.module @Top() {
    firrtl.instance foo  @Foo()
    firrtl.instance bar  @Bar()
    %dataTap_b = firrtl.instance dataTap  @DataTap(out b: !firrtl.uint<1>)
  }
}

// -----// IR Dump After Dedup //----- //
firrtl.circuit "Top"  {
  firrtl.nla @nla [#hw.innerNameRef<@Top::@foo>, #hw.innerNameRef<@Foo::@f>]
  firrtl.extmodule @DataTap(out b: !firrtl.uint<1> sym @b [{class = "sifive.enterprise.grandcentral.ReferenceDataTapKey", id = 0 : i64, portID = 1 : i64, type = "portName"}]) attributes {annotations = [{class = "sifive.enterprise.grandcentral.DataTapsAnnotation"}, {class = "firrtl.transforms.DontTouchAnnotation"}], defname = "DataTap"}
  firrtl.module @Foo() {
    %f = firrtl.wire sym @f  {annotations = [{circt.nonlocal = @nla, class = "sifive.enterprise.grandcentral.ReferenceDataTapKey", id = 0 : i64, portID = 1 : i64, type = "source"}]} : !firrtl.uint<1>
    %invalid_ui1 = firrtl.invalidvalue : !firrtl.uint<1>
    firrtl.connect %f, %invalid_ui1 : !firrtl.uint<1>, !firrtl.uint<1>
  }
  firrtl.module @Top() {
    firrtl.instance foo sym @foo  {annotations = [{circt.nonlocal = @nla, class = "circt.nonlocal"}]} @Foo()
    firrtl.instance bar  @Foo()
    %dataTap_b = firrtl.instance dataTap  @DataTap(out b: !firrtl.uint<1>)
  }
}

// -----// IR Dump After GrandCentralTaps //----- //
firrtl.circuit "Top"  {
  firrtl.module @DataTap_impl_0(out %b: !firrtl.uint<1> sym @b) attributes {annotations = [{class = "firrtl.transforms.DontTouchAnnotation"}]} {
    %0 = firrtl.verbatim.expr "{{0}}.{{1}}.{{2}}" : () -> !firrtl.uint<1> {symbols = [@Top, #hw.innerNameRef<@Top::@gct_sym>, #hw.innerNameRef<@Foo::@f>]}
    firrtl.connect %b, %0 : !firrtl.uint<1>, !firrtl.uint<1>
  }
  firrtl.module @Foo() {
    %invalid_ui1 = firrtl.invalidvalue : !firrtl.uint<1>
    %f = firrtl.wire sym @f  : !firrtl.uint<1>
    firrtl.strictconnect %f, %invalid_ui1 : !firrtl.uint<1>
  }
  firrtl.module @Top() {
    firrtl.instance foo sym @foo  @Foo()
    firrtl.instance bar sym @gct_sym  @Foo()
    %dataTap_b = firrtl.instance dataTap  @DataTap_impl_0(out b: !firrtl.uint<1>)
  }
}
```

### PR DESCRIPTION
**Pull request by fabianschuiki**
The Grand Central data/mem taps pass used guess which concrete instance of a wire or port a data/mem tap referred to, because the taps were local annotations (i.e., they did not mention a concrete instance that they applied to). Since we now *do* have support for non-local annotations, and passes like deduplication make ample use of them, the GCT pass should consider the additional path information provided by NLAs when generating the data tap wiring. This commit makes GCT leverage the path information in NLAs.

A concrete example would be a design with two instances:
```
module Top:
  inst foo of Foo
  inst bar of Foo
```
If the instance port `foo.a` is targeted as a reference data tap, the GCT pass would up until now consider `Top.foo.a` and `Top.bar.a` as possible paths to that port, essentially ignoring the concrete instance path provided by the NLA `foo.a` and instead finding all possible prefixes for `Foo.a` (note the reference to Foo the module, not foo the instance.) The pass would then pick among all possible prefixes the shortest one (or in case of a tie, the last shortest one), which in this case could lead to the data tap targeting `Top.bar.a`, instead of the specified `Top.foo.a`.

The solution is to actually consider the concrete NLA instance path if one is given, and use that to perform the tapping. Arguably, *all* GCT data taps should be local annotations, which would also allow us to get rid of a lot of hacky logic in the GCT pass. That requires upstream changes in Chisel first, though.

Fixes #2691.

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp [hunk 1]
```diff
@@ -709,11 +736,32 @@ void GrandCentralTapsPass::processAnnotation(AnnotatedPort &portAnno,
...
+  NonLocalAnchor nla;
+  if (auto nlaSym = targetAnno.getMember<FlatSymbolRefAttr>("circt.nonlocal")) {
+    nla = dyn_cast<NonLocalAnchor>(circuitSymbols->lookup(nlaSym.getAttr()));
+    assert(nla);
+    // Find all paths to the root of the NLA.
+    StringAttr rootSym =
+        TypeSwitch<Attribute, StringAttr>(nla.namepath()[0])
+            .Case<InnerRefAttr>([](auto attr) { return attr.getModule(); })
+            .Case<FlatSymbolRefAttr>([](auto attr) { return attr.getAttr(); });
+    Operation *root = circuitSymbols->lookup(rootSym);
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp:754]:
```suggestion
    Operation *root = circuitSymbols->lookup(nla.root());
```

FYI: there's a bunch of added member functions for extracting information from NLAs that help here: https://github.com/llvm/circt/blob/5b70f5bd7c0d7cb1ad9a8f073b74b6d1b995381b/include/circt/Dialect/FIRRTL/FIRRTLStructure.td#L178

File: test/Dialect/FIRRTL/grand-central-taps.mlir [hunk 2]
```diff
@@ -390,3 +390,91 @@ firrtl.circuit "NLAGarbageCollection" {
...
+    out d: !firrtl.uint<1> sym @d [{
+      class = "sifive.enterprise.grandcentral.ReferenceDataTapKey",
+      id = 0 : i64,
+      portID = 3 : i64,
+      type = "portName"
+    }]
+  ) attributes {
+    annotations = [
+      {class = "sifive.enterprise.grandcentral.DataTapsAnnotation"},
+      {class = "firrtl.transforms.DontTouchAnnotation"}
```
Comment (seldridge) [inline test/Dialect/FIRRTL/grand-central-taps.mlir:438]: Nit: don't touch should be unnecessary given that this is just running the GCT taps pass.

**Review by seldridge — APPROVED** [review]
lgtm

File: lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp (hunk 1 above)
Comment (fabianschuiki) [reply lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp:754]: Cool stuff, thanks for pointing this out. Let me fix this up.

File: lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp [hunk 3]
```diff
@@ -709,11 +736,28 @@ void GrandCentralTapsPass::processAnnotation(AnnotatedPort &portAnno,
...
+  NonLocalAnchor nla;
+  if (auto nlaSym = targetAnno.getMember<FlatSymbolRefAttr>("circt.nonlocal")) {
+    nla = dyn_cast<NonLocalAnchor>(circuitSymbols->lookup(nlaSym.getAttr()));
+    assert(nla);
+    // Find all paths to the root of the NLA.
+    Operation *root = circuitSymbols->lookup(nla.root());
+    wiring.nla = nla;
+    wiring.prefices = instancePaths.getAbsolutePaths(root);
+  }
+
```
Comment (youngar) [inline lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp:754]: Nice!

**Review by youngar — APPROVED** [review]
