### PR TITLE
[FIRRTL][LowerTypes] Fix DontTouch application on ports

### LINKED ISSUE #3504: [FIRRTL][LowerTypes] DontTouch on a field going missing
```mlir
firrtl.circuit "Test" {
  firrtl.module @Test (in %front_port_ahb_0: !firrtl.bundle<hmastlock: uint<1>> [
    {circt.fieldID = 1 : i32, class = "firrtl.transforms.DontTouchAnnotation"},
    {circt.fieldID = 1 : i32, class = "Test"}
  ]) {
 }
}
```
`/bin/circt-opt --firrtl-lower-types ./test.mlir` produces: 
```mlir
module {
  firrtl.circuit "Test"  {
    firrtl.module @Test(in %front_port_ahb_0_hmastlock: !firrtl.uint<1> [{class = "Test"}]) {
    }
  }
}
```
The port should have a symbol on it to indicate `DontTouch`.  If you reverse the order of the annotations, the symbol appears:
```mlir
firrtl.circuit "Test" {
  firrtl.module @Test (in %front_port_ahb_0: !firrtl.bundle<hmastlock: uint<1>> [
    {circt.fieldID = 1 : i32, class = "Test"},
    {circt.fieldID = 1 : i32, class = "firrtl.transforms.DontTouchAnnotation"}
  ]) {
 }
}

```
```mlir
module {
  firrtl.circuit "Test"  {
    firrtl.module @Test(in %front_port_ahb_0_hmastlock: !firrtl.uint<1> sym @front_port_ahb_0_hmastlock [{class = "Test"}]) {
    }
  }
}
```

### PR DESCRIPTION
**Pull request by youngar**
During LowerTypes we take ports of bundle type, with fields annotated
with DontTouch, and exchange the annotation for a symbol on the port.
This was broken when the DontTouch was not the last annotation applied
to the port, as subsequent annotations would overwrite the `needsSym`
local variable.

Fixes #3504

### CODE REVIEW

**Review by seldridge — APPROVED** [review]
🤦  Awesome catch! LGTM

File: lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp [hunk 1]
```diff
@@ -1213,10 +1213,6 @@ bool TypeLoweringVisitor::visitDecl(InstanceOp op) {
   if (skip) {
     return false;
   }
-  if (!sym || sym.getValue().empty())
```
Comment (dtzSiFive) [inline lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp:1216]: (Is this code not needed?)

File: test/Dialect/FIRRTL/lower-types.mlir [hunk 2]
```diff
@@ -1215,3 +1215,16 @@ firrtl.circuit "SymbolCollision" {
     in %b: !firrtl.bundle<foo: uint<1>> [{circt.fieldID = 1 : i32, circt.nonlocal = @bar}]) {
   }
 }
+
+// Check that we don't lost the DontTouchAnnotation when it is not the lose
```
Comment (dtzSiFive) [inline test/Dialect/FIRRTL/lower-types.mlir:1219]:
```suggestion
// Check that we don't lose the DontTouchAnnotation when it is not the last
```

**Review by dtzSiFive — APPROVED** [review]
Awesome, great work tracking this down and fixing it!  Sure seems like a bug to me, and fix of course LGTM.

File: lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp (hunk 1 above)
Comment (youngar) [reply lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp]: This wasn't supposed to make it in the PR 😂 I was just curious what would break when I removed it, and then opened this issue to ask about it over here https://github.com/llvm/circt/issues/3505
