### PR TITLE
[ImportVerilog] Fix single unit preprocessor option

### LINKED ISSUE #6680: [ImportVerilog] Preprocessor ignores singleUnit option
Running multiple Verilog files through `circt-verilog` in preprocessor mode (`-E` option) ignores the `--single-unit` option. Single unit mode should carry macros of earlier files over into subsequent files. But the `preprocessVerilog` function in `ImportVerilog` creates a fresh new preprocessor for every file, regardless of whether `singleUnit` is set. Instead, if `singleUnit` is set, we should create one preprocessor that is used for all input files.

Shoutout to @dtzWill for finding this!

### PR DESCRIPTION
**Pull request by fabianschuiki**
Make `ImportVerilog` honor the `singleUnit` option by either adding all source files to a single preprocessor (single unit), or creating a fresh preprocessor for every single file (multiple units).

Fixes #6680.

### CODE REVIEW

File: lib/Conversion/ImportVerilog/ImportVerilog.cpp [hunk 1]
```diff
@@ -260,14 +257,44 @@ LogicalResult ImportContext::preprocessVerilog(llvm::raw_ostream &os) {
...
+  // source file is in its own compilation unit.
+  auto optionBag = driver.createOptionBag();
+  if (driver.options.singleUnit == true) {
+    slang::BumpAllocator alloc;
+    slang::Diagnostics diagnostics;
+    slang::parsing::Preprocessor preprocessor(driver.sourceManager, alloc,
+                                              diagnostics, optionBag);
+    // Sources have to be pushed in reverse, as they form a stack in the
+    // preprocessor. Last pushed source is processed first.
+    for (auto &buffer : slang::make_reverse_range(driver.buffers))
```
Comment (dtzSiFive) [inline lib/Conversion/ImportVerilog/ImportVerilog.cpp:282]: I'm curious about this via `llvm::reverse(...)` but LGTM.

**Review by dtzSiFive — APPROVED** [review]
LGTM, thanks!

File: lib/Conversion/ImportVerilog/ImportVerilog.cpp (hunk 1 above)
Comment (fabianschuiki) [reply lib/Conversion/ImportVerilog/ImportVerilog.cpp:282]: I tried that first, but ran into an ambiguous reference to `make_range` inside the reverse function (one provided by slang, one by llvm).
