### PR TITLE
[ExportVerilog] Don't emit "logic" for temporaries with struct types

### LINKED ISSUE #2335: [ExportVerilog] Invalid automatic variable emission of struct type
```mlir
; circt-opt %s -export-verilog
hw.module @AggregateTemporay(%clock: i1, %foo: i1) {
  %temp = sv.reg  : !hw.inout<!hw.struct<b: i1>>
  sv.always posedge %clock  {
    %0 = hw.bitcast %foo : (i1) -> !hw.struct<b: i1>
    sv.passign %temp, %0 : !hw.struct<b: i1>
    sv.passign %temp, %0 : !hw.struct<b: i1>
  }
}
```
will generate something like this:
```sv
module AggregateTemporay(       // foo.mlir:1:1
  input clock, foo);

  struct packed {logic b; } temp;       // foo.mlir:2:11

  always @(posedge clock) begin // foo.mlir:5:3
    automatic logic struct packed {logic b; } _T = foo;       // foo.mlir:6:10

    temp <= _T; // foo.mlir:7:5
    temp <= _T; // foo.mlir:8:5
  end // always @(posedge)
endmodule
```
`automatic logic struct packed {logic b; } _T = foo;` is syntactically incorrect. 
We have to emit `automatic struct packed {logic b; } _T = foo; `.

### PR DESCRIPTION
**Pull request by uenoku**
This commit fixes the issue related to the emission of automatic
variable. If the type contains a struct type, we shouldn't emit "logic"
because "automatic struct" is syntactically correct. 

Will close #2335 .

### CODE REVIEW

File: lib/Conversion/ExportVerilog/ExportVerilog.cpp [hunk 1]
```diff
@@ -290,7 +300,14 @@ static StringRef getVerilogDeclWord(Operation *op,
   // "automatic logic" values aren't allowed in disallowLocalVariables mode.
   assert((!isProcedural || !options.disallowLocalVariables) &&
          "automatic variables not allowed");
```
Comment (lattner) [inline lib/Conversion/ExportVerilog/ExportVerilog.cpp:302]: The patch looks good, but since you're making this an "if" please sink the assert after the if.  This will simplify it to just `assert(!options.disallowLocalVariables && ...`

**Review by lattner — APPROVED** [review]
Thx!

File: lib/Conversion/ExportVerilog/ExportVerilog.cpp (hunk 1 above)
Comment (uenoku) [reply lib/Conversion/ExportVerilog/ExportVerilog.cpp]: Thanks!

**Comment by uenoku** [comment]
Thank you for the review!
