### PR TITLE
[FIRRTL] Add a CheckCombCycles pass

### LINKED ISSUE #1138: [FIRRTL] combinational loop detection
The following FIRRTL program

```python
circuit top_mod :
  module top_mod :
    output a: UInt<11>
    output b: UInt<11>
    a <= b
    b <= a
```

Compiled with `firtool a_top_mod.fir --lower-to-hw --expand-whens --infer-widths --lowering-options=noAlwaysFF --verilog -o=a_top_mod_new.v` produces this Verilog:

```verilog
module top_mod(
  output [10:0] a, b);

  wire [10:0] _a_output;	// a_top_mod.fir:2:3
  wire [10:0] _b_output;	// a_top_mod.fir:2:3

  wire [10:0] _T = _b_output;	// a_top_mod.fir:5:7
  assign _a_output = _T;	// a_top_mod.fir:5:7
  wire [10:0] _T_0 = _a_output;	// a_top_mod.fir:6:7
  assign _b_output = _T_0;	// a_top_mod.fir:6:7
  assign a = _T_0;	// a_top_mod.fir:2:3
  assign b = _T;	// a_top_mod.fir:2:3
endmodule
```

Compiled with `firrtl-1.5-SNAPSHOT` produces this Error message:

```
Exception in thread "main" firrtl.transforms.CheckCombLoops$CombLoopException: : [module top_mod] Combinational loop detected:
```

### PR DESCRIPTION
**Pull request by hanchenye**
This pass runs a DFS traversing to detect the combinational loops in the IR. As the beginning, the current implementation assumes the aggregated types have been lowered to ground types before this pass.

I tested this with `dot.mlir` and `matmul.mlir` in `integration_test/Dialect/Handshake/`. Combinational loops can be detected on both test cases if `-handshake-insert-buffer` is not applied. Also tested on all cases in [perf](https://github.com/circt/perf), no combinational loop detected :)

Fixes #1138.

### CODE REVIEW

**Review by seldridge — COMMENTED** [review]
Can you add every test from here: https://github.com/chipsalliance/firrtl/blob/master/src/test/scala/firrtlTests/CheckCombLoopsSpec.scala

Going forward, I just want to make sure that we have the exact same test coverage that the SFC has.

**Review by fabianschuiki — COMMENTED** [review]
I haven't gone through the entire PR yet, but just a quick question: Do we expect this pass to run after LowerTypes? If it operates on entire `Value`s, instead of individual fields (which might be too fine-grained anyway, so this could be totally fine), then IR with structs/vectors may give false positives on comb loop detection which would go away if fields are individually resolved.

Edit: The `CheckCombLoopsSpec.scala` that @seldridge has linked doesn't seem to resolve individual fields, so I'm pretty sure this is okay as it is :+1:

**Comment by seldridge** [comment]
Also, note that there is an annotation, [`firrtl.transform.ExtModulePathAnnotation`](https://github.com/chipsalliance/firrtl/blob/master/src/main/scala/firrtl/transforms/CheckCombLoops.scala#L66), which will describe combinational paths in blackboxes. This can allow combinational loop checking to look inside blackboxes and include it in the analysis. You'll notice that the `CheckCombLoopsSpec.scala` includes tests of this. 

I am okay with punting on this for now (I'm trying to get clarification on how widely this is used), but we should have an issue tracking `ExtModulePathAnnotation` after this lands (if support is not added here).

**Comment by hanchenye** [comment]
@seldridge Thanks for pointing out! It seems we have two targets, `source` and `sink`, for this annotation. I'm thinking are we able to parse this annotation in the current parser and represent it in the IR?

**Comment by seldridge** [comment]
This will be parsed, but because it is not a `SingleTargetAnnotation`, it will need to be special cased during scattering to apply it to the `ExtModule`. The source and sink are supposed to be ports on the same extmodule and if they're not I would then error out.

**Comment by hanchenye** [comment]
I see. I'll open an issue and take a look at this. Once this annotation can be handled properly, we should be able to support it trivially in this loops detection pass.

File: lib/Dialect/FIRRTL/Analysis/DetectCombLoops.cpp [hunk 1]
```diff
@@ -0,0 +1,228 @@
+//===- ModuleInliner.cpp - FIRRTL module inlining ---------------*- C++ -*-===//
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Analysis/DetectCombLoops.cpp:1]: Plz update the first line of the header

File: lib/Dialect/FIRRTL/Analysis/CMakeLists.txt [hunk 2]
```diff
@@ -0,0 +1,12 @@
+add_circt_dialect_library(CIRCTFIRRTLAnalysis
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Analysis/CMakeLists.txt:1]: I'd just add this to the existing firrtl passes directory.  It isn't really an "analysis" per-say, it is a checker like the CheckWidths pass.

File: include/circt/Dialect/FIRRTL/Passes.td [hunk 3]
```diff
@@ -196,4 +196,12 @@ def GrandCentralTaps : Pass<"firrtl-grand-central-taps", "firrtl::CircuitOp"> {
   let dependentDialects = ["sv::SVDialect"];
 }
 
+def DetectCombLoops : Pass<"firrtl-detect-comb-loops", "firrtl::CircuitOp"> {
```
Comment (lattner) [inline include/circt/Dialect/FIRRTL/Passes.td:199]: This run on a module at a time, please change to do so.

File: lib/Dialect/FIRRTL/Analysis/DetectCombLoops.cpp [hunk 4]
```diff
@@ -0,0 +1,228 @@
...
+// Pass Infrastructure
+//===----------------------------------------------------------------------===//
+
+namespace {
+/// This pass should be applied after firrtl-lower-types.
+class DetectCombLoopsPass : public DetectCombLoopsBase<DetectCombLoopsPass> {
+  void runOnOperation() override {
+    for (auto module : getOperation().getOps<FModuleOp>()) {
+      if (!combPathsMap.count(module))
+        Detector(module, combPathsMap).detect();
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Analysis/DetectCombLoops.cpp:214]: Plz make sure to tell the passmgr that the IR wasn't changed.

File: include/circt/Dialect/FIRRTL/Passes.h [hunk 5]
```diff
@@ -47,6 +47,8 @@ std::unique_ptr<mlir::Pass> createGrandCentralPass();
 
 std::unique_ptr<mlir::Pass> createGrandCentralTapsPass();
 
+std::unique_ptr<mlir::Pass> createDetectCombLoopsPass();
```
Comment (lattner) [inline include/circt/Dialect/FIRRTL/Passes.h:50]: General comment, please name this "DetectCombCycles" instead of "loops".  "Loops" means something pretty specific in the compiler world (at least my brain is programmed to think so).  I think that "cycles" captures the more general graph property that you're checking.

File: lib/Dialect/FIRRTL/Analysis/DetectCombLoops.cpp [hunk 6]
```diff
@@ -0,0 +1,228 @@
...
+class Detector {
+public:
+  Detector(FModuleOp module,
+           DenseMap<Operation *, InputOutputPaths> &combPathsMap)
+      : module(module), combPathsMap(combPathsMap) {}
+  /// Detect combinational loops in the module.
+  void detect();
+
+  /// DFS visit a value. Return the minimum DFS index in the SCC.
+  int64_t DFSVisitValue(Value value);
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Analysis/DetectCombLoops.cpp:32]: "visit" is the verb here, I'd recommend naming this `visitValueDFS`

File: lib/Dialect/FIRRTL/Analysis/DetectCombLoops.cpp [hunk 7]
```diff
@@ -0,0 +1,228 @@
...
+  if (definingOp) {
+    // Handle instance operation.
+    if (auto instance = dyn_cast<InstanceOp>(definingOp)) {
+      if (auto referencedModule =
+              dyn_cast<FModuleOp>(instance.getReferencedModule())) {
+        // TODO: We should have a InstantiationAnalysis to construct an
+        // instantiation graph for FIRRTL or HW dialect. As a result, we can
+        // traverse the modules in a DFS order and avoid the logic here.
+        if (!combPathsMap.count(referencedModule))
+          Detector(referencedModule, combPathsMap).detect();
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Analysis/DetectCombLoops.cpp:128]: I haven't dug into the full implementation details of this, but this looks recursive on the SSA graph.  That can quickly lead to stack exhaustion, I'd recommend an iterative / worklist driven algorithm.

File: lib/Dialect/FIRRTL/Analysis/DetectCombLoops.cpp [hunk 8]
```diff
@@ -0,0 +1,228 @@
...
+        childs.push_back(connect.dest());
+    }
+  }
+
+  // Handle two special operations that may introduce extra childs.
+  if (definingOp) {
+    // Handle instance operation.
+    if (auto instance = dyn_cast<InstanceOp>(definingOp)) {
+      if (auto referencedModule =
+              dyn_cast<FModuleOp>(instance.getReferencedModule())) {
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Analysis/DetectCombLoops.cpp:123]: Plz use Andrew's fancy CallGraph analysis which will make this O(1) instead of O(n)

File: lib/Dialect/FIRRTL/Analysis/DetectCombLoops.cpp [hunk 9]
```diff
@@ -0,0 +1,228 @@
...
+  if (!definingOp && currentArg && currentArg != value) {
+    auto outputIndex = BlockArgument(value.getImpl()).getArgNumber();
+    combPaths[currentArg.getArgNumber()].push_back(outputIndex);
+  }
+
+  auto currentStackSize = valueStack.size();
+  valueStack.push_back(value);
+
+  // Collect childs of the current value.
+  SmallVector<Value> childs;
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Analysis/DetectCombLoops.cpp:107]: childs -> children

File: lib/Dialect/FIRRTL/Analysis/DetectCombLoops.cpp [hunk 10]
```diff
@@ -0,0 +1,228 @@
...
+    }
+
+    // Handle subfield operation. After lower types, subfield operations should
+    // only be used to split bundles generated by memories. Thus we need to
+    // detect whether there are combinational path between inputs (`en` and
+    // `addr`) and outputs (`data` or `rdata`).
+    if (auto subField = dyn_cast<SubfieldOp>(definingOp)) {
+      auto inputDefiningOp = subField.input().getDefiningOp();
+      if (!inputDefiningOp)
+        return subField.emitOpError("input must not be an argument"), minIndex;
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Analysis/DetectCombLoops.cpp:145]: Why not?  What phase of FIRRTL lowering does this work on?

Please make the error message more explicit about what the problem is, particularly if this is user-visible.

**Review by lattner — COMMENTED** [review]
Cool, thanks for working on this!

**Comment by hanchenye** [comment]
@lattner Thanks for the review! This is still in progress and I'm working to make it more efficient :D

**Comment by hanchenye** [comment]
Just rewrote the pass with the following updates:
1. Use test cases from [firrtlTests](https://github.com/chipsalliance/firrtl/blob/master/src/test/scala/firrtlTests/CheckCombLoopsSpec.scala) except the cases with cross module references and ext-module annotations;
2. Now construct a new graph in the pass and use `llvm::scc_iterator` to detect combinational cycles;
3. Use `llvm::df_iterator` to detect combinational paths between IOs;
4. Use `InstanceGraph` to get referenced module and determine the order of module traversing.

A question: Do we want to add `CombinationalPath` annotations in this pass?

**Comment by hanchenye** [comment]
Update: Include `ConnectOp`s when reporting combinational cycles.

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 11]
```diff
@@ -0,0 +1,470 @@
...
+    if (auto node = combGraph.getNode(connect.dest()))
+      dummyNode->addChild(node);
+  }
+
+  // Lauch SCC iteration and report diagnostics.
+  using SCCIterator = llvm::scc_iterator<CombNode>;
+  for (auto SCC = SCCIterator::begin(dummyNode); !SCC.isAtEnd(); ++SCC) {
+    if (SCC.hasCycle()) {
+      auto errorDiag = mlir::emitError(
+          module.getLoc(), "detected combinational SCC in the module");
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:357]: Nit: plainer language would make this more useful to a front end user.  E.g., a chisel user who gets this error may have no idea what an SCC is. Consider:

```suggestion
          module.getLoc(), "detected combinational cycle in a FIRRTL module");
```

Note: the usual synthesis tool error is about "combinational loops" which is unfortunate.  It is also unfortunate that "cycle" has a collision with "clock cycle".  However, "cycle" is the correct mathematical term.

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 12]
```diff
@@ -0,0 +1,470 @@
...
+      for (auto it = SCC->rbegin(); it < SCC->rend(); ++it) {
+        auto node = *it;
+        auto nodeVal = node->getValOrOp().dyn_cast<Value>();
+        auto nodeOp = node->getValOrOp().dyn_cast<Operation *>();
+
+        auto &noteDiag =
+            errorDiag.attachNote(nodeVal ? nodeVal.getLoc() : nodeOp->getLoc());
+
+        noteDiag << "see node in the combinational SCC";
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:366]: Not sure on language, but I'd avoid the SCC stuff:

```suggestion
        noteDiag << "this operation is part of the combinational cycle";
```

**Review by seldridge — COMMENTED** [review]
Error message nits.  

One huge annoyance is that most VLSI language will talk about "combinational/combinatorial loops" when they really mean "cycles".  I think it's fine to deviate here, though.

Also, can you add an option to `firtool` for this? 😄

**Comment by lattner** [comment]
great diagnostics!

File: include/circt/Dialect/FIRRTL/Passes.td [hunk 13]
```diff
@@ -210,4 +210,12 @@ def GrandCentralTaps : Pass<"firrtl-grand-central-taps", "firrtl::CircuitOp"> {
   let dependentDialects = ["sv::SVDialect"];
 }
 
+def CheckCombCycles : Pass<"firrtl-check-comb-cycles", "firrtl::CircuitOp"> {
```
Comment (lattner) [inline include/circt/Dialect/FIRRTL/Passes.td:213]: Please make this a pass that runs on ModuleOp so it runs in parallel.

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 14]
```diff
@@ -0,0 +1,472 @@
...
+// CombGraph class
+//===----------------------------------------------------------------------===//
+
+namespace {
+// This is a combinational graph contains a set of nodes.
+class CombGraph {
+public:
+  /// Get a node from the graph if it exists. Otherwise, allocate a new node and
+  /// add to the graph.
+  CombNode getOrAddNode(ValueOrOpType valOrOp, unsigned fieldID = 0) {
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:81]: This seems like it is effectively replicating the SSA graph into another datastructure.  This could make sense for SFC because it doesn't have SSA, can we avoid this in MFC?

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 15]
```diff
@@ -0,0 +1,472 @@
...
+    auto node = CombNodeImpl(valOrOp, fieldID);
+    auto it = nodes.find(&node);
+    if (it != nodes.end())
+      return *it;
+    return nullptr;
+  }
+
+private:
+  /// For allocating memories for combinational nodes.
+  llvm::BumpPtrAllocator allocator;
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:102]: `~CombGraph` needs to run the dtor on each node, because they contain smallvectors, which can allocate when exceeding their smallsize.  Not doing so will leak memory.

It'd be better to eliminate this graph entirely though :-)

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 16]
```diff
@@ -0,0 +1,472 @@
...
+/// the combinational paths between IOs of its subinstances into a subgraph and
+/// encodes them in a `combPathsMap`.
+class CheckCombCyclesPass : public CheckCombCyclesBase<CheckCombCyclesPass> {
+  void runOnOperation() override {
+    auto &instanceGraph = getAnalysis<InstanceGraph>();
+    // Traverse modules in a post order to make sure the combinational paths
+    // between IOs of a module have been detected and recorded in `combPathsMap`
+    // before we handle its parent modules.
+    for (auto node : llvm::post_order<InstanceGraph *>(&instanceGraph)) {
+      // TODO: Handle FExtModuleOp with annotations.
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:456]: Why the todo?  ExtModule's cannot have cycles since they have no body.

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 17]
```diff
@@ -0,0 +1,472 @@
...
+}
+
+/// Declaration handlers.
+bool Detector::visitDecl(InstanceOp op) {
+  SmallVector<CombNode, 8> nodes;
+  for (auto result : op.getResults())
+    nodes.push_back(combGraph.getOrAddNode(result));
+
+  // Query the combinational paths between IOs and create edges.
+  for (auto combPath :
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:225]: This is copying a combPath, i'd recommend referring to it by const& or something

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 18]
```diff
@@ -0,0 +1,472 @@
...
+    return node->child_end();
+  }
+};
+} // namespace llvm
+
+//===----------------------------------------------------------------------===//
+// Detector class
+//===----------------------------------------------------------------------===//
+
+using CombPaths = SmallDenseMap<int64_t, SmallVector<int64_t>>;
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:134]: I'm not sure what is really being modeled here, but this is a pretty expensive data structure.  Can you add comments saying more of what the key and value represent?  Also, why a sparse map from an integer to a vector?  Can this be a dense mapping (i.e. an array)?

Also, SmallVector<T> is really designed to be used on the stack.  What is the expected length of this?  It is hard for me to tell with more context on how this is being used.

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp (hunk 16 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:456]: 😅  So, there are these [`CombinationalPath` Annotations](https://www.chisel-lang.org/api/firrtl/latest/firrtl/transforms/CombinationalPath.html) which can be used to inform the compiler about a combinational path in a blackbox. This is what Hanchen is referring to, here. CIRCT can't pass all SFC tests if it doesn't support this, but I'm fine to lazily implement this once there's an obvious user.

File: include/circt/Dialect/FIRRTL/Passes.td (hunk 13 above)
Comment (hanchenye) [reply include/circt/Dialect/FIRRTL/Passes.td:213]: Auh, forgot to reply on your last comment. We need to consider cross-module combinational cycles here, because a module may have combinational paths between its IOs.

In the current implementation, we encode these combinational paths into the `CombPaths` data structure and maintain a map from `FModuleOp` to `CombPaths`. When constructing the combinational graph of a module, the combinational paths of sub-instances will be inlined into the graph. Therefore, we traverse Andrew's instance graph in a post order in this pass.

Parallelization is still possible by cutting the instance graph into a tree and running on all leaf nodes in parallel, but this will still happen inside of a `CircuitOp` pass.

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp (hunk 14 above)
Comment (hanchenye) [reply lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:81]: This is a good point. I tried to work on the SSA graph and use a customized iterator to iterate on a value/operation's children. But I found it's hard to do so, because directed edges in the combinational graph don't always flow from operands to results. For example:

1. `ConnectOp` connects the `src` operand to the `dest` operand;
2. For `InstanceOp`, we need to query `CombPaths` to determine which pairs of IOs are connected combinationally;
3. For `MemOp`, we need to connect the `en/addr` subfield and `(r)data` subfield if the read latency is zero;

And for some of them, it's not trivial to get the directed edges, such as `MemOp`. Therefore, I decided to construct a new graph for this :D

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp (hunk 15 above)
Comment (hanchenye) [reply lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:102]: Thanks for pointing out! I'll tackle this later.

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp (hunk 18 above)
Comment (hanchenye) [reply lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:134]: Sorry for the confusing :sweat_smile: This is the data structure for representing combinational paths between IOs. I'd consider in most cases, this should be a very sparse map. I'm imagining a module with AXI interfaces, say 50 IOs in total, but none or only several of them are connected combinationally. Any thoughts on this? @drom @seldridge

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp (hunk 14 above)
Comment (fabianschuiki) [reply lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:87]: Do the graph traits take references to the nodes, or do they copy them around? If it's the latter, you might be able to create the `CombNode` as a temporary thing on the stack that just lives inside the graph traits iterator. Then you can dump all the custom handling of ops in there, but don't need to push things into the allocator?

I'm looking at a similar thing in InferWidths, where it would be nice to actually not create the `Expr` graph shadowing the IR, but rather run on the IR directly.

**Review by fabianschuiki — APPROVED** [review]
This looks good from a quick 10min read-through point of view! It would be interesting to see if doing everything on the IR is possible (through the graph traits and maybe some helper/temporary nodes on the stack), or if we can't get around allocating a few `CombNode`s on the heap. The findings are likely to apply to InferWidths as well.

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 19]
```diff
@@ -0,0 +1,487 @@
...
+
+  /// Get a node from the graph if it exists. Otherwise, allocate a new node and
+  /// add to the graph.
+  CombNode getOrAddNode(ValueOrOpType valOrOp, unsigned fieldID = 0) {
+    auto it = nodes.find_as<CombNodeKeyType>({valOrOp, fieldID});
+    if (it != nodes.end())
+      return *it;
+    auto newNode = new (allocator) CombNodeImpl(valOrOp, fieldID);
+    nodes.insert(newNode);
+    return newNode;
```
[the remark this answers is not in the document]
Comment (hanchenye) [reply lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:93]: I referenced your InferWidths pass! :wink:

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 20]
```diff
@@ -0,0 +1,487 @@
...
+  // combinationally connected to it.
+  auto &combPaths = combPathsMap[module];
+  for (auto input : inputs) {
+    for (auto node : llvm::depth_first<CombNode>(combGraph.getNode(input))) {
+      if (auto val = node->getValOrOp().dyn_cast<Value>())
+        if (auto output = val.dyn_cast<BlockArgument>())
+          if (directionList[output.getArgNumber()])
+            combPaths.push_back({input.getArgNumber(), output.getArgNumber()});
+    }
+  }
```
[the remark this answers is not in the document]
Comment (hanchenye) [reply lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:412]: Exactly, will add some comments.

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 21]
```diff
@@ -0,0 +1,487 @@
...
+// Detector class
+//===----------------------------------------------------------------------===//
+
+/// This is used for storing combinational paths between IOs of a FIRRTL module.
+/// The two elements of the pair are the argument index of the input port and
+/// output port, respectively.
+using CombPaths = SmallVector<std::pair<unsigned, unsigned>>;
+
+namespace {
+class Detector : public FIRRTLVisitor<Detector, bool> {
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:142]: nit, but I think that `CycleDetector` would be more specific.

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 22]
```diff
@@ -0,0 +1,487 @@
...
+      dummyNode->addChild(node);
+  }
+
+  // Lauch SCC iteration and report diagnostics.
+  using SCCIterator = llvm::scc_iterator<CombNode>;
+  for (auto SCC = SCCIterator::begin(dummyNode); !SCC.isAtEnd(); ++SCC) {
+    if (SCC.hasCycle()) {
+      auto errorDiag = mlir::emitError(
+          module.getLoc(), "detected combinational cycle in a FIRRTL module");
+      for (auto it = SCC->rbegin(); it < SCC->rend(); ++it) {
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:365]: nit, but you don't need to evaluate `SCC->rend()` each iteration.

**Comment by hanchenye** [comment]
Thanks for all the comments! @lattner @fabianschuiki 

I just pushed a new version fully based on the SSA graph. This is just a proof of concept and has not been optimized yet. There're several annoying things I'm trying to get rid of, thus any feedback or suggestion will be super helpful to me!

1. Because now we don't have a `xxxGraph` class that contains `CombPathsMap` and `InstanceGraph`, and the `GraphTraits` request the `child_begin` and `child_end` iterators just from `NodeRef`, I must put the pointers of `CombPathsMap` and `InstanceGraph` into `NodeRef` and duplicated them for N times on stack... I'm not sure whether there's a clever way to use `GraphTraits` and get rid of this. Alternatively, we can create our own `scc_iterator` and `df_iterator` and store things there :thinking: 
2. The current implementation cannot track all "nodes" on stack as it completely based on `Value` and `use_iterator`. Specifically, the `ConnectOp`s and `MemOp`s are handled transparently in `getChildValue()` and the `SubfieldOp` handler, respectively, and will not be stored as "nodes". Therefore, the error diagnostic is not as good as the old implementation. Talked with @darthscsi on this, one possible solution is to use the efficient implementation to do the checking job, and if combinational cycles are detected, the old implementation is launched to report pretty error diagnostic.

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 23]
```diff
@@ -0,0 +1,799 @@
...
+    if (rhs == empty || rhs == tombstone)
+      return false;
+    return lhs.first == rhs->getValOrOp() && lhs.second == rhs->getFieldID();
+  }
+};
+} // namespace llvm
+
+//===----------------------------------------------------------------------===//
+// Fast implementation
+//===----------------------------------------------------------------------===//
```
Comment (hanchenye) [inline lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:459]: New implementation starting from here.

**Comment by lattner** [comment]
Yeah, this is looking good.  C++ doesn't have generators and yield, so it makes stuff like this a bit more annoying to write than it should be.  However, you've got the right thing going on: a Node struct with graphtraits defined against it, and defining the custom iteration without cloning the graph.

I'd recommend putting the CombPathsMapType+InstanceGraph pointers into a "GraphContext" object that you can put on the stack and have it contain both pointers.  This would just shrink sizeof(Node) a bit.

In order to make your iterator simpler to implement, you might try turning this:

```
class ChildIterator {
 Node node;
...
```

into something like this:

```
class ConnectNodeIterator {
  Node node;
  size_t operandNo;
}
class InstanceNodeIterator {
  Node node;
  size_t portNo;
}

class ChildIterator {
 std::variant<ConnectNodeIterator, InstanceNodeIterator, ... 
...
```

and then have `ChildIterator's ++` method dispatch to methods on `ConnectNodeIterator` etc.  Also, I'm not sure I follow the use of FilteredIterator.

**Comment by fabianschuiki** [comment]
I think the `std::variant` is a C++17 feature. In the root CMake we set C++14 as the standard for CIRCT. Do we want to bump to 17? :wink: I'd love to be able to use `std::variant` (a taste of Rust/Swift enums!) :smirk:

**Comment by lattner** [comment]
Ah, I didn't realize that.  I'm not sure if circt has a project policy on this, is std::variant well supported by MSVC?  If so, it is probably ok, but I'd ask on the CIRCT forum.  I believe (but haven't verified) that Flang is already requiring C++17 so there is some precedent for it in the llvm world.

**Comment by hanchenye** [comment]
Just created a [thread](https://llvm.discourse.group/t/rfc-update-c-standard-from-14-to-17/3951) on the CIRCT forum. I made a quick search, yes Flang is using C++17 @lattner.

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 24]
```diff
@@ -0,0 +1,893 @@
...
+    if (rhs == empty || rhs == tombstone)
+      return false;
+    return lhs.first == rhs->getValOrOp() && lhs.second == rhs->getFieldID();
+  }
+};
+} // namespace llvm
+
+//===----------------------------------------------------------------------===//
+// SSA graph based implementation
+//===----------------------------------------------------------------------===//
```
Comment (hanchenye) [inline lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:460]: The new implementation using `std::variant` starts from here.

File: CMakeLists.txt [hunk 25]
```diff
@@ -28,7 +28,7 @@ if( CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR )
 #-------------------------------------------------------------------------------
   project(circt LANGUAGES CXX C)
   
-  set(CMAKE_CXX_STANDARD 14)
+  set(CMAKE_CXX_STANDARD 17)
```
Comment (lattner) [inline CMakeLists.txt:31]: Plz merge with mainline

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 26]
```diff
@@ -0,0 +1,893 @@
...
+using child_iterator =
+    llvm::mapped_iterator<use_iterator, Value (*)(OpOperand &)>;
+
+namespace {
+/// This is a child iterator class for FIRRTL values. The base iterator is the
+/// `use_iterator` of a value. On top of the `use_iterator`, uses whose owner
+/// has no results and uses which are 'dest`s of connect ops are filtered out
+/// through the `isChild` method. Then, all the filtered uses are mapped to its
+/// corresponding child value through the `getChild` method.
+class ChildIterator : public child_iterator {
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:506]: IMO, the use of filter_iterator/mapped_iterator just makes this more complicated.  I'd recommend flattening their implementations into ChildIterator.    C++ isn't great at composing functional algorithms in this way.

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 27]
```diff
@@ -0,0 +1,893 @@
...
+
+//===----------------------------------------------------------------------===//
+// CombIterator class
+//===----------------------------------------------------------------------===//
+
+using CombIteratorBase = std::variant<DefaultNodeIterator, InstanceNodeIterator,
+                                      SubfieldNodeIterator>;
+
+namespace {
+class CombIterator : public CombIteratorBase {
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:699]: I'd recommend containing the variant as a member instead of inheriting from it.  There is no "isa" relationship with the variant type itself, though I get what you're conceptually going for here.

**Review by lattner — COMMENTED** [review]
Cool, this is looking good.  Let's go with this design, thank you for iterating on this (haha). :-)

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp (hunk 26 above)
Comment (hanchenye) [reply lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp]: Thanks for the suggestion! After dropping `filter_iterator` and `mapped_iterator`, the code is much cleaner and easy to follow now :smile:

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 28]
```diff
@@ -0,0 +1,537 @@
...
+        // FIRRTL module is an SSA region, all cycles must contain at least one
+        // connect op on its path. Thus we introduce a dummy source node to
+        // iterate on the `dest`s of all connect ops in the module.
+        using SCCIterator = llvm::scc_iterator<Node>;
+        for (auto SCC = SCCIterator::begin(dummyNode); !SCC.isAtEnd(); ++SCC) {
+          if (SCC.hasCycle()) {
+            auto errorDiag = mlir::emitError(
+                module.getLoc(),
+                "detected combinational cycle in a FIRRTL module");
+            for (auto it = SCC->begin(), e = SCC->end(); it != e; ++it) {
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:487]: Can this use a range based for loop?

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp [hunk 29]
```diff
@@ -0,0 +1,537 @@
...
+    auto users = subfield.input().getUsers();
+    for (auto it = users.begin(), e = users.end(); it != e; ++it) {
+      auto currentSubfield = dyn_cast<SubfieldOp>(*it);
+      if (!currentSubfield) {
+        it->emitOpError("MemOp must be used by SubfieldOp, please run "
+                        "-firrtl-lower-types first");
+        return;
+      }
+
+      if ((currentSubfield.fieldIndex() == 3 &&
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:257]: Is the field index "3" stable?  If so, can we use an enum defined in FIRRTLOps.h instead of a magic number?

**Review by lattner — APPROVED** [review]
great work!

File: lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp (hunk 29 above)
Comment (hanchenye) [reply lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:257]: Yes, they are fixed, according to [this discussion](https://github.com/llvm/circt/pull/1462#discussion_r674460293). Your idea sounds great. Making it a enum could avoid many unnecessary string or magic number comparison.

Comment (hanchenye) [reply lib/Dialect/FIRRTL/Transforms/CheckCombCycles.cpp:257]: I'll open another PR for this.

File: tools/firtool/firtool.cpp [hunk 30]
```diff
@@ -118,6 +118,11 @@ static cl::opt<bool>
                           "Grand Central annotations"),
                  cl::init(false));
 
+static cl::opt<bool>
+    checkCombCycles("firrtl-check-comb-cycles",
+                    cl::desc("check combinational cycles on firrtl"),
+                    cl::init(false));
```
Comment (seldridge) [inline tools/firtool/firtool.cpp:124]: For this to catch some cases that the SFC will also catch, this will need to run before IMCP (since IMCP will aggressively prune cycles). Does this continue to work if you move it up there?

Comment (hanchenye) [reply tools/firtool/firtool.cpp:124]: Moved this pass up before IMCP. It works well!
