### PR TITLE
[FIRRTL] Same defname ExtModules in LowerClasses

### LINKED ISSUE #9468: [FIRRTL] LowerClasses creates duplicate symbols for external modules with the same defname
`LowerClasses` fails to lower external modules which have properties when the external modules have the same defname. Consider the following:

``` mlir
firrtl.circuit "Foo" {
  firrtl.extmodule @Bar_1<WIDTH: ui32 = 1>(
    in a: !firrtl.integer,
    in b: !firrtl.uint<1>
  ) attributes {defname = "Bar"}
  firrtl.extmodule @Bar_2<WIDTH: ui32 = 2>(
    in a: !firrtl.integer,
    in b: !firrtl.uint<2>
  ) attributes {defname = "Bar"}
  firrtl.module @Foo() {
    %bar_1_a, %bar_1_b = firrtl.instance bar_1 @Bar_1(
      in a: !firrtl.integer,
      in b: !firrtl.uint<1>
    )
    %bar_2_a, %bar_2_b = firrtl.instance bar_2 @Bar_2(
      in a: !firrtl.integer,
      in b: !firrtl.uint<2>
    )
    %0 = firrtl.integer 0
    firrtl.propassign %bar_1_a, %0 : !firrtl.integer
    firrtl.propassign %bar_2_a, %0 : !firrtl.integer
  }
}
```

This can be compiled with:

``` console
# circt-opt -pass-pipeline='builtin.module(firrtl.circuit(firrtl-lower-classes))' Foo.mlir
Foo.mlir:6:3: error: redefinition of symbol named 'Bar_Class'
  firrtl.extmodule @Bar_2<WIDTH: ui32 = 2>(
  ^
Foo.mlir:6:3: note: see current operation: 
"om.class.extern"() <{fieldNames = [], fieldTypes = {}, formalParamNames = ["basepath", "a"], sym_name = "Bar_Class"}> ({
^bb0(%arg0: !om.basepath, %arg1: !om.integer):
}) : () -> ()
Foo.mlir:2:3: note: see existing symbol definition here
  firrtl.extmodule @Bar_1<WIDTH: ui32 = 1>(
  ^
```

I think the right thing to do here is to only create one class for each external module with that defname.

Note: the root issue here is a representational one where external modules with parameters are not actually modules, but instantiations of specific parametric modules. A much larger refactor to change this representation so that there was exactly one module for `Bar` that had parameters bound at the instantiation site and a way to represent the fact that the parameters affect the widths of ports would fix this. E.g.:

``` mlir
firrtl.circuit "Foo" {
  firrtl.extmodule @Bar<WIDTH: ui32>(
    in a: !firrtl.integer,
    in b: !firrtl.uint<WIDTH>
  )
  firrtl.module @Foo() {
    %bar_1_a, %bar_1_b = firrtl.instance bar_1 @Bar<1>(
      in a: !firrtl.integer,
      in b: !firrtl.uint<1>
    )
    %bar_2_a, %bar_2_b = firrtl.instance bar_2 @Bar<2>(
      in a: !firrtl.integer,
      in b: !firrtl.uint<2>
    )
    %0 = firrtl.integer 0
    firrtl.propassign %bar_1_a, %0 : !firrtl.integer
    firrtl.propassign %bar_2_a, %0 : !firrtl.integer
  }
}
```

### PR DESCRIPTION
**Pull request by seldridge**
Fix illegal IR that the `LowerClasses` pass would create when lowering two
FIRRTL external modules with the same defname.  These need to map to the
same class as we don't have parametric classes.

This then exposed an issue where module ports needed to be deleted
centrally as the module-to-class mapping was no longer one to one.

Fix #9468.

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp [hunk 1]
```diff
@@ -249,6 +249,13 @@ struct LowerClassesPass
 
   // State used while creating the optional 'ports' list of RtlPort objects.
   SmallVector<RtlPortsInfo> rtlPortsToCreate;
+
+  // Store of already created external classes.  External modules are not
+  // modules, but specific instantiations of a module with a given
+  // parameterization.  When this is happening, two external modules will have
+  // the same `defname`.  This is a mechanism to ensure we don't create the same
+  // external class twice.
+  DenseMap<StringRef, om::ClassLike> externalClassMap;
```
Comment (dtzSiFive) [inline lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp]: Consider `StringAttr` as key, so doesn't need to hash the string contents (or compare contents for equality).

File: lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp [hunk 2]
```diff
@@ -917,6 +933,19 @@ void LowerClassesPass::runOnOperation() {
                                          pathInfoTable);
                         });
 
+  // Erase property ports from all modules that had classes created.  This must
+  // be done separately because multiple modules can share the same class (e.g.,
+  // external modules with the same defname).
+  for (auto moduleLike : modulesToErasePortsFrom) {
+    BitVector portsToErase(moduleLike.getNumPorts());
+    for (unsigned i = 0, e = moduleLike.getNumPorts(); i < e; ++i) {
+      auto type = moduleLike.getPortType(i);
```
Comment (dtzSiFive) [inline lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp]: Consider inlining this if you'd prefer.

File: lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp [hunk 3]
```diff
@@ -1077,8 +1106,16 @@ om::ClassLike LowerClassesPass::createClass(FModuleLike moduleLike,
   om::ClassLike loweredClassOp;
   if (isa<firrtl::ExtClassOp, firrtl::FExtModuleOp>(
           moduleLike.getOperation())) {
-    loweredClassOp = convertExtClass(moduleLike, builder, className + suffix,
-                                     formalParamNames, hasContainingModule);
+    // External modules are "deduplicated" via their defname.  Don't create a
+    // new external class if we've already created one for this defname.
+    auto it = externalClassMap.find(className);
```
Comment (dtzSiFive) [inline lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp]: A good habit to get into is minimizing the number of times a lookup (/hash, red-black-tree-traversal, whatever) is performed.

Since a post-condition of these lines is that `className` will point to an extclass, consider something like attempting to insert a dummy value and overriding it with a constructed `convertExtClass(....)` should it not already be present.

For infrastructure and code that needs to scale, this sort of thinking matters and can add up.

For this? Your call :+1:.

File: lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp (hunk 1 above)
Comment (dtzSiFive) [reply lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp]: Looks like we don't have an attribute version of the accessors used to get this name here, I think?

Welp.

Something to fix at some point.

File: lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp [hunk 4]
```diff
@@ -878,7 +887,14 @@ void LowerClassesPass::runOnOperation() {
     if (shouldCreateClass(moduleLike.getModuleNameAttr())) {
       auto omClass = createClass(moduleLike, pathInfoTable, intraPassMutex);
       auto &classLoweringState = loweringState.classLoweringStateTable[omClass];
-      classLoweringState.moduleLike = moduleLike;
+      // For external modules with the same defname, the same omClass is reused.
+      // Only set moduleLike if not already set, to avoid overwriting.
```
Comment (dtzSiFive) [inline lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp:891]: I think this makes sense, but a little surprised about the `createClass` call done unconditionally, which is then used as a key into a table -- which we're here checking for having already visited.

Does `createClass` sometimes return a class already created or something?

Ah, it does after this PR.  Consider renaming it to reflect it only usually creates a class.

File: lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp (hunk 1 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp]: Good idea. I also noticed the missing member function here. I'm adding that in 3e7bbe896 and will land that part directly.

File: lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp (hunk 2 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp]: 👍 Fixed in: 0cf3955ce

File: lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp (hunk 1 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp]: Fixed in: 40a6ded55

File: lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp (hunk 3 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/Transforms/LowerClasses.cpp]: This is an interesting optimization that I hadn't noticed other places or thought about. I'm normally only thinking asymptotically about this. I.e., before this is expected time `O(1) * 2`. After this change, this is `O(1)`. This won't dramatically change anything, but it is still way better code! I like the pattern of doing the dummy insertion and then overriding it.

There's some really nice readability benefits, about what you're proposing here, too.

Nice suggestion. Fixed in: 985fd57427b9b6b1cc5840523e45416b3f9341c9
