### PR TITLE
[HandshakeToFIRRTL] Add initial values to buffer module names

### LINKED ISSUE #3180: [Handshake][IntegrationTests] Using `--handshake-insert-buffers=strategy=all` on IR with sequential buffer produces unexpected output.
I'm playing around with the CIRCT integration tests. While doing so, I discovered some very weird behaviour related to buffers with more than one initial value. 

I'm lowering the following to Verilog (through FIRRTL) and run a simulation with a driver that looks as `integration_test/Dialect/Handshake/driver.sv`, except that it expects a `i1` output. I'm using Vivado to run the simulation.

```mlir
module {
  handshake.func @top(%ctrl: none) -> (i1, none) attributes {argNames = ["inCtrl"], resNames = ["out0", "outCtrl"]} {
    // Using this causes the result to be 0/false
    %c20 = buffer [2] seq %c20 {initValues = [20 : i64, 20 : i64]} : i64 

    // Using one of the following results in the expected 1/true
    //%c20 = buffer [1] seq %c20 {initValues = [20 : i64]} : i64
    //%c20 = constant %ctrl {value = 20 : i64} : i64

    %c10 = constant %ctrl {value = 10 : i64} : i64
    %cond = arith.cmpi ne, %c20, %c10 : i64
    return %cond, %ctrl : i1, none
  }
}
```

As you see in the inline comments, this produces faulty results. 
The code can be found in the following branch: [dinistro/handshake-buffer-problem](https://github.com/llvm/circt/tree/dinistro/handshake-buffer-problem)

It turns out that removing the `--handshake-insert-buffers=strategy=all` flag fixes the issue. Does this pass have assumptions that my IR does not satisfy or is this a bug in the pass?

### PR DESCRIPTION
**Pull request by Dinistro**
This patch adds the initial values to the names of the buffer modules to create different modules for different initial values.

If added a new integration test as this bug mainly appears when the generated verilog is simulated.

Fixes #3180

### CODE REVIEW

File: lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp [hunk 1]
```diff
@@ -443,6 +443,13 @@ static std::string getSubModuleName(Operation *oldOp) {
       subModuleName += "_seq";
     else
       subModuleName += "_fifo";
+
+    if (bufferOp.initValues().hasValue()) {
+      subModuleName += "_init";
+      for (auto e : *bufferOp.initValues())
+        subModuleName +=
+            "_" + std::to_string(e.dyn_cast<IntegerAttr>().getInt());
```
Comment (mortbopet) [inline lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp:451]: Won't do much in terms of LOC, but `llvm::interleave` with a stringstream on `subModuleName` is an option.

**Review by mortbopet — APPROVED** [review]

File: lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp (hunk 1 above)
Comment (Dinistro) [reply lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp:451]: In that case one should switch to a stringstream for the whole module name, I think.

Comment (mortbopet) [reply lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp:451]: Agreed!
