### PR TITLE
[FIRRTL] Fix parsing connection between enum of uninferred width.

### LINKED ISSUE #5322: [FIRRTL] Assertion failure parsing input connecting compatible (?) enums of different width inferred-ness
Input:

```firrtl
circuit EnumWidths:
  module EnumWidths:
    input i : {| Some : UInt<8>, None |}
    input i2 : {| Some : UInt, None |}
    output o : {| Some : UInt, None |}
    output o2 : {| Some : UInt<8>, None |}
    o <= i
    o2 <= i2
```

Either connection causes an assertion failure during parsing (as of 6ff3acee7):

```
firtool: /home/will/src/sifive/circt/llvm/llvm/include/llvm/Support/Casting.h:566: decltype(auto) llvm::cast(const From &) [To = mlir::detail::TypedValue<circt::firrtl::IntType>, From = mlir::OpResult]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
PLEASE submit a bug report to https://github.com/llvm/circt and include the crash backtrace.
Stack dump:
0.	Program arguments: ./build/bin/firtool ./enum-widths.fir
 #0 0x000055778c477435 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/will/src/sifive/circt/llvm/llvm/lib/Support/Unix/Signals.inc:602:13
 #1 0x000055778c475550 llvm::sys::RunSignalHandlers() /home/will/src/sifive/circt/llvm/llvm/lib/Support/Signals.cpp:105:18
 #2 0x000055778c477aad SignalHandler(int) /home/will/src/sifive/circt/llvm/llvm/lib/Support/Unix/Signals.inc:0:3
 #3 0x00007f22f9308d60 __restore_rt (/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8/lib/libc.so.6+0x38d60)
 #4 0x00007f22f9357adc __pthread_kill_implementation (/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8/lib/libc.so.6+0x87adc)
 #5 0x00007f22f9308cb6 gsignal (/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8/lib/libc.so.6+0x38cb6)
 #6 0x00007f22f92f28ba abort (/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8/lib/libc.so.6+0x228ba)
 #7 0x00007f22f92f27d9 _nl_load_domain.cold (/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8/lib/libc.so.6+0x227d9)
 #8 0x00007f22f93019c6 (/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8/lib/libc.so.6+0x319c6)
 #9 0x000055778ca660c4 circt::firrtl::emitConnect(mlir::ImplicitLocOpBuilder&, mlir::Value, mlir::Value) /home/will/src/sifive/circt/lib/Dialect/FIRRTL/FIRRTLUtils.cpp:134:3
#10 0x000055778c4e1b89 (anonymous namespace)::FIRStmtParser::parseLeadingExpStmt(mlir::Value) /home/will/src/sifive/circt/lib/Dialect/FIRRTL/Import/FIRParser.cpp:0:5
#11 0x000055778c4db18e (anonymous namespace)::FIRStmtParser::parseSimpleStmtImpl(unsigned int) /home/will/src/sifive/circt/lib/Dialect/FIRRTL/Import/FIRParser.cpp:0:0
#12 0x000055778c4dab35 (anonymous namespace)::FIRStmtParser::parseSimpleStmt(unsigned int) /home/will/src/sifive/circt/lib/Dialect/FIRRTL/Import/FIRParser.cpp:2111:17
#13 0x000055778c4dab35 (anonymous namespace)::FIRStmtParser::parseSimpleStmtBlock(unsigned int) /home/will/src/sifive/circt/lib/Dialect/FIRRTL/Import/FIRParser.cpp:2104:9
#14 0x000055778c4da5df mlir::LogicalResult::failed() const /home/will/src/sifive/circt/llvm/mlir/include/mlir/Support/LogicalResult.h:44:33
#15 0x000055778c4da5df mlir::failed(mlir::LogicalResult) /home/will/src/sifive/circt/llvm/mlir/include/mlir/Support/LogicalResult.h:72:58
#16 0x000055778c4da5df (anonymous namespace)::FIRCircuitParser::parseModuleBody((anonymous namespace)::FIRCircuitParser::DeferredModuleToParse&) /home/will/src/sifive/circt/lib/Dialect/FIRRTL/Import/FIRParser.cpp:4077:7
#17 0x000055778c4da5df (anonymous namespace)::FIRCircuitParser::parseCircuit(llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, mlir::TimingScope&)::$_14::operator()(unsigned long) const /home/will/src/sifive/circt/lib/Dialect/FIRRTL/Import/FIRParser.cpp:4237:13
#18 0x000055778c4d5b01 mlir::LogicalResult::failed() const /home/will/src/sifive/circt/llvm/mlir/include/mlir/Support/LogicalResult.h:44:33
#19 0x000055778c4d5b01 mlir::failed(mlir::LogicalResult) /home/will/src/sifive/circt/llvm/mlir/include/mlir/Support/LogicalResult.h:72:58
#20 0x000055778c4d5b01 mlir::LogicalResult mlir::failableParallelForEach<llvm::detail::SafeIntIterator<unsigned long, false>, (anonymous namespace)::FIRCircuitParser::parseCircuit(llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, mlir::TimingScope&)::$_14>(mlir::MLIRContext*, llvm::detail::SafeIntIterator<unsigned long, false>, llvm::detail::SafeIntIterator<unsigned long, false>, (anonymous namespace)::FIRCircuitParser::parseCircuit(llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, mlir::TimingScope&)::$_14&&) /home/will/src/sifive/circt/llvm/mlir/include/mlir/IR/Threading.h:46:11
#21 0x000055778c4d5b01 mlir::LogicalResult mlir::failableParallelForEach<llvm::iota_range<unsigned long>, (anonymous namespace)::FIRCircuitParser::parseCircuit(llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, mlir::TimingScope&)::$_14>(mlir::MLIRContext*, llvm::iota_range<unsigned long>&&, (anonymous namespace)::FIRCircuitParser::parseCircuit(llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, mlir::TimingScope&)::$_14&&) /home/will/src/sifive/circt/llvm/mlir/include/mlir/IR/Threading.h:92:10
#22 0x000055778c4d5b01 mlir::LogicalResult mlir::failableParallelForEachN<(anonymous namespace)::FIRCircuitParser::parseCircuit(llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, mlir::TimingScope&)::$_14>(mlir::MLIRContext*, unsigned long, unsigned long, (anonymous namespace)::FIRCircuitParser::parseCircuit(llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, mlir::TimingScope&)::$_14&&) /home/will/src/sifive/circt/llvm/mlir/include/mlir/IR/Threading.h:107:10
#23 0x000055778c4d5b01 (anonymous namespace)::FIRCircuitParser::parseCircuit(llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, llvm::SmallVectorImpl<llvm::MemoryBuffer const*>&, mlir::TimingScope&) /home/will/src/sifive/circt/lib/Dialect/FIRRTL/Import/FIRParser.cpp:4235:20
#24 0x000055778c4d5b01 circt::firrtl::importFIRFile(llvm::SourceMgr&, mlir::MLIRContext*, mlir::TimingScope&, circt::firrtl::FIRParserOptions) /home/will/src/sifive/circt/lib/Dialect/FIRRTL/Import/FIRParser.cpp:4305:12
#25 0x000055778c3cbb62 std::enable_if<__and_<std::__not_<std::__is_tuple_like<mlir::ModuleOp>>, std::is_move_constructible<mlir::ModuleOp>, std::is_move_assignable<mlir::ModuleOp>>::value, void>::type std::swap<mlir::ModuleOp>(mlir::ModuleOp&, mlir::ModuleOp&) /nix/store/aafdki1nf49k5vxq6gx2yabiybk2bjmw-gcc-12.2.0/include/c++/12.2.0/bits/move.h:205:11
#26 0x000055778c3cbb62 mlir::OwningOpRef<mlir::ModuleOp>::release() /home/will/src/sifive/circt/llvm/mlir/include/mlir/IR/OwningOpRef.h:68:5
#27 0x000055778c3cbb62 mlir::OwningOpRef<mlir::ModuleOp>::operator=(mlir::OwningOpRef<mlir::ModuleOp>&&) /home/will/src/sifive/circt/llvm/mlir/include/mlir/IR/OwningOpRef.h:45:16
#28 0x000055778c3cbb62 processBuffer(mlir::MLIRContext&, mlir::TimingScope&, llvm::SourceMgr&, std::optional<std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile>>>&) /home/will/src/sifive/circt/tools/firtool/firtool.cpp:286:12
#29 0x000055778c3cb56f processInputSplit(mlir::MLIRContext&, mlir::TimingScope&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, std::optional<std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile>>>&) /home/will/src/sifive/circt/tools/firtool/firtool.cpp:452:12
#30 0x000055778c3cb105 processInput(mlir::MLIRContext&, mlir::TimingScope&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, std::optional<std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile>>>&) /home/will/src/sifive/circt/tools/firtool/firtool.cpp:468:12
#31 0x000055778c3cb105 executeFirtool(mlir::MLIRContext&) /home/will/src/sifive/circt/tools/firtool/firtool.cpp:552:14
#32 0x000055778c3cace6 mlir::LogicalResult::failed() const /home/will/src/sifive/circt/llvm/mlir/include/mlir/Support/LogicalResult.h:44:33
#33 0x000055778c3cace6 mlir::failed(mlir::LogicalResult) /home/will/src/sifive/circt/llvm/mlir/include/mlir/Support/LogicalResult.h:72:58
#34 0x000055778c3cace6 main /home/will/src/sifive/circt/tools/firtool/firtool.cpp:616:8
#35 0x00007f22f92f3ace __libc_start_call_main (/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8/lib/libc.so.6+0x23ace)
#36 0x00007f22f92f3b89 __libc_start_main@GLIBC_2.2.5 (/nix/store/1n2l5law9g3b77hcfyp50vrhhssbrj5g-glibc-2.37-8/lib/libc.so.6+0x23b89)
#37 0x000055778c3cab15 _start (./build/bin/firtool+0x50db15)
zsh: IOT instruction (core dumped)  ./build/bin/firtool ./enum-widths.fir
```

### PR DESCRIPTION
**Pull request by dtzSiFive**
Fixes #5322.

cc #5884 and #5886.

### CODE REVIEW

File: lib/Dialect/FIRRTL/FIRRTLUtils.cpp [hunk 1]
```diff
@@ -106,7 +106,6 @@ void circt::firrtl::emitConnect(ImplicitLocOpBuilder &builder, Value dst,
     // Const-cast as needed, using widthless version of dest.
     // (dest is either widthless already, or source is and if the types
     //  can be const-cast'd, do so)
-    assert(srcType.isGround() && dstType.isGround());
```
Comment (trilorez) [inline lib/Dialect/FIRRTL/FIRRTLUtils.cpp:109]: Line 99 above refers to `ground` types, I suppose that can be removed or changed to `passive`

**Review by trilorez — APPROVED** [review]

File: lib/Dialect/FIRRTL/FIRRTLUtils.cpp (hunk 1 above)
Comment (dtzSiFive) [reply lib/Dialect/FIRRTL/FIRRTLUtils.cpp:109]: Good call, thank you!

**Comment by dtzSiFive** [comment]
Thanks!
