### PR TITLE
[FIRRTL][InferWidths] Fix back-prop, fix ref equality, fix upper bound.

### LINKED ISSUE #5002: [InferWidths] Constrain ref.define operands to same width
Width-inference is supported through references, in the direction the reference itself flows.  Nothing done at the other end of the reference, including using in a `force` or similar, should influence the generated hardware the reference targets (assuming no cycles involving references).

However, the inferred widths need to be consistent along the path (if not possible, error), compared to the "max of all drivers" (minimum width that makes all connections legal, anyway) approach for other operations, like connect.
This is not handled presently, and causes invalid IR.
Ideally this would be modeled / checked as part of InferWidths, generating the same nice diagnostics as other width inference issues.

An equality constraint may be needed (like attach), although the direction the constraints "flow" may matter (unlike for `attach`).  Offhand I'm not sure whether the same approach used for `attach` will handle this correctly.

Example not handled currently, not exhaustive:
```firrtl
// -----
firrtl.circuit "RefDefineEqual" {
  firrtl.module private @InRef(in %ref : !firrtl.rwprobe<uint>) { }
  firrtl.module @RefDefineEqual(in %x : !firrtl.uint<1>, in %y : !firrtl.uint<2>) {
    %w1, %w1_ref = firrtl.wire forceable : !firrtl.uint, !firrtl.rwprobe<uint>
    %w2, %w2_ref = firrtl.wire forceable : !firrtl.uint, !firrtl.rwprobe<uint>
    firrtl.connect %w1, %x : !firrtl.uint, !firrtl.uint<1>
    firrtl.connect %w2, %y : !firrtl.uint, !firrtl.uint<2>

    %inst1_ref = firrtl.instance inst1 @InRef(in ref: !firrtl.rwprobe<uint>)
    %inst2_ref = firrtl.instance inst2 @InRef(in ref: !firrtl.rwprobe<uint>)
    firrtl.ref.define %inst1_ref, %w1_ref : !firrtl.rwprobe<uint>
    firrtl.ref.define %inst2_ref, %w2_ref : !firrtl.rwprobe<uint>
  }
}
```

This infers the input reference to the `uint<2>` which causes problems for the `rwprobe<uint<1>>` (via `%w2_ref`, via `%y`) being connected to it.

This should be reported as unsatisfiable.

### LINKED ISSUE #5391: [FIRRTL] Width inference bug as of 1.40.0
Input:

```firrtl
circuit Widths:
  module Widths:
    input x : UInt<1>
    input y : UInt<2>
    output out1 : UInt
    output out2 : UInt

    wire w : UInt
    w <= x
    w <= y

    out1 <= w

    wire wx : UInt
    wx <= x

    out2 <= wx
```

firtool:

```systemverilog
// Generated by CIRCT firtool-1.43.0-53-g60763f2c0
module Widths(
  input        x,
  input  [1:0] y,
  output [1:0] out1,
               out2
);

  assign out1 = y;
  assign out2 = {1'h0, x};
endmodule
```

Note that `wx` / `out2` are inferred to have width 2 instead of the expected 1.

firtool 1.39.0 infers this correctly: (1.40.0 does not-- first release w/uninferred width cast FWIW)
```systemverilog
// Generated by CIRCT firtool-1.39.0
module Widths(
  input        x,
  input  [1:0] y,
  output [1:0] out1,
  output       out2
);

  assign out1 = y;
  assign out2 = x;
endmodule
```

### PR DESCRIPTION
**Pull request by dtzSiFive**
Fix upperBoundSolution being set from bool indicating if cycle, instead of the value solved for (.first instead of .second).

Tweak how/when upper bound constraint is solved.

Fixes #5002.
Fixes #5391.

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/InferWidths.cpp [hunk 1]
```diff
@@ -887,9 +887,14 @@ static ExprSolution solveExpr(Expr *expr, SmallPtrSetImpl<Expr *> &seenVars,
...
-            if (expr->upperBound)
-              expr->upperBoundSolution = solvedExprs[expr->upperBound].second;
-
+            // If we've solved the upper bound already, store the solution.
+            // This will be explicitly solved for later if not computed as
+            // part of the solving that resolved this constraint.
+            // This should only happen if somehow the constraint is
+            // solved before visiting this expression, so that our upperBound
+            // was not added to the worklist such that it was handled first.
+            if (expr->upperBound && solvedExprs.contains(expr->upperBound))
```
Comment (dtzSiFive) [inline lib/Dialect/FIRRTL/Transforms/InferWidths.cpp:896]: I'm not sure we don't need to handle this re:seenVars and checkCycles/etc.?
Or if constraint expressions can be re-used such that we could have solution for the constraint w/o having put the upper bound on the worklist first?

File: lib/Dialect/FIRRTL/Transforms/InferWidths.cpp [hunk 2]
```diff
@@ -1819,7 +1821,7 @@ void InferenceMapping::constrainTypes(Value larger, Value smaller) {
         } else if (type.isGround()) {
           // Leaf element, look up their expressions, and create the constraint.
           constrainTypes(getExpr(FieldRef(larger, fieldID)),
-                         getExpr(FieldRef(smaller, fieldID)));
+                         getExpr(FieldRef(smaller, fieldID)), false, equal);
```
Comment (dtzSiFive) [inline lib/Dialect/FIRRTL/Transforms/InferWidths.cpp:1824]: Don't love this re:bools and ergonomics but wanted to get this reviewed for functionality first, but once that seems good suggestions on improvements welcome (please!). FWIW--  imposeUpperBounds adds LEQ in compatible way to GEQ (if x >= y is requested, it'll add y <= x if x isn't free variable), where-as "equal" causes LEQ (x >= y && x <= y) to be added.  Anyway.

**Comment by dtzSiFive** [comment]
Note that the discussion on whether `widthCast` should actually/correctly be "Pure" still is open, but at least this avoids known inference mistakes.

**Review by fabianschuiki — APPROVED** [review]
This looks good to me! Since this is mostly touching the `upperBound`, which isn't used for most of the widths, this shouldn't have any impact on existing width inference.

I wish there was a saner way to do width inference overall than building this shadow expression graph and then running this custom solver. Problem for another day :wink:

**Comment by dtzSiFive** [comment]
> This looks good to me! Since this is mostly touching the `upperBound`, which isn't used for most of the widths, this shouldn't have any impact on existing width inference.

FWIW this explicitly fixes a bug where we inferred wrong widths, not involving upper bound, mostly because the operation-visiting code put constraints in both directions so we propagated the wrong way (perhaps because didn't have a way to express what it wanted re:new `equal`).
But insofar as this means "impact on existing width inference [done by solver]", totally and agreed re:finding a better way :smile: .

**Comment by dtzSiFive** [comment]
tyvm for review and discussion/explanation!
