### PR TITLE
[FIRRTL][InferResets] Handle RefType, send, resolve.

### LINKED ISSUE #3717: [FIRRTL][InferResets] Support RefType, at least don't crash
RefType currently causes InferReset to crash.

Example:
```mlir
firrtl.circuit "xmr" {
  firrtl.module private @Test(in %p: !firrtl.uint<1>, out %x: !firrtl.ref<uint<2>>) {
    %w = firrtl.wire : !firrtl.uint<2>
    %1 = firrtl.ref.send %w : !firrtl.uint<2>
    firrtl.strictconnect %x, %1 : !firrtl.ref<uint<2>>
  }
  firrtl.module @xmr(in %p: !firrtl.uint<1>) {
    %test_in, %test_x = firrtl.instance test @Test(in p: !firrtl.uint<1>, out x: !firrtl.ref<uint<2>>)
    firrtl.strictconnect %test_in, %p : !firrtl.uint<1>
    %x = firrtl.ref.resolve %test_x : !firrtl.ref<uint<2>>
  }
}
```

Crash when pointing `firtool` at this:
```
firtool: /home/will/src/sifive/circt/llvm/mlir/include/mlir/IR/Types.h:279: U mlir::Type::cast() const [U = circt::firrtl::FIRRTLBaseType]: Assertion `isa<U>()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ./build/bin/firtool ./xmr.mlir
 #0 0x00000000005e8046 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/will/src/sifive/circt/llvm/llvm/lib/Support/Unix/Signals.inc:569:13
 #1 0x00000000005e64d5 llvm::sys::RunSignalHandlers() /home/will/src/sifive/circt/llvm/llvm/lib/Support/Signals.cpp:104:18
 #2 0x00000000005e83df SignalHandler(int) /home/will/src/sifive/circt/llvm/llvm/lib/Support/Unix/Signals.inc:0:3
 #3 0x00007eff35b9d0e0 __restore_rt (/nix/store/bvy2z17rzlvkx2sj7fy99ajm853yv898-glibc-2.34-210/lib/libc.so.6+0x3d0e0)
 #4 0x00007eff35be7c1f __pthread_kill_implementation (/nix/store/bvy2z17rzlvkx2sj7fy99ajm853yv898-glibc-2.34-210/lib/libc.so.6+0x87c1f)
 #5 0x00007eff35b9d042 gsignal (/nix/store/bvy2z17rzlvkx2sj7fy99ajm853yv898-glibc-2.34-210/lib/libc.so.6+0x3d042)
 #6 0x00007eff35b8849c abort (/nix/store/bvy2z17rzlvkx2sj7fy99ajm853yv898-glibc-2.34-210/lib/libc.so.6+0x2849c)
 #7 0x00007eff35b883d5 _nl_load_domain.cold.0 (/nix/store/bvy2z17rzlvkx2sj7fy99ajm853yv898-glibc-2.34-210/lib/libc.so.6+0x283d5)
 #8 0x00007eff35b96062 (/nix/store/bvy2z17rzlvkx2sj7fy99ajm853yv898-glibc-2.34-210/lib/libc.so.6+0x36062)
 #9 0x00000000007344c6 (anonymous namespace)::InferResetsPass::traceResets(mlir::Value, mlir::Value, mlir::Location) /home/will/src/sifive/circt/lib/Dialect/FIRRTL/Transforms/InferResets.cpp:0:0
#10 0x00000000007338e6 void llvm::function_ref<void (mlir::Operation*)>::callback_fn<(anonymous namespace)::InferResetsPass::traceResets(circt::firrtl::CircuitOp)::$_22>(long, mlir::Operation*) /home/will/src/sifive/circt/llvm/mlir/include/mlir/IR/OpDefinition.h:0:0
#11 0x00000000008d686e mlir::detail::walk(mlir::Operation*, llvm::function_ref<void (mlir::Operation*)>, mlir::WalkOrder) /home/will/src/sifive/circt/llvm/mlir/lib/IR/Visitors.cpp:0:9
#12 0x00000000008d686e mlir::detail::walk(mlir::Operation*, llvm::function_ref<void (mlir::Operation*)>, mlir::WalkOrder) /home/will/src/sifive/circt/llvm/mlir/lib/IR/Visitors.cpp:0:9
#13 0x000000000072d7a3 (anonymous namespace)::InferResetsPass::runOnOperationInner() /home/will/src/sifive/circt/lib/Dialect/FIRRTL/Transforms/InferResets.cpp:515:14
#14 0x000000000072cee6 std::_Rb_tree<llvm::EquivalenceClasses<(anonymous namespace)::ResetSignal, std::less<(anonymous namespace)::ResetSignal> >::ECValue, llvm::EquivalenceClasses<(anonymous namespace)::ResetSignal, std::less<(anonymous namespace)::ResetSignal> >::ECValue, std::_Identity<llvm::EquivalenceClasses<(anonymous namespace)::ResetSignal, std::less<(anonymous namespace)::ResetSignal> >::ECValue>, llvm::EquivalenceClasses<(anonymous namespace)::ResetSignal, std::less<(anonymous namespace)::ResetSignal> >::ECValueComparator, std::allocator<llvm::EquivalenceClasses<(anonymous namespace)::ResetSignal, std::less<(anonymous namespace)::ResetSignal> >::ECValue> >::_Rb_tree_impl<llvm::EquivalenceClasses<(anonymous namespace)::ResetSignal, std::less<(anonymous namespace)::ResetSignal> >::ECValueComparator, false>::_Rb_tree_impl() /nix/store/ck3jkdhlvqznybcq4s4s3hp2qyqp5kkm-gcc-11.3.0/include/c++/11.3.0/bits/stl_tree.h:672:4
#15 0x000000000072cee6 std::_Rb_tree<llvm::EquivalenceClasses<(anonymous namespace)::ResetSignal, std::less<(anonymous namespace)::ResetSignal> >::ECValue, llvm::EquivalenceClasses<(anonymous namespace)::ResetSignal, std::less<(anonymous namespace)::ResetSignal> >::ECValue, std::_Identity<llvm::EquivalenceClasses<(anonymous namespace)::ResetSignal, std::less<(anonymous namespace)::ResetSignal> >::ECValue>, llvm::EquivalenceClasses<(anonymous namespace)::ResetSignal, std::less<(anonymous namespace)::ResetSignal> >::ECValueComparator, std::allocator<llvm::EquivalenceClasses<(anonymous namespace)::ResetSignal, std::less<(anonymous namespace)::ResetSignal> >::ECValue> >::_Rb_tree() /nix/store/ck3jkdhlvqznybcq4s4s3hp2qyqp5kkm-gcc-11.3.0/include/c++/11.3.0/bits/stl_tree.h:928:7
#16 0x000000000072cee6 std::set<llvm::EquivalenceClasses<(anonymous namespace)::ResetSignal, std::less<(anonymous namespace)::ResetSignal> >::ECValue, llvm::EquivalenceClasses<(anonymous namespace)::ResetSignal, std::less<(anonymous namespace)::ResetSignal> >::ECValueComparator, std::allocator<llvm::EquivalenceClasses<(anonymous namespace)::ResetSignal, std::less<(anonymous namespace)::ResetSignal> >::ECValue> >::set() /nix/store/ck3jkdhlvqznybcq4s4s3hp2qyqp5kkm-gcc-11.3.0/include/c++/11.3.0/bits/stl_set.h:167:7
#17 0x000000000072cee6 llvm::EquivalenceClasses<(anonymous namespace)::ResetSignal, std::less<(anonymous namespace)::ResetSignal> >::EquivalenceClasses() /home/will/src/sifive/circt/llvm/llvm/include/llvm/ADT/EquivalenceClasses.h:142:3
#18 0x000000000072cee6 (anonymous namespace)::InferResetsPass::runOnOperation() /home/will/src/sifive/circt/lib/Dialect/FIRRTL/Transforms/InferResets.cpp:501:18
#19 0x0000000000c6d550 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) /home/will/src/sifive/circt/llvm/mlir/lib/Pass/Pass.cpp:0:11
```
Certainly the crashing behavior is no good, but ideally we'd also support RefType's in the EC net calculations and update them appropriately for inferred reset type.

### PR DESCRIPTION
**Pull request by dtzSiFive**
Fixes #3717.

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/InferResets.cpp [hunk 1]
```diff
@@ -1142,8 +1166,16 @@ static FIRRTLBaseType updateType(FIRRTLBaseType oldType, unsigned fieldID,
...
+  auto oldType = field.getValue().getType().cast<FIRRTLType>();
+  FIRRTLType newType =
+      TypeSwitch<FIRRTLType, FIRRTLType>(oldType)
+          .Case<FIRRTLBaseType>([&](auto base) {
+            return updateType(base, field.getFieldID(), resetType);
+          })
+          .Case<RefType>([&](auto ref) {
+            return RefType::get(
+                updateType(ref.getType(), field.getFieldID(), resetType));
+          });
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/Transforms/InferResets.cpp:1178]: This type of stuff feels a lot like we want a `map` function defined for `FIRRTLType`.

**Review by seldridge — APPROVED** [review]
LGTM

File: lib/Dialect/FIRRTL/Transforms/InferResets.cpp (hunk 1 above)
Comment (dtzSiFive) [reply lib/Dialect/FIRRTL/Transforms/InferResets.cpp:1178]: Good call, agreed! Will add something like this in a follow-up PR (it'll be useful in a few places..).
