### PR TITLE
[LLHD] Lower processes that have ops ahead of convergence block

### LINKED ISSUE #8799: [LLHD] Snitch register file processes fails lowering
The following IR extracted from the Snitch RISC-V core fails in the LowerProcesses pass:
```mlir
// -----// IR Dump Before LowerProcessesPass (llhd-lower-processes) //----- //
hw.module @snitch_regfile(in %clk_i : i1, in %raddr_i : !hw.array<2xi5>, out rdata_o : !hw.array<2xi32>, in %waddr_i : !hw.array<1xi5>, in %wdata_i : !hw.array<1xi32>, in %we_i : i1) {
  %0 = llhd.constant_time <0ns, 0d, 1e>
  %true = hw.constant true
  %c0_i31 = hw.constant 0 : i31
  %c-1_i5 = hw.constant -1 : i5
  %c0_i27 = hw.constant 0 : i27
  %c0_i0 = hw.constant 0 : i0
  %c0_i1024 = hw.constant 0 : i1024
  %c0_i5 = hw.constant 0 : i5
  %c0_i64 = hw.constant 0 : i64
  %false = hw.constant false
  %c0_i32 = hw.constant 0 : i32
  %c1_i32 = hw.constant 1 : i32
  %c32_i32 = hw.constant 32 : i32
  %clk_i_0 = llhd.sig name "clk_i" %false : i1
  %1 = llhd.prb %clk_i_0 : !hw.inout<i1>
  %2 = hw.bitcast %c0_i64 : (i64) -> !hw.array<2xi32>
  %false_1 = hw.constant false
  %3 = hw.array_get %2[%false_1] : !hw.array<2xi32>, i1
  %rdata_o = llhd.sig %3 : i32
  %true_2 = hw.constant true
  %4 = hw.array_get %2[%true_2] : !hw.array<2xi32>, i1
  %rdata_o_3 = llhd.sig name "rdata_o" %4 : i32
  %5 = hw.bitcast %c0_i5 : (i5) -> !hw.array<1xi5>
  %c0_i0_4 = hw.constant 0 : i0
  %6 = hw.array_get %5[%c0_i0_4] : !hw.array<1xi5>, i0
  %waddr_i_5 = llhd.sig name "waddr_i" %6 : i5
  %7 = hw.bitcast %c0_i32 : (i32) -> !hw.array<1xi32>
  %c0_i0_6 = hw.constant 0 : i0
  %8 = hw.array_get %7[%c0_i0_6] : !hw.array<1xi32>, i0
  %wdata_i_7 = llhd.sig name "wdata_i" %8 : i32
  %9 = llhd.prb %wdata_i_7 : !hw.inout<i32>
  %we_i_8 = llhd.sig name "we_i" %false : i1
  %10 = hw.bitcast %c0_i1024 : (i1024) -> !hw.array<32xi32>
  %mem = llhd.sig %10 : !hw.array<32xi32>
  %we_dec = llhd.sig %7 : !hw.array<1xi32>
  %11 = llhd.prb %waddr_i_5 : !hw.inout<i5>
  %12 = hw.array_create %11 : i5
  %13 = llhd.prb %we_dec : !hw.inout<array<1xi32>>
  %14 = llhd.prb %we_i_8 : !hw.inout<i1>
  %15 = llhd.constant_time <0ns, 0d, 1e>
  %16:2 = llhd.process -> !hw.array<1xi32>, i1 {
    %false_12 = hw.constant false
    cf.br ^bb2(%c0_i32, %11, %13, %false_12, %14 : i32, i5, !hw.array<1xi32>, i1, i1)
  ^bb1:  // pred: ^bb9
    %false_13 = hw.constant false
    cf.br ^bb2(%c0_i32, %11, %13, %false_13, %14 : i32, i5, !hw.array<1xi32>, i1, i1)
  ^bb2(%32: i32, %33: i5, %34: !hw.array<1xi32>, %35: i1, %36: i1):  // 3 preds: ^bb0, ^bb1, ^bb8
    %37 = comb.icmp eq %32, %c0_i32 : i32
    cf.cond_br %37, ^bb3(%c0_i32, %34, %35 : i32, !hw.array<1xi32>, i1), ^bb9
  ^bb3(%38: i32, %39: !hw.array<1xi32>, %40: i1):  // 2 preds: ^bb2, ^bb7
    %41 = comb.icmp ult %38, %c32_i32 : i32
    cf.cond_br %41, ^bb4, ^bb8
  ^bb4:  // pred: ^bb3
    %42 = hw.array_create %33 : i5
    %43 = comb.icmp eq %32, %c0_i32 : i32
    %44 = comb.extract %32 from 0 : (i32) -> i0
    %45 = comb.mux %43, %44, %c0_i0 : i0
    %46 = hw.array_get %42[%45] : !hw.array<1xi5>, i0
    %47 = comb.concat %c0_i27, %46 : i27, i5
    %48 = comb.icmp eq %47, %38 : i32
    cf.cond_br %48, ^bb5, ^bb6
  ^bb5:  // pred: ^bb4
    %49 = comb.extract %38 from 5 : (i32) -> i27
    %50 = comb.icmp eq %49, %c0_i27 : i27
    %51 = comb.extract %38 from 0 : (i32) -> i5
    %52 = comb.mux %50, %51, %c-1_i5 : i5
    %53 = comb.extract %32 from 1 : (i32) -> i31
    %54 = comb.extract %32 from 0 : (i32) -> i1
    %55 = comb.icmp ne %53, %c0_i31 : i31
    %56 = comb.or %55, %54 : i1
    %57 = comb.shru %36, %56 : i1
    %58 = hw.array_get %39[%45] : !hw.array<1xi32>, i0
    %c0_i27_14 = hw.constant 0 : i27
    %59 = comb.concat %c0_i27_14, %52 : i27, i5
    %c1_i32_15 = hw.constant 1 : i32
    %60 = comb.shl %c1_i32_15, %59 : i32
    %c-1_i32 = hw.constant -1 : i32
    %61 = comb.xor bin %60, %c-1_i32 : i32
    %62 = comb.and %58, %61 : i32
    %c0_i31_16 = hw.constant 0 : i31
    %63 = comb.concat %c0_i31_16, %57 : i31, i1
    %64 = comb.shl %63, %59 : i32
    %65 = comb.or %62, %64 : i32
    %66 = hw.array_inject %39[%45], %65 : !hw.array<1xi32>, i0
    cf.br ^bb7(%66 : !hw.array<1xi32>)
  ^bb6:  // pred: ^bb4
    %67 = comb.extract %38 from 5 : (i32) -> i27
    %68 = comb.icmp eq %67, %c0_i27 : i27
    %69 = comb.extract %38 from 0 : (i32) -> i5
    %70 = comb.mux %68, %69, %c-1_i5 : i5
    %71 = hw.array_get %39[%45] : !hw.array<1xi32>, i0
    %c0_i27_17 = hw.constant 0 : i27
    %72 = comb.concat %c0_i27_17, %70 : i27, i5
    %c1_i32_18 = hw.constant 1 : i32
    %73 = comb.shl %c1_i32_18, %72 : i32
    %c-1_i32_19 = hw.constant -1 : i32
    %74 = comb.xor bin %73, %c-1_i32_19 : i32
    %75 = comb.and %71, %74 : i32
    %c0_i31_20 = hw.constant 0 : i31
    %c0_i32_21 = hw.constant 0 : i32
    %76 = comb.shl %c0_i32_21, %72 : i32
    %77 = comb.or %75, %76 : i32
    %78 = hw.array_inject %39[%45], %77 : !hw.array<1xi32>, i0
    cf.br ^bb7(%78 : !hw.array<1xi32>)
  ^bb7(%79: !hw.array<1xi32>):  // 2 preds: ^bb5, ^bb6
    %true_22 = hw.constant true
    %80 = comb.add %38, %c1_i32 : i32
    cf.br ^bb3(%80, %79, %true_22 : i32, !hw.array<1xi32>, i1)
  ^bb8:  // pred: ^bb3
    %81 = comb.add %32, %c1_i32 : i32
    cf.br ^bb2(%81, %33, %39, %40, %36 : i32, i5, !hw.array<1xi32>, i1, i1)
  ^bb9:  // pred: ^bb2
    llhd.wait yield (%34, %35 : !hw.array<1xi32>, i1), (%12, %13, %14 : !hw.array<1xi5>, !hw.array<1xi32>, i1), ^bb1
  }
  llhd.drv %we_dec, %16#0 after %15 if %16#1 : !hw.inout<array<1xi32>>
  %17 = llhd.constant_time <0ns, 1d, 0e>
  %18:2 = llhd.combinational -> !hw.array<32xi32>, i1 {
    %true_12 = hw.constant true
    %false_13 = hw.constant false
    %c0_i1024_14 = hw.constant 0 : i1024
    %32 = hw.bitcast %c0_i1024_14 : (i1024) -> !hw.array<32xi32>
    cf.br ^bb1(%true_12, %32, %false_13 : i1, !hw.array<32xi32>, i1)
  ^bb1(%33: i1, %34: !hw.array<32xi32>, %35: i1):  // pred: ^bb0
    cf.br ^bb2(%c0_i32, %22, %false_13 : i32, !hw.array<32xi32>, i1)
  ^bb2(%36: i32, %37: !hw.array<32xi32>, %38: i1):  // 2 preds: ^bb1, ^bb6
    %39 = comb.icmp eq %36, %c0_i32 : i32
    cf.cond_br %39, ^bb3(%c0_i32, %37 : i32, !hw.array<32xi32>), ^bb4(%true_12, %37, %38 : i1, !hw.array<32xi32>, i1)
  ^bb3(%40: i32, %41: !hw.array<32xi32>):  // 2 preds: ^bb2, ^bb8
    %42 = comb.icmp ult %40, %c32_i32 : i32
    cf.cond_br %42, ^bb5, ^bb6
  ^bb4(%43: i1, %44: !hw.array<32xi32>, %45: i1):  // pred: ^bb2
    llhd.yield %44, %45 : !hw.array<32xi32>, i1
  ^bb5:  // pred: ^bb3
    %46 = comb.icmp eq %36, %c0_i32 : i32
    %47 = comb.extract %36 from 0 : (i32) -> i0
    %48 = comb.mux %46, %47, %c0_i0 : i0
    %49 = hw.array_get %13[%48] : !hw.array<1xi32>, i0
    %50 = comb.shru %49, %40 : i32
    %51 = comb.extract %50 from 0 : (i32) -> i1
    cf.cond_br %51, ^bb7, ^bb8(%41 : !hw.array<32xi32>)
  ^bb6:  // pred: ^bb3
    %52 = hw.array_inject %41[%c0_i5], %c0_i32 : !hw.array<32xi32>, i5
    %53 = comb.add %36, %c1_i32 : i32
    cf.br ^bb2(%53, %52, %true_12 : i32, !hw.array<32xi32>, i1)
  ^bb7:  // pred: ^bb5
    %54 = comb.extract %40 from 5 : (i32) -> i27
    %55 = comb.icmp eq %54, %c0_i27 : i27
    %56 = comb.extract %40 from 0 : (i32) -> i5
    %57 = comb.mux %55, %56, %c-1_i5 : i5
    %58 = hw.array_create %9 : i32
    %59 = hw.array_inject %41[%57], %9 : !hw.array<32xi32>, i5
    cf.br ^bb8(%59 : !hw.array<32xi32>)
  ^bb8(%60: !hw.array<32xi32>):  // 2 preds: ^bb5, ^bb7
    %61 = comb.add %40, %c1_i32 : i32
    cf.br ^bb3(%61, %60 : i32, !hw.array<32xi32>)
  }
  %19 = seq.to_clock %1
  %20 = comb.mux bin %18#1, %18#0, %mem_9 : !hw.array<32xi32>
  %mem_9 = seq.firreg %20 clock %19 {name = "mem"} : !hw.array<32xi32>
  %21 = llhd.constant_time <0ns, 0d, 1e>
  llhd.drv %mem, %mem_9 after %21 : !hw.inout<array<32xi32>>
  %22 = llhd.prb %mem : !hw.inout<array<32xi32>>
  %23 = hw.array_get %raddr_i[%false] : !hw.array<2xi5>, i1
  %24 = hw.array_get %22[%23] : !hw.array<32xi32>, i5
  llhd.drv %rdata_o, %24 after %0 : !hw.inout<i32>
  %25 = hw.array_get %raddr_i[%true] : !hw.array<2xi5>, i1
  %26 = hw.array_get %22[%25] : !hw.array<32xi32>, i5
  llhd.drv %rdata_o_3, %26 after %0 : !hw.inout<i32>
  llhd.drv %clk_i_0, %clk_i after %0 : !hw.inout<i1>
  %27 = llhd.prb %rdata_o : !hw.inout<i32>
  %28 = llhd.prb %rdata_o_3 : !hw.inout<i32>
  %29 = hw.array_create %27, %28 : i32
  %c0_i0_10 = hw.constant 0 : i0
  %30 = hw.array_get %waddr_i[%c0_i0_10] : !hw.array<1xi5>, i0
  llhd.drv %waddr_i_5, %30 after %0 : !hw.inout<i5>
  %c0_i0_11 = hw.constant 0 : i0
  %31 = hw.array_get %wdata_i[%c0_i0_11] : !hw.array<1xi32>, i0
  llhd.drv %wdata_i_7, %31 after %0 : !hw.inout<i32>
  llhd.drv %we_i_8, %we_i after %0 : !hw.inout<i1>
  hw.output %29 : !hw.array<2xi32>
}
```
Output:
```
$ circt-opt --llhd-lower-processes --debug-only=llhd-lower-processes
Skipping process loc(...): control from entry and wait does not converge
```

### PR DESCRIPTION
**Pull request by fabianschuiki**
Currently, the LowerProcesses pass does not allow for the control flow from the entry block and the wait op to contain any non-branch ops up to the point where they converge. This is very conservative, since ops like constants can make their way into the entry block in a way where the entry block and wait op do converge, but with distinct yet equivalent ops in the respective blocks leading up to the convergence point.

Fix this issue by allowing blocks up to the convergence point to contain any ops, as long as the block arguments passed to the convergence block are coming from equivalent (but possibly distinct) ops.

We should really have a flavor of `llhd.process` that does not require a wait and a control flow loop to describe combinational processes. That would make these passes a lot easier.

Fixes #8799.

### CODE REVIEW

File: lib/Dialect/LLHD/Transforms/LowerProcesses.cpp [hunk 1]
```diff
@@ -103,8 +103,6 @@ bool Lowering::matchControlFlow() {
   auto skipToMergePoint = [&](Block *block) -> std::pair<Block *, ValueRange> {
     ValueRange operands;
     while (auto branchOp = dyn_cast<cf::BranchOp>(block->getTerminator())) {
-      if (!block->without_terminator().empty())
-        break;
```
Comment (maerhart) [inline lib/Dialect/LLHD/Transforms/LowerProcesses.cpp]: That would allow arbitrary ops in the entry block, right? What if there's some DPI call in there? We would have to put that into a separate initial op and funnel the (potential) result through to the lowered combinational op to make sure it is only called once at simulation start unless the sequence of blocks in the infinite loop has the same call that is skipped in the initial startup?
So, I think it would be fine to relax this constraint to checking that ALL ops in the blocks before the converged block are equivalent, rather than just the ones feeding the block arguments.

Comment (fabianschuiki) [reply lib/Dialect/LLHD/Transforms/LowerProcesses.cpp]: Hmmm yeah good point. Let me maybe limit this to side-effect free ops for now, since the op-by-op comparison is a bit annoying in the general case when there are a different number of blocks between the entry and the convergence point, and the wait op an d the convergence point.

**Comment by fabianschuiki** [comment]
@maerhart I think some more CSE/canonicalization before this pass would definitely help. My reasoning was that it would be good to also make the pass a bit more robust, such that we don't _really_ need canonicalization. I hope we'll be able to get rid of some of this block skipping stuff again in the future, if we introduce a flavor lf `llhd.process` that executes the body in a loop, with the wait absorbed into the surrounding op.

I've tweaked the pass to only skip side-effect-free ops and have added a test.

**Review by maerhart — APPROVED** [review]
Completely agree with making the pass more robust and not too reliant on CSE. My thought was that it might be an easy way to support this case without implementing the annoying equivalence checking of all ops in the converging blocks. But your approach with restricting it to side-effect-free ops sounds great! The case when they are passed via block arguments is already covered, and if they are used directly (because the entry block dominates all other blocks), it is equivalent with the alternative IR where those ops are just outside the process.
