### PR TITLE
[circt-reduce] Fix firrtl-remove-unused-ports crash with probes

### LINKED ISSUE #9564: [FIRRTL][circt-reduce] firrtl-remove-unused-ports can't handle probes
Consider the following:

``` mlir
firrtl.circuit "Foo" {
  firrtl.module private @Bar(
    out %ref: !firrtl.probe<clock>
  ) {
  }
  firrtl.module @Foo() {
    %Bar_ref = firrtl.instance Bar @Bar(
      out ref: !firrtl.probe<clock>
    )
  }
}
```

This will crash if run with:

``` console
# circt-reduce -skip-initial -test='exit 0' firrtl-remove-unused-ports.1.mlir -include firrtl-remove-unused-ports -o /dev/null
Reading input
Testing input with `exit 0`
Initial module has size 221
Trying reduction `firrtl-remove-unused-ports`
Assertion failed: (isa<To>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file Casting.h, line 560.
PLEASE submit a bug report to https://github.com/llvm/circt and include the crash backtrace.
Stack dump:
0.	Program arguments: circt-reduce -skip-initial "-test=exit 0" firrtl-remove-unused-ports.1.mlir -include firrtl-remove-unused-ports -o /dev/null
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  circt-reduce             0x0000000102367c34 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  circt-reduce             0x0000000102365b1c llvm::sys::RunSignalHandlers() + 172
2  circt-reduce             0x00000001023686dc SignalHandler(int, __siginfo*, void*) + 300
3  libsystem_platform.dylib 0x000000018fd516a4 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000018fd17848 pthread_kill + 296
5  libsystem_c.dylib        0x000000018fc209e4 abort + 124
6  libsystem_c.dylib        0x000000018fc1fc18 err + 0
7  circt-reduce             0x00000001034bbc2c llvm::StdThreadPool::wait() (.cold.1) + 0
8  circt-reduce             0x000000010269e0d8 circt::firrtl::patterns::AddOfPad::~AddOfPad() + 0
9  circt-reduce             0x000000010282e020 (anonymous namespace)::RemoveUnusedPortsPass::runOnOperation() + 3056
10 circt-reduce             0x0000000103475108 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) + 1340
11 circt-reduce             0x0000000103475a04 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) + 620
12 circt-reduce             0x0000000103477b68 mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool) + 5408
13 circt-reduce             0x00000001034754f0 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) + 2340
14 circt-reduce             0x0000000103475a04 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) + 620
15 circt-reduce             0x000000010347b3ec mlir::PassManager::runPasses(mlir::Operation*, mlir::AnalysisManager) + 464
16 circt-reduce             0x000000010347abf0 mlir::PassManager::run(mlir::Operation*) + 5292
17 circt-reduce             0x00000001022f30dc execute(mlir::MLIRContext&) + 3988
18 circt-reduce             0x00000001022f1ebc main + 300
19 dyld                     0x000000018f976b98 start + 6076
zsh: abort      circt-reduce -skip-initial -test='exit 0' firrtl-remove-unused-ports.1.mlir 
```

### PR DESCRIPTION
**Pull request by seldridge**
The firrtl-remove-unused-ports pass was crashing with a cast assertion
failure when trying to create InvalidValueOp for probe types like
!firrtl.probe<clock>. The issue was that InvalidValueOp only accepts
FIRRTLBaseType, but probe types are RefType (which inherits from
FIRRTLType but not FIRRTLBaseType).

This commit adds a check to only create InvalidValueOp for FIRRTLBaseType
results. For non-base types like probe types, we skip creating the
invalid value since ref types cannot be invalidated.

Fixes #9564.

AI-assisted-by: Augment (Claude Sonnet 4)

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/RemoveUnusedPorts.cpp [hunk 1]
```diff
@@ -193,8 +193,18 @@ void RemoveUnusedPortsPass::removeUnusedModulePorts(
...
+        // not base types and cannot be invalidated.
+        if (auto baseType =
+                dyn_cast<firrtl::FIRRTLBaseType>(result.getType())) {
+          value = InvalidValueOp::create(builder, baseType);
+        } else {
+          // For non-base types like ref types, we cannot create an invalid
+          // value. Skip replacing uses for these types.
+          continue;
+        }
+      }
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/Transforms/RemoveUnusedPorts.cpp:209]: I'll rework this after https://github.com/llvm/circt/pull/9580 goes in. This would be better to use appropriate "invalid" tie-off values and https://github.com/llvm/circt/pull/9580 adds some infrastructure to help here.

**Review by fabianschuiki — APPROVED** [review]
Nice! LGTM!
