### PR TITLE
[FIRRTL][CheckCombLoops] Improve loop reporting diagnostics.

### LINKED ISSUE #4781: [FIRRTL] comb cycle error has too many entries (?)
Consider this input:
```firrtl
circuit wut :
   module wut :

     wire x : UInt<8>
     wire y : UInt<8>
     x <= y
     y <= x
```

We currently produce this error:

```
wut.fir:2:11: error: detected combinational cycle in a FIRRTL module, sample path: wut.x <- wut.y <- wut.x <- wut.x
   module wut :
          ^
```

From brief testing, seems we print the beginning/end an extra time?  As shown here, that last `<- wut.x` is not actually present and describes a connection that doesn't exist (not directly anyway).

As a nit, it would be nice to point to one of the signals involved instead of the module?  If we are intentionally avoiding printing all the signals to avoid being too verbose that makes sense, but may be useful to enable as a debugging aid.

### PR DESCRIPTION
**Pull request by dtzSiFive**
* Fixup cases with trailing or leading arrows.
* Fix printing starting value twice, misrepresenting cycle (#4781).
* Walk cycle until a name is found and start from there, improving diagnostic and ensuring the begin/end are named.
  * If nothing can be named, say so explicitly instead empty path and emit note pointing to add location for starting val.
* Avoid printing module name for every named signal
  * mymodule.a <- mymodule.b.c <- mymodule.d is now: mymodule.{a <- b.c <- d} They always start with same module name, compress a bit.
* Use '...' to describe paths not named, only once until next name.

A future improvement would be to improve printing names for values that alias a number of sources-- presently we (non-deterministically) pick the first of the computed alias set, this could be made clearer to the user (indicating it's representative of the set, not necessarily "directly" involved), and perhaps picking "best" representative if some we can't name.

Fixes #4781 .

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp [hunk 1]
```diff
@@ -398,27 +398,52 @@ class DiscoverLoops {
...
   void reportLoopFound(Value childVal, VisitingSet visiting) {
-    auto getName = [&](FieldRef node) {
-      if (isa<SubfieldOp, SubindexOp, SubaccessOp>(node.getDefiningOp())) {
-        assert(!valRefersTo[node.getValue()].empty());
-        return getFieldName(*valRefersTo[node.getValue()].begin()).first;
+    auto getName = [&](Value v) {
+      if (isa_and_nonnull<SubfieldOp, SubindexOp, SubaccessOp>(
+              v.getDefiningOp())) {
+        assert(!valRefersTo[v].empty());
+        // TODO: Indicate to user if "alias set" if > 1, and/or pick
```
Comment (prithayan) [inline lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp:405]: We don't have enough information here, but this can be deterministic if we do another traversal to find the actual value that's connected, and just print that. We want the loop detection to be fast, but the error reporting can be slower. So, given the source and sink of the cycle, find the actual path between them and report the loop.

Comment (prithayan) [reply lib/Dialect/FIRRTL/Transforms/CheckCombLoops.cpp:405]: Plus, we need to handle `SubAccessOp` in `getFieldName` .

**Review by prithayan — APPROVED** [review]
Thanks a lot for fixing this. There's bit more scope to improve error reporting here, as this doesn't yet print cycles across modules via instance op.
