### PR TITLE
[circt-reduce] Try reductions on promising ops first

### LINKED ISSUE #3479: [reduce] Try reductions on promising ops first
It would be great if `circt-reduce` would try to apply reductions on the "juiciest" operations first, to hopefully get the input size down quickly.

Currently the reducer walks the IR, considering only ops to which the current reduction applies, numbers them, and applies the reduction to those ops whose number are inside the current "reduction chunk". The chunks get progressively smaller, in a binary search like pattern, to try and get rid of large consecutive chunks of ops quickly.

However, the ops are just considered in the order in which they appeared in the IR. It would be great if `Reduction::match` could not only indicate if it applies to an op, but also return a measure of the expected benefit of successfully applying the reduction. That could be just an unsigned number, where 0 indicates "doesn't apply", and >0 indicates the expected benefit. The *instance-stubber* or *module-externalizer* reduction could return the (recursive) number of ops in the instantiated module as a benefit, since turning a large `firrtl.module` into a `firrtl.extmodule` is going to have a huge impact on the input.

Instead of directly walking the IR and numbering ops here
https://github.com/llvm/circt/blob/eb624a76fada2058daa11c4496d5323531d1adea/tools/circt-reduce/circt-reduce.cpp#L181-L198
the reducer could instead collect them along with the reported benefit into a vector, sort the vector by decreasing benefit, and then apply the reduction to the current range of vector indices selected by `rangeBase, rangeLength`.

As a result, I would expect the reducer to try to get rid of the heaviest modules first, which should lead to a much more significant reduction early on. Also, since the benefit is likely so somewhat correlate with how "entangled" an op is in the design (e.g. small leaf modules have a small benefit, large aggregate top-level modules a large benefit), the reducer should be much more effective at pruning off the tail end of the low-benefit reductions. For example, in the second and third reduction iteration the ops have been split into two groups which are processed one after the other. In this case the reduction is likely to fail on the first half (which contains all the high-benefit reductions, likely containing the bug to be reduced), but then is likely to succeed in the second half (which contains all the low-benefit reductions).

### Todo
- [ ] Make `Reduction::match(Operation *)` return a benefit measure instead of a boolean
- [ ] Make the `ModuleExternalizer` and `InstanceStubber` reductions return a benefit from `match` computed as the number of instructions in the module (ideally transitively, counting submodules as well)
- [ ] Make [pattern application](https://github.com/llvm/circt/blob/eb624a76fada2058daa11c4496d5323531d1adea/tools/circt-reduce/circt-reduce.cpp#L181-L198) aggregate ops and their benefit returned from `match(...)` into a vector, e.g. as int-op pair
- [ ] Sort the vector by benefit, high benefit first
- [ ] Apply reduction on the `rangeBase .. rangeBase+rangeLength` subrange of the vector

### PR DESCRIPTION
**Pull request by maerhart**
Depends on #3555

Resolves #3479

### CODE REVIEW

File: tools/circt-reduce/Reduction.cpp [hunk 1]
```diff
@@ -181,10 +268,26 @@ std::string PassReduction::getName() const { return passName.str(); }
...
+      if (failed(collectInstantiatedModules(fmoduleOp, symbols, modules,
+                                            instances)))
+        return 0;
+      return computeTransitiveModuleSize(modules, instances,
+                                         /*countMultipleInstantiations=*/false,
+                                         /*countElsewhereInstantiated=*/true);
+    }
+    return 0;
+  }
+
```
Comment (fabianschuiki) [inline tools/circt-reduce/Reduction.cpp:290]: Very cool :sunglasses:

File: tools/circt-reduce/Reduction.h [hunk 2]
```diff
@@ -48,8 +48,11 @@ struct Reduction {
   /// reductions before the resulting module is tried for interestingness.
   virtual void afterReduction(mlir::ModuleOp) {}
 
-  /// Check if the reduction can apply to a specific operation.
-  virtual bool match(mlir::Operation *op) = 0;
+  /// Check if the reduction can apply to a specific operation. Returns a
+  /// benefit measure where a higher number means that applying the pattern
+  /// leads to a bigger reduction and zero means that the patten does not
+  /// match and thus cannot be applied at all.
+  virtual uint64_t match(mlir::Operation *op) = 0;
```
Comment (fabianschuiki) [inline tools/circt-reduce/Reduction.h:55]: Thanks for also updating the comments :+1:

File: tools/circt-reduce/circt-reduce.cpp [hunk 3]
```diff
@@ -226,14 +226,22 @@ static LogicalResult execute(MLIRContext &context) {
...
+        }
       });
+      std::sort(opBenefits.begin(), opBenefits.end(),
+                [](auto a, auto b) { return a.second > b.second; });
+      for (size_t i = rangeBase;
+           i < rangeBase + rangeLength && i < opBenefits.size(); i++) {
+        auto *op = opBenefits[i].first;
+        if (pattern.match(op))
+          (void)pattern.rewrite(op);
+      }
```
Comment (fabianschuiki) [inline tools/circt-reduce/circt-reduce.cpp:244]: Cool! Very nice :+1:

**Review by fabianschuiki — APPROVED** [review]
LGTM! Thanks for working on this :+1:
