### PR TITLE
[FIRRTL] Fix use-after-free in InferReset

### LINKED ISSUE #7225: [FIRRTL] InferResets: deleting op used to drive reset network results in use-after-free
```mlir
firrtl.circuit "MovableNodeShouldDominate" {
  firrtl.module @MovableNodeShouldDominate(in %clock: !firrtl.clock) {
    %child_clock = firrtl.instance child @Child(in clock: !firrtl.clock)
    firrtl.connect %child_clock, %clock : !firrtl.clock
    %ui1 = firrtl.constant 1 : !firrtl.uint<1>
    %0 = firrtl.asAsyncReset %ui1 : (!firrtl.uint<1>) -> !firrtl.asyncreset
    %localReset = firrtl.node %0 {annotations = [{class = "sifive.enterprise.firrtl.FullAsyncResetAnnotation"}]} : !firrtl.asyncreset
  }
  firrtl.module @Child(in %clock: !firrtl.clock) {
    %reg = firrtl.reg %clock : !firrtl.clock, !firrtl.uint<8>
  }
}
```
```
./bin/circt-opt --pass-pipeline='builtin.module(firrtl.circuit(firrtl-infer-resets))' reset.mlir
```

InferResets needs to wire the result of the NodeOp to the instance of Child, and to do so [replaces it with a wire](https://github.com/llvm/circt/blob/main/lib/Dialect/FIRRTL/Transforms/InferResets.cpp#L1724).  This results in a dangling reference to the deleted node stored in the ResetDomain.

Running it under valgrind yields many errors, such as the one below, but my line numbers won't line up with `main` due to a lot of printf debugging:
```
==176563== Invalid read of size 8
==176563==    at 0x1C35A53: mlir::Value::getLoc() const (llvm/mlir/lib/IR/Value.cpp:0)
==176563==    by 0x12A6F98: implementAsyncReset (lib/Dialect/FIRRTL/Transforms/InferResets.cpp:1688)
==176563==    by 0x12A6F98: implementAsyncReset (lib/Dialect/FIRRTL/Transforms/InferResets.cpp:1647)
==176563==    by 0x12A6F98: (anonymous namespace)::InferResetsPass::runOnOperationInner() (lib/Dialect/FIRRTL/Transforms/InferResets.cpp:545)
==176563==    by 0x12A4465: (anonymous namespace)::InferResetsPass::runOnOperation() (lib/Dialect/FIRRTL/Transforms/InferResets.cpp:513)

==176563==  Address 0x613f688 is 40 bytes inside a block of size 128 free'd
==176563==    at 0x4C39A93: free (vg_replace_malloc.c:872)
==176563==    by 0x18E466D: llvm::iplist_impl<llvm::simple_ilist<mlir::Operation>, llvm::ilist_traits<mlir::Operation> >::erase(llvm::ilist_iterator<llvm::ilist_detail::node_options<mlir::Operation, true, false, void, false>, false, false>) (ilist.h:205)
==176563==    by 0x12A7755: erase (OpDefinition.h:131)
==176563==    by 0x12A7755: implementAsyncReset (lib/Dialect/FIRRTL/Transforms/InferResets.cpp:1742)
==176563==    by 0x12A7755: implementAsyncReset (lib/Dialect/FIRRTL/Transforms/InferResets.cpp:1647)
==176563==    by 0x12A7755: (anonymous namespace)::InferResetsPass::runOnOperationInner() (lib/Dialect/FIRRTL/Transforms/InferResets.cpp:545)
==176563==    by 0x12A4465: (anonymous namespace)::InferResetsPass::runOnOperation() (lib/Dialect/FIRRTL/Transforms/InferResets.cpp:513)
```

### PR DESCRIPTION
**Pull request by darthscsi**
As @youngar explains well, a node was being deleted when it had references.  Just route the node through the bounce wire instead of trying to replace it.

Closes #7225

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/InferResets.cpp [hunk 1]
```diff
@@ -1714,14 +1714,17 @@ LogicalResult InferResetsPass::implementAsyncReset(FModuleOp module,
...
+                                                          nodeOp->getBlock());
         auto wireOp = builder.create<WireOp>(
             nodeOp.getResult().getType(), nodeOp.getNameAttr(),
             nodeOp.getNameKindAttr(), nodeOp.getAnnotationsAttr(),
             nodeOp.getInnerSymAttr(), nodeOp.getForceableAttr());
-        emitConnect(builder, wireOp.getResult(), nodeOp.getInput());
+        // Don't delete the node, since it might be in use in worklists.
         nodeOp->replaceAllUsesWith(wireOp);
-        nodeOp.erase();
+        nodeOp->removeAttr(nodeOp.getInnerSymAttrName());
```
Comment (youngar) [inline lib/Dialect/FIRRTL/Transforms/InferResets.cpp:1725]: Should probably remove the annotations as well, e.g. if the node has an OMIR path tracker we will end up having two things with the same path tracker.

Not as important but might want to make the Node non-forcible.

Comment (darthscsi) [reply lib/Dialect/FIRRTL/Transforms/InferResets.cpp:1725]: yea working on it.

**Comment by dtzSiFive** [comment]
Thanks for getting us past this.

Sounds like some bits are still coming, but please add a test (such as in the linked issue).

File: lib/Dialect/FIRRTL/Transforms/InferResets.cpp (hunk 1 above)
Comment (darthscsi) [reply lib/Dialect/FIRRTL/Transforms/InferResets.cpp:1725]: Changing the node to be non-forcable is kind of a pain as it would requiring changing the number of results, which I don't think you can do.  The forcable result should be unused, so it should be cleared away with the rest of the node by CSE/Canonicalization.

Comment (dtzSiFive) [reply lib/Dialect/FIRRTL/Transforms/InferResets.cpp:1725]: Yes you can't change results, the way it's done is a bit rough but basically creates a new one and replaces it.

And even if you did that (there's a helper, but in the `detail` namespace) it'd be erasing the existing node so no-go.

Thanks!!

**Review by dtzSiFive — APPROVED** [review]
LGTM, we can fix the rest of InferResets later.

**Comment by dtzSiFive** [comment]
Okay to land? :grin:
