### PR TITLE
[FIRRTL] Cache symbol table in LowerLayers

### LINKED ISSUE #7434: [FIRRTL] crash in LowerLayers
Got a random crash in LowerLayers in an unrelated PR [here](https://github.com/llvm/circt/actions/runs/10239144740/job/28324393501#step:10:2194).  Did not see anything wrong when running under valgrind. It is crashing on one of the calls to `lookupSymbolIn` which walks the circuit looking for a specific symbol.  I see some code that looks like we are creating modules in the circuit in parallel, but guarding it with a lock.  If we are searching the circuit for a layerblock while we are creating more modules, that could be an issue.  If that is the problem, then prepopulating a SymbolTable could help make the code run faster as well as solving the race condition.

```
******************** TEST 'CIRCT :: Dialect/FIRRTL/lower-layers.mlir' FAILED ********************
Exit Code: 2

Command Output (stderr):
--
RUN: at line 1: circt-opt --verify-roundtrip -firrtl-lower-layers -split-input-file /__w/circt/circt/test/Dialect/FIRRTL/lower-layers.mlir | /__w/circt/circt/llvm/install/bin/FileCheck /__w/circt/circt/test/Dialect/FIRRTL/lower-layers.mlir
+ circt-opt --verify-roundtrip -firrtl-lower-layers -split-input-file /__w/circt/circt/test/Dialect/FIRRTL/lower-layers.mlir
+ /__w/circt/circt/llvm/install/bin/FileCheck /__w/circt/circt/test/Dialect/FIRRTL/lower-layers.mlir
PLEASE submit a bug report to https://github.com/llvm/circt and include the crash backtrace.
 #0 0x00007f3886038d7d llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /__w/circt/circt/llvm/llvm/lib/Support/Unix/Signals.inc:723:11
 #1 0x00007f388603926b PrintStackTraceSignalHandler(void*) /__w/circt/circt/llvm/llvm/lib/Support/Unix/Signals.inc:798:1
 #2 0x00007f3886037296 llvm::sys::RunSignalHandlers() /__w/circt/circt/llvm/llvm/lib/Support/Signals.cpp:105:5
 #3 0x00007f3886039a85 SignalHandler(int) /__w/circt/circt/llvm/llvm/lib/Support/Unix/Signals.inc:413:1
 #4 0x00007f3895f01420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #5 0x00007f38866285f0 bool llvm::isa<mlir::StringAttr, mlir::Attribute>(mlir::Attribute const&) /__w/circt/circt/llvm/llvm/include/llvm/Support/Casting.h:549:47
 #6 0x00007f38866284d5 decltype(auto) llvm::cast<mlir::StringAttr, mlir::Attribute>(mlir::Attribute const&) /__w/circt/circt/llvm/llvm/include/llvm/Support/Casting.h:566:3
 #7 0x00007f3886628175 mlir::NamedAttribute::getName() const /__w/circt/circt/llvm/mlir/lib/IR/Attributes.cpp:50:10
 #8 0x00007f3895df0c15 std::pair<mlir::NamedAttribute const*, bool> mlir::impl::findAttrSorted<mlir::NamedAttribute const*>(mlir::NamedAttribute const*, mlir::NamedAttribute const*, llvm::StringRef) /__w/circt/circt/llvm/install/include/mlir/IR/OperationSupport.h:751:24
 #9 0x00007f3895df0ae8 std::pair<mlir::NamedAttribute const*, bool> mlir::impl::findAttrSorted<mlir::NamedAttribute const*>(mlir::NamedAttribute const*, mlir::NamedAttribute const*, mlir::StringAttr) /__w/circt/circt/llvm/install/include/mlir/IR/OperationSupport.h:772:12
#10 0x00007f388665e0a2 mlir::DictionaryAttr::get(mlir::StringAttr) const /__w/circt/circt/llvm/mlir/lib/IR/BuiltinAttributes.cpp:174:13
#11 0x00007f388687f698 mlir::Operation::getAttr(mlir::StringAttr) /__w/circt/circt/llvm/mlir/include/mlir/IR/Operation.h:534:18
#12 0x00007f388687f5e5 mlir::StringAttr mlir::Operation::getAttrOfType<mlir::StringAttr>(mlir::StringAttr) /__w/circt/circt/llvm/mlir/include/mlir/IR/Operation.h:546:46
#13 0x00007f3886872165 getNameIfSymbol(mlir::Operation*, mlir::StringAttr) /__w/circt/circt/llvm/mlir/lib/IR/SymbolTable.cpp:32:14
#14 0x00007f3886873aa6 mlir::SymbolTable::lookupSymbolIn(mlir::Operation*, mlir::StringAttr) /__w/circt/circt/llvm/mlir/lib/IR/SymbolTable.cpp:396:9
#15 0x00007f3886877749 mlir::SymbolTable::lookupSymbolIn(mlir::Operation*, mlir::SymbolRefAttr, llvm::SmallVectorImpl<mlir::Operation*>&)::$_2::operator()(mlir::Operation*, mlir::StringAttr) const /__w/circt/circt/llvm/mlir/lib/IR/SymbolTable.cpp:447:5
#16 0x00007f388687770d mlir::Operation* llvm::function_ref<mlir::Operation* (mlir::Operation*, mlir::StringAttr)>::callback_fn<mlir::SymbolTable::lookupSymbolIn(mlir::Operation*, mlir::SymbolRefAttr, llvm::SmallVectorImpl<mlir::Operation*>&)::$_2>(long, mlir::Operation*, mlir::StringAttr) /__w/circt/circt/llvm/llvm/include/llvm/ADT/STLFunctionalExtras.h:45:5
#17 0x00007f388687fe0c llvm::function_ref<mlir::Operation* (mlir::Operation*, mlir::StringAttr)>::operator()(mlir::Operation*, mlir::StringAttr) const /__w/circt/circt/llvm/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:5
#18 0x00007f3886873c95 lookupSymbolInImpl(mlir::Operation*, mlir::SymbolRefAttr, llvm::SmallVectorImpl<mlir::Operation*>&, llvm::function_ref<mlir::Operation* (mlir::Operation*, mlir::StringAttr)>) /__w/circt/circt/llvm/mlir/lib/IR/SymbolTable.cpp:417:17
#19 0x00007f3886873bf9 mlir::SymbolTable::lookupSymbolIn(mlir::Operation*, mlir::SymbolRefAttr, llvm::SmallVectorImpl<mlir::Operation*>&) /__w/circt/circt/llvm/mlir/lib/IR/SymbolTable.cpp:449:10
#20 0x00007f3886873b42 mlir::SymbolTable::lookupSymbolIn(mlir::Operation*, mlir::SymbolRefAttr) /__w/circt/circt/llvm/mlir/lib/IR/SymbolTable.cpp:403:14
#21 0x00007f3894b64d95 LowerLayersPass::runOnModuleBody(circt::firrtl::FModuleOp, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>&)::$_4::operator()(mlir::Operation*) const /__w/circt/circt/lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp:356:9
#22 0x00007f3894b64aed mlir::WalkResult llvm::function_ref<mlir::WalkResult (mlir::Operation*)>::callback_fn<LowerLayersPass::runOnModuleBody(circt::firrtl::FModuleOp, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>&)::$_4>(long, mlir::Operation*) /__w/circt/circt/llvm/install/include/llvm/ADT/STLFunctionalExtras.h:45:12
#23 0x00007f3895ecf11c llvm::function_ref<mlir::WalkResult (mlir::Operation*)>::operator()(mlir::Operation*) const /__w/circt/circt/llvm/install/include/llvm/ADT/STLFunctionalExtras.h:68:12
#24 0x00007f3895ecf0bd mlir::WalkResult mlir::detail::walk<mlir::ForwardIterator>(mlir::Operation*, llvm::function_ref<mlir::WalkResult (mlir::Operation*)>, mlir::WalkOrder) /__w/circt/circt/llvm/install/include/mlir/IR/Visitors.h:280:12
#25 0x00007f3895ecf03b mlir::WalkResult mlir::detail::walk<mlir::ForwardIterator>(mlir::Operation*, llvm::function_ref<mlir::WalkResult (mlir::Operation*)>, mlir::WalkOrder) /__w/circt/circt/llvm/install/include/mlir/IR/Visitors.h:273:13
#26 0x00007f3895ecf03b mlir::WalkResult mlir::detail::walk<mlir::ForwardIterator>(mlir::Operation*, llvm::function_ref<mlir::WalkResult (mlir::Operation*)>, mlir::WalkOrder) /__w/circt/circt/llvm/install/include/mlir/IR/Visitors.h:273:13
#27 0x00007f3895ecf03b mlir::WalkResult mlir::detail::walk<mlir::ForwardIterator>(mlir::Operation*, llvm::function_ref<mlir::WalkResult (mlir::Operation*)>, mlir::WalkOrder) /__w/circt/circt/llvm/install/include/mlir/IR/Visitors.h:273:13
#28 0x00007f3894b64a82 std::enable_if<llvm::is_one_of<mlir::Operation*, mlir::Operation*, mlir::Region*, mlir::Block*>::value, mlir::WalkResult>::type mlir::detail::walk<(mlir::WalkOrder)1, mlir::ForwardIterator, LowerLayersPass::runOnModuleBody(circt::firrtl::FModuleOp, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>&)::$_4, mlir::Operation*, mlir::WalkResult>(mlir::Operation*, LowerLayersPass::runOnModuleBody(circt::firrtl::FModuleOp, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>&)::$_4&&) /__w/circt/circt/llvm/install/include/mlir/IR/Visitors.h:312:10
#29 0x00007f3894b64a1d std::enable_if<llvm::function_traits<std::decay<LowerLayersPass::runOnModuleBody(circt::firrtl::FModuleOp, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>&)::$_4>::type>::num_args == 1, mlir::WalkResult>::type mlir::Operation::walk<(mlir::WalkOrder)1, mlir::ForwardIterator, LowerLayersPass::runOnModuleBody(circt::firrtl::FModuleOp, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>&)::$_4, mlir::WalkResult>(LowerLayersPass::runOnModuleBody(circt::firrtl::FModuleOp, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>&)::$_4&&) /__w/circt/circt/llvm/install/include/mlir/IR/Operation.h:794:12
#30 0x00007f3894b63550 std::enable_if<llvm::function_traits<std::decay<LowerLayersPass::runOnModuleBody(circt::firrtl::FModuleOp, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>&)::$_4>::type>::num_args == 1, mlir::WalkResult>::type mlir::OpState::walk<(mlir::WalkOrder)1, mlir::ForwardIterator, LowerLayersPass::runOnModuleBody(circt::firrtl::FModuleOp, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>&)::$_4, mlir::WalkResult>(LowerLayersPass::runOnModuleBody(circt::firrtl::FModuleOp, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>&)::$_4&&) /__w/circt/circt/llvm/install/include/mlir/IR/OpDefinition.h:166:19
#31 0x00007f3894b634f4 LowerLayersPass::runOnModuleBody(circt::firrtl::FModuleOp, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>&) /__w/circt/circt/lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp:330:12
#32 0x00007f3894b6453c _ZZN15LowerLayersPass15runOnModuleLikeEN5circt6firrtl11FModuleLikeEENK3$_0clINS1_9FModuleOpEEEDaT_ /__w/circt/circt/lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp:288:7
#33 0x00007f3894b63327 llvm::TypeSwitch<mlir::Operation*, void>& llvm::TypeSwitch<mlir::Operation*, void>::Case<circt::firrtl::FModuleOp, LowerLayersPass::runOnModuleLike(circt::firrtl::FModuleLike)::$_0>(LowerLayersPass::runOnModuleLike(circt::firrtl::FModuleLike)::$_0&&) /__w/circt/circt/llvm/install/include/llvm/ADT/TypeSwitch.h:149:7
#34 0x00007f3894b631ec LowerLayersPass::runOnModuleLike(circt::firrtl::FModuleLike) /__w/circt/circt/lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp:284:8
#35 0x00007f3894b67e56 LowerLayersPass::runOnOperation()::$_7::operator()(circt::firrtl::FModuleLike) const /__w/circt/circt/lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp:732:56
#36 0x00007f3894b686a4 llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>> llvm::parallel::detail::parallel_transform_reduce<circt::firrtl::FModuleLike*, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>, LowerLayersPass::runOnOperation()::$_6, LowerLayersPass::runOnOperation()::$_7>(circt::firrtl::FModuleLike*, circt::firrtl::FModuleLike*, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>, LowerLayersPass::runOnOperation()::$_6, LowerLayersPass::runOnOperation()::$_7)::'lambda'()::operator()() const /__w/circt/circt/llvm/install/include/llvm/Support/Parallel.h:193:25
#37 0x00007f3894b685fd circt::firrtl::FModuleLike* std::__invoke_impl<void, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>> llvm::parallel::detail::parallel_transform_reduce<circt::firrtl::FModuleLike*, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>, LowerLayersPass::runOnOperation()::$_6, LowerLayersPass::runOnOperation()::$_7>(circt::firrtl::FModuleLike*, circt::firrtl::FModuleLike*, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>, LowerLayersPass::runOnOperation()::$_6, LowerLayersPass::runOnOperation()::$_7)::'lambda'()&>(std::__invoke_other, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61:7
#38 0x00007f3894b685ad std::enable_if<is_invocable_r_v<circt::firrtl::FModuleLike*, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>>, circt::firrtl::FModuleLike*>::type std::__invoke_r<void, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>> llvm::parallel::detail::parallel_transform_reduce<circt::firrtl::FModuleLike*, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>, LowerLayersPass::runOnOperation()::$_6, LowerLayersPass::runOnOperation()::$_7>(circt::firrtl::FModuleLike*, circt::firrtl::FModuleLike*, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>, LowerLayersPass::runOnOperation()::$_6, LowerLayersPass::runOnOperation()::$_7)::'lambda'()&>(llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:117:5
#39 0x00007f3894b6842d std::_Function_handler<void (), llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>> llvm::parallel::detail::parallel_transform_reduce<circt::firrtl::FModuleLike*, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>, LowerLayersPass::runOnOperation()::$_6, LowerLayersPass::runOnOperation()::$_7>(circt::firrtl::FModuleLike*, circt::firrtl::FModuleLike*, llvm::DenseMap<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>, llvm::DenseMapInfo<circt::hw::InnerRefAttr, void>, llvm::detail::DenseMapPair<circt::hw::InnerRefAttr, std::pair<circt::hw::InnerSymAttr, mlir::StringAttr>>>, LowerLayersPass::runOnOperation()::$_6, LowerLayersPass::runOnOperation()::$_7)::'lambda'()>::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:290:2
#40 0x00007f3885e87005 std::function<void ()>::operator()() const /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:590:2
#41 0x00007f3885f4af7d llvm::parallel::TaskGroup::spawn(std::function<void ()>, bool)::$_0::operator()() const /__w/circt/circt/llvm/llvm/lib/Support/Parallel.cpp:214:11
#42 0x00007f3885f4af3d void std::__invoke_impl<void, llvm::parallel::TaskGroup::spawn(std::function<void ()>, bool)::$_0&>(std::__invoke_other, llvm::parallel::TaskGroup::spawn(std::function<void ()>, bool)::$_0&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61:7
#43 0x00007f3885f4aeed std::enable_if<is_invocable_r_v<void, llvm::parallel::TaskGroup::spawn(std::function<void ()>, bool)::$_0&>, void>::type std::__invoke_r<void, llvm::parallel::TaskGroup::spawn(std::function<void ()>, bool)::$_0&>(llvm::parallel::TaskGroup::spawn(std::function<void ()>, bool)::$_0&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:117:5
#44 0x00007f3885f4ad9d std::_Function_handler<void (), llvm::parallel::TaskGroup::spawn(std::function<void ()>, bool)::$_0>::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:290:2
#45 0x00007f3885e87005 std::function<void ()>::operator()() const /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:590:2
#46 0x00007f3885f4a083 llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::work(llvm::ThreadPoolStrategy, unsigned int) /__w/circt/circt/llvm/llvm/lib/Support/Parallel.cpp:142:11
#47 0x00007f3885f4a6a7 llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()::operator()() const /__w/circt/circt/llvm/llvm/lib/Support/Parallel.cpp:64:48
#48 0x00007f3885f4a66d void std::__invoke_impl<void, llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()>(std::__invoke_other, llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61:7
#49 0x00007f3885f4a5fd std::__invoke_result<llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()>::type std::__invoke<llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()>(llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:96:7
#50 0x00007f3885f4a5d5 void std::thread::_Invoker<std::tuple<llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()>>::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_thread.h:259:6
#51 0x00007f3885f4a5a5 std::thread::_Invoker<std::tuple<llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()>>::operator()() /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_thread.h:266:4
#52 0x00007f3885f4a4b9 std::thread::_State_impl<std::thread::_Invoker<std::tuple<llvm::parallel::detail::(anonymous namespace)::ThreadPoolExecutor::ThreadPoolExecutor(llvm::ThreadPoolStrategy)::'lambda'()::operator()() const::'lambda'()>>>::_M_run() /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_thread.h:211:24
#53 0x00007f3885a78793 (/lib/x86_64-linux-gnu/libstdc++.so.6+0xe6793)
#54 0x00007f3895ef5609 start_thread /build/glibc-wuryBv/glibc-2.31/nptl/pthread_create.c:478:7
#55 0x00007f38858bf353 __clone /build/glibc-wuryBv/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97:0
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /__w/circt/circt/llvm/install/bin/FileCheck /__w/circt/circt/test/Dialect/FIRRTL/lower-layers.mlir
```

### PR DESCRIPTION
**Pull request by seldridge**
Precompute a symbol table inside LowerLayers in order to do SymbolRefAttr -> LayerOp lookups.  This is expected to fix an intermittent crash as well as improve performance.

Fixes #7434.

h/t @youngar for the fix suggestion.

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp [hunk 1]
```diff
@@ -197,6 +197,9 @@ class LowerLayersPass
 
   /// A map from inline layers to their macro names.
   DenseMap<LayerOp, FlatSymbolRefAttr> macroNames;
+
+  /// A symbol table associated with the FIRRTL circuit.
+  SymbolTable* symbolTable;
```
Comment (youngar) [inline lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp:202]:
```suggestion
  SymbolTable *symbolTable;
```

File: lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp [hunk 2]
```diff
@@ -138,7 +138,7 @@ class LowerLayersPass
     : public circt::firrtl::impl::LowerLayersBase<LowerLayersPass> {
   hw::OutputFileAttr getOutputFile(SymbolRefAttr layerName) {
     auto layer =
-        cast<LayerOp>(SymbolTable::lookupSymbolIn(getOperation(), layerName));
+        cast<LayerOp>(symbolTable->lookupSymbolIn(getOperation(), layerName));
```
Comment (youngar) [inline lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp:141]: I think you might have to call a different function, shouldn't have to take the symbol operation as an argument

File: lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp (hunk 1 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp]: 😓

File: lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp (hunk 2 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp:141]: So, this may not work so easily then. As this is a `SymbolRefAttr` and it needs to do a nested lookup across symbol tables. It may be better to instead do the actual `SymbolRefAttr` -> `LayerOp` caching during the serial portion, then.

WDYT?

Comment (youngar) [reply lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp:141]: Yeah, that sounds like a solid plan.  I don't see a good way to force the SymbolTableCollection to prepopulate the symbol tables.

Comment (seldridge) [reply lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp]: Fixed in the force push here: https://github.com/llvm/circt/pull/7436/commits/46326f7aef18f4ce7ebaf5de39f314c37e0a8379

File: lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp [hunk 3]
```diff
@@ -123,7 +123,8 @@ static SmallString<32> fileNameForLayer(StringRef circuitName,
 }
 
 /// For a layerblock `@A::@B::@C`, the verilog macro is `A_B_C`.
-static SmallString<32> macroNameForLayer(ArrayRef<StringAttr> layerName) {
+static SmallString<32>
+macroNameForLayer(ArrayRef<FlatSymbolRefAttr> layerName) {
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp:127]: This change, and others that are `s/StringAttr/FlatSymbolRefAttr/` exist because the former is always trivially accessible from the latter while the latter is necessary for constructing `SymbolRefAttr`s. This became necessary due to wanting to compute macros and the `SymbolRefAttr` -> `LayerOp` mapping at the same time.

**Review by rwy7 — APPROVED** [review]
