### PR TITLE
[WireDFT] harden a bit, check clock gate modules.

### LINKED ISSUE #4447: [FIRRTL] Verifier Crash from Invalid WireDFT Circuit
I was able to get the verifier to crash with a circuit that is unanticipated by the `WireDFT` pass. Consider:

```
circuit Top: %[[
  {
    "class":"sifive.enterprise.firrtl.MarkDUTAnnotation",
    "target":"~Top|Top"
  },
  {
    "class":"sifive.enterprise.firrtl.DFTTestModeEnableAnnotation",
    "target":"~Top|Top>test_en"
    },
  {
    "class":"firrtl.transforms.DontTouchAnnotation",
    "target":"~Top|Top>test_en"
  }
]]
  extmodule EICG_wrapper_Bar:

  module Foo:
    inst bar of EICG_wrapper_Bar

  module Top:
    wire test_en: UInt<1>
    test_en is invalid

    inst foo of Foo
```

This produces with `firtool Foo.fir`:

```
# firtool Tmp.fir
PLEASE submit a bug report to https://github.com/llvm/circt and include the crash backtrace.
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  firtool                  0x000000010fdc97fd llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 61
1  firtool                  0x000000010fdc9d7b PrintStackTraceSignalHandler(void*) + 27
2  firtool                  0x000000010fdc7b66 llvm::sys::RunSignalHandlers() + 134
3  firtool                  0x000000010fdcb9bf SignalHandler(int) + 223
4  libsystem_platform.dylib 0x00007ff81f38fdfd _sigtramp + 29
5  libsystem_platform.dylib 0x00007ff5df040000 _sigtramp + 18446744064042402336
6  firtool                  0x000000011057e328 mlir::Type::getDialect() const + 24
7  firtool                  0x0000000110b2df35 circt::firrtl::FIRRTLBaseType::classof(mlir::Type) + 21
8  firtool                  0x0000000110b2df0d llvm::CastInfo<circt::firrtl::FIRRTLBaseType, mlir::Type const, void>::isPossible(mlir::Type) + 29
9  firtool                  0x0000000110b2dee0 bool llvm::isa<circt::firrtl::FIRRTLBaseType, mlir::Type>(mlir::Type const&) + 32
10 firtool                  0x0000000110b2db75 bool mlir::Type::isa<circt::firrtl::FIRRTLBaseType>() const + 21
11 firtool                  0x0000000110a9abc8 circt::firrtl::__mlir_ods_local_type_constraint_FIRRTL12(mlir::Operation*, mlir::Type, llvm::StringRef, unsigned int) + 72
12 firtool                  0x0000000110a9a9e6 circt::firrtl::ConnectOp::verifyInvariantsImpl() + 214
13 firtool                  0x0000000110939ab2 mlir::OpTrait::OpInvariants<circt::firrtl::ConnectOp>::verifyTrait(mlir::Operation*) + 34
14 firtool                  0x0000000110939985 std::__1::enable_if<detect_has_verify_trait<mlir::OpTrait::OpInvariants<circt::firrtl::ConnectOp>>::value, mlir::LogicalResult>::type mlir::op_definition_impl::verifyTrait<mlir::OpTrait::OpInvariants<circt::firrtl::ConnectOp>>(mlir::Operation*) + 21
15 firtool                  0x000000011093983d mlir::LogicalResult mlir::op_definition_impl::verifyTraits<mlir::OpTrait::ZeroRegions<circt::firrtl::ConnectOp>, mlir::OpTrait::ZeroResults<circt::firrtl::ConnectOp>, mlir::OpTrait::ZeroSuccessors<circt::firrtl::ConnectOp>, mlir::OpTrait::NOperands<2u>::Impl<circt::firrtl::ConnectOp>, mlir::OpTrait::OpInvariants<circt::firrtl::ConnectOp>, circt::firrtl::FConnectLike::Trait<circt::firrtl::ConnectOp>>(mlir::Operation*) + 189
16 firtool                  0x0000000110939725 mlir::Op<circt::firrtl::ConnectOp, mlir::OpTrait::ZeroRegions, mlir::OpTrait::ZeroResults, mlir::OpTrait::ZeroSuccessors, mlir::OpTrait::NOperands<2u>::Impl, mlir::OpTrait::OpInvariants, circt::firrtl::FConnectLike::Trait>::verifyInvariants(mlir::Operation*) + 21
17 firtool                  0x0000000110db1e28 mlir::LogicalResult llvm::detail::UniqueFunctionBase<mlir::LogicalResult, mlir::Operation*>::CallImpl<mlir::LogicalResult (* const)(mlir::Operation*)>(void*, mlir::Operation*) + 56
18 firtool                  0x0000000110864757 llvm::unique_function<mlir::LogicalResult (mlir::Operation*) const>::operator()(mlir::Operation*) const + 55
19 firtool                  0x0000000110863457 mlir::RegisteredOperationName::verifyInvariants(mlir::Operation*) const + 39
20 firtool                  0x00000001108629de (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&) + 734
21 firtool                  0x000000011086386e (anonymous namespace)::OperationVerifier::verifyBlock(mlir::Block&, llvm::SmallVectorImpl<mlir::Operation*>&) + 878
22 firtool                  0x0000000110862d13 (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&) + 1555
23 firtool                  0x0000000110862611 (anonymous namespace)::OperationVerifier::verifyOpAndDominance(mlir::Operation&) + 33
24 firtool                  0x0000000110865430 (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0::operator()(mlir::Operation*) const + 32
25 firtool                  0x000000011086ae44 mlir::LogicalResult mlir::failableParallelForEach<mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0>(mlir::MLIRContext*, mlir::Operation**, mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0&&)::'lambda'()::operator()() const + 148
26 firtool                  0x000000011086ada5 decltype(static_cast<mlir::Operation**>(fp)()) std::__1::__invoke<mlir::LogicalResult mlir::failableParallelForEach<mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0>(mlir::MLIRContext*, mlir::Operation**, mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0&&)::'lambda'()&>(mlir::Operation**&&) + 21
27 firtool                  0x000000011086ad5d void std::__1::__invoke_void_return_wrapper<void, true>::__call<mlir::LogicalResult mlir::failableParallelForEach<mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0>(mlir::MLIRContext*, mlir::Operation**, mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0&&)::'lambda'()&>(mlir::LogicalResult mlir::failableParallelForEach<mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0>(mlir::MLIRContext*, mlir::Operation**, mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0&&)::'lambda'()&) + 29
28 firtool                  0x000000011086ad2d std::__1::__function::__alloc_func<mlir::LogicalResult mlir::failableParallelForEach<mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0>(mlir::MLIRContext*, mlir::Operation**, mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0&&)::'lambda'(), std::__1::allocator<mlir::LogicalResult mlir::failableParallelForEach<mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0>(mlir::MLIRContext*, mlir::Operation**, mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0&&)::'lambda'()>, void ()>::operator()() + 29
29 firtool                  0x0000000110869d79 std::__1::__function::__func<mlir::LogicalResult mlir::failableParallelForEach<mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0>(mlir::MLIRContext*, mlir::Operation**, mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0&&)::'lambda'(), std::__1::allocator<mlir::LogicalResult mlir::failableParallelForEach<mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0>(mlir::MLIRContext*, mlir::Operation**, mlir::Operation**, (anonymous namespace)::OperationVerifier::verifyOperation(mlir::Operation&)::$_0&&)::'lambda'()>, void ()>::operator()() + 25
30 firtool                  0x00000001111a4052 std::__1::__function::__value_func<void ()>::operator()() const + 50
31 firtool                  0x00000001111a4015 std::__1::function<void ()>::operator()() const + 21
32 firtool                  0x00000001111a3fdd llvm::ThreadPool::createTaskAndFuture(std::__1::function<void ()>)::'lambda'()::operator()() const + 29
33 firtool                  0x00000001111a3fa5 decltype(static_cast<llvm::ThreadPool::createTaskAndFuture(std::__1::function<void ()>)::'lambda'()&>(fp)()) std::__1::__invoke<llvm::ThreadPool::createTaskAndFuture(std::__1::function<void ()>)::'lambda'()&>(llvm::ThreadPool::createTaskAndFuture(std::__1::function<void ()>)::'lambda'()&) + 21
34 firtool                  0x00000001111a3f5d void std::__1::__invoke_void_return_wrapper<void, true>::__call<llvm::ThreadPool::createTaskAndFuture(std::__1::function<void ()>)::'lambda'()&>(llvm::ThreadPool::createTaskAndFuture(std::__1::function<void ()>)::'lambda'()&) + 29
35 firtool                  0x00000001111a3f2d std::__1::__function::__alloc_func<llvm::ThreadPool::createTaskAndFuture(std::__1::function<void ()>)::'lambda'(), std::__1::allocator<llvm::ThreadPool::createTaskAndFuture(std::__1::function<void ()>)::'lambda'()>, void ()>::operator()() + 29
36 firtool                  0x00000001111a2d19 std::__1::__function::__func<llvm::ThreadPool::createTaskAndFuture(std::__1::function<void ()>)::'lambda'(), std::__1::allocator<llvm::ThreadPool::createTaskAndFuture(std::__1::function<void ()>)::'lambda'()>, void ()>::operator()() + 25
37 firtool                  0x00000001111a4052 std::__1::__function::__value_func<void ()>::operator()() const + 50
38 firtool                  0x00000001111a4015 std::__1::function<void ()>::operator()() const + 21
39 firtool                  0x000000010fcffd12 llvm::ThreadPool::processTasks(llvm::ThreadPoolTaskGroup*) + 546
40 firtool                  0x000000010fd033f3 llvm::ThreadPool::grow(int)::$_0::operator()() const + 51
41 firtool                  0x000000010fd03385 void llvm::thread::Apply<llvm::ThreadPool::grow(int)::$_0>(std::__1::tuple<llvm::ThreadPool::grow(int)::$_0>&, std::__1::integer_sequence<unsigned long>) + 37
42 firtool                  0x000000010fd03343 void llvm::thread::GenericThreadProxy<std::__1::tuple<llvm::ThreadPool::grow(int)::$_0>>(void*) + 51
43 firtool                  0x000000010fd03075 void* llvm::thread::ThreadProxy<std::__1::tuple<llvm::ThreadPool::grow(int)::$_0>>(void*) + 21
44 libsystem_pthread.dylib  0x00007ff81f37a4e1 _pthread_start + 125
45 libsystem_pthread.dylib  0x00007ff81f375f6b thread_start + 15
```

### LINKED ISSUE #4448: [FIRRTL] WireDFT Needs Hardening
The `WireDFT` pass makes some assumptions about the structure of modules with the `EICG_wrapper` name. Specifically, I think it assumes that any module that starts with `EICG_wrapper` has a second port that is supposed to be hooked up. I _don't_ think this validates the name, type, or directionality.

Consider:

```
circuit Top: %[[
  {
    "class":"sifive.enterprise.firrtl.MarkDUTAnnotation",
    "target":"~Top|Top"
  },
  {
    "class":"sifive.enterprise.firrtl.DFTTestModeEnableAnnotation",
    "target":"~Top|Top>test_en"
    },
  {
    "class":"firrtl.transforms.DontTouchAnnotation",
    "target":"~Top|Top>test_en"
  }
]]
  extmodule EICG_wrapper_Bar:
    output a: UInt<1>
    output b: UInt<1>

  module Foo:
    inst bar of EICG_wrapper_Bar

  module Top:
    wire test_en: UInt<1>
    test_en is invalid

    inst foo of Foo
```

Running this with `firtool Foo.fir` produces:

```
# firtool Tmp.fir -mlir-print-ir-after=firrtl-dft                       
Tmp.fir:19:10: error: connect has invalid flow: the destination expression "bar.b" has source flow, expected sink or duplex flow
  module Foo:
         ^
Tmp.fir:20:5: note: the destination was defined here
    inst bar of EICG_wrapper_Bar
    ^
```

The output MLIR is:

```mlir
"firrtl.circuit"() ({
  "firrtl.extmodule"() ({
  }) {annotations = [], internalPaths = [], parameters = [], portAnnotations = [], portDirections = -1 : i2, portNames = ["a", "b"], portSyms = [], portTypes = [!firrtl.uint<1>, !firrtl.uint<1>], sym_name = "EICG_wrapper_Bar", sym_visibility = "private"} : () -> ()
  "firrtl.module"() ({
  ^bb0(%arg0: !firrtl.uint<1>):
    %0:2 = "firrtl.instance"() {annotations = [], moduleName = @EICG_wrapper_Bar, name = "bar", nameKind = #firrtl<name_kind droppable_name>, portAnnotations = [[], []], portDirections = -1 : i2, portNames = ["a", "b"]} : () -> (!firrtl.uint<1>, !firrtl.uint<1>)
    "firrtl.connect"(%0#1, %arg0) : (!firrtl.uint<1>, !firrtl.uint<1>) -> ()
  }) {annotations = [], portAnnotations = [], portDirections = false, portNames = ["test_en"], portSyms = [], portTypes = [!firrtl.uint<1>], sym_name = "Foo", sym_visibility = "private"} : () -> ()
  "firrtl.module"() ({
    %0 = "firrtl.wire"() {annotations = [{class = "firrtl.transforms.DontTouchAnnotation"}], name = "test_en", nameKind = #firrtl<name_kind droppable_name>} : () -> !firrtl.uint<1>
    %1 = "firrtl.invalidvalue"() : () -> !firrtl.uint<1>
    "firrtl.strictconnect"(%0, %1) : (!firrtl.uint<1>, !firrtl.uint<1>) -> ()
    %2 = "firrtl.instance"() {annotations = [], moduleName = @Foo, name = "foo", nameKind = #firrtl<name_kind droppable_name>, portAnnotations = [[]], portDirections = false, portNames = ["test_en"]} : () -> !firrtl.uint<1>
    "firrtl.connect"(%2, %0) : (!firrtl.uint<1>, !firrtl.uint<1>) -> ()
  }) {annotations = [{class = "sifive.enterprise.firrtl.MarkDUTAnnotation"}], portAnnotations = [], portDirections = 0 : i0, portNames = [], portSyms = [], portTypes = [], sym_name = "Top"} : () -> ()
}) {annotations = [], name = "Top"} : () -> ()
```

### PR DESCRIPTION
**Pull request by dtzSiFive**
Avoid generating invalid or corrupt IR based on assumptions about the structure of the clock gate modules,
and instead check for required structure.

Port name is not checked presently to avoid rejecting circuits that would previously work.

Fixes #4447.
Fixes #4448.

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/WireDFT.cpp [hunk 1]
```diff
@@ -215,9 +215,48 @@ void WireDFTPass::runOnOperation() {
...
+  // Scan gathered clock gates and check for basic compatibility.
+  for (auto *cgnode : clockGates) {
+    auto module = cgnode->getTarget()->getModule();
+    auto genErr = [&]() { return module.emitError("clock gate module "); };
+    FExtModuleOp ext = dyn_cast<FExtModuleOp>(module.getOperation());
+    if (!ext) {
+      genErr() << "must be an extmodule";
+      return signalPassFailure();
+    }
+    static_assert(testEnPortNo == 1, "update this code");
```
Comment (youngar) [inline lib/Dialect/FIRRTL/Transforms/WireDFT.cpp:237]: nice!

File: lib/Dialect/FIRRTL/Transforms/WireDFT.cpp [hunk 2]
```diff
@@ -215,9 +215,48 @@ void WireDFTPass::runOnOperation() {
...
+    if (ext.getNumPorts() <= testEnPortNo) {
+      genErr() << "must have at least two ports";
```
Comment (youngar) [inline lib/Dialect/FIRRTL/Transforms/WireDFT.cpp:239]: I think a slightly more informative error message like the one below might help `must have second port with type UInt<1>"`

**Review by youngar — APPROVED** [review]
Thanks for fixing this.  The requirements for this pass were always a little bit weird, e.g. what is the interface for a clock gate? It would make just as much sense to me to search for a "test_en" port instead of enforcing that it is the second port.  In the future, I think a better interface would be to just annotate any port as a "test_en" pin.

**Review by seldridge — APPROVED** [review]
Looks great!

The tests can be shortened to remove the A module.

**Comment by dtzSiFive** [comment]
> It would make just as much sense to me to search for a "test_en" port instead of enforcing that it is the second port

Absolutely, this is a bit weird as you say...  adhoc and unnecessarily rigid.  Having the clock gates marked explicitly, particularly the port to wire up, seems much nicer :+1:, especially if managed without more annotations.

> The tests can be shortened to remove the A module.

Good call, dropped!

**Comment by seldridge** [comment]
> It would make just as much sense to me to search for a "test_en" port instead of enforcing that it is the second port. In the future, I think a better interface would be to just annotate any port as a "test_en" pin.

The "search for a test_en port" seems a bit weird to me. I do totally agree that this should be reworked, if it remains as a "wiring problem", to use explicit wiring connections. I.e., this entire pass can be reframed as a point-to-point wiring problem that doesn't need to know anything about module names, port orders, or port names.

**Comment by dtzSiFive** [comment]
Thanks folks.  Error messages could be better but this is a start, and avoids crashing and is a bit clearer than debugging IR verification failure.
Let's revisit this API / implementation later as discussed! :+1:.
