### PR TITLE
[FIRRTL] Allow full reset module instances outside of reset domain

### LINKED ISSUE #9396: [FIRRTL] FullResetAnnotation breaks multi-top
Consider the following circuit:

``` firrtl
FIRRTL version 6.0.0
circuit Foo: %[[
  {
    "class": "circt.FullResetAnnotation",
    "target": "~|Foo>reset",
    "resetType": "async"
  }
]]

  module Baz:
    inst bar of Bar

  module Bar:

  public module Foo:
    input reset: AsyncReset

    inst bar of Bar
```

When compiled with `firtool Foo.fir -mlir-print-ir-after-failure`, this will error out because this creates a port on `Bar`, but doesn't update all instances of `Bar`. See commentary later as I think there are actual problems with `FullResetAnnotation` here:

```
circt/async-reset-full-multi-top.fir:11:5: error: 'firrtl.instance' op has a wrong number of results; expected 1 but got 0
    inst bar of Bar
    ^
circt/async-reset-full-multi-top.fir:11:5: note: see current operation: "firrtl.instance"() <{annotations = [], domainInfo = [], layers = [], moduleName = @Bar, name = "bar", nameKind = #firrtl<name_kind droppable_name>, portAnnotations = [], portDirections = array<i1>, portNames = []}> : () -> ()
circt/async-reset-full-multi-top.fir:13:3: note: original module declared here
  module Bar:
  ^
```

MLIR dump:

``` mlir
"firrtl.circuit"() <{annotations = [], name = "Foo"}> ({
  "firrtl.module"() <{
    annotations = [],
    convention = #firrtl<convention internal>,
    domainInfo = [],
    layers = [],
    portAnnotations = [],
    portDirections = array<i1>,
    portLocations = [],
    portNames = [],
    portSymbols = [],
    portTypes = [],
    sym_name = "Baz"
  }> ({
    "firrtl.instance"() <{
      annotations = [],
      domainInfo = [],
      layers = [],
      moduleName = @Bar,
      name = "bar",
      nameKind = #firrtl<name_kind droppable_name>,
      portAnnotations = [],
      portDirections = array<i1>,
      portNames = []
    }> : () -> ()
  }) {sym_visibility = "private"} : () -> ()
  "firrtl.module"() <{
    annotations = [{class = "circt.FullResetAnnotation"}],
    convention = #firrtl<convention internal>,
    domainInfo = [],
    layers = [],
    portAnnotations = [],
    portDirections = array<i1: false>,
    portLocations = [loc("circt/async-reset-full-multi-top.fir":16:11)],
    portNames = ["reset"],
    portSymbols = [],
    portTypes = [!firrtl.asyncreset],
    sym_name = "Bar"
  }> ({
  ^bb0(%arg1: !firrtl.asyncreset):
  }) {sym_visibility = "private"} : () -> ()
  "firrtl.module"() <{
    annotations = [{class = "circt.FullResetAnnotation"}],
    convention = #firrtl<convention scalarized>,
    domainInfo = [[]],
    layers = [],
    portAnnotations = [[{class = "circt.FullResetAnnotation",
    resetType = "async"}]],
    portDirections = array<i1: false>,
    portLocations = [loc("circt/async-reset-full-multi-top.fir":16:11)],
    portNames = ["reset"],
    portSymbols = [],
    portTypes = [!firrtl.asyncreset],
    sym_name = "Foo"
  }> ({
  ^bb0(%arg0: !firrtl.asyncreset):
    %0 = "firrtl.instance"() <{
      annotations = [],
      domainInfo = [[]],
      layers = [],
      moduleName = @Bar,
      name = "bar",
      nameKind = #firrtl<name_kind droppable_name>,
      portAnnotations = [[]],
      portDirections = array<i1: false>,
      portNames = ["reset"]
    }> : () -> !firrtl.asyncreset
    "firrtl.matchingconnect"(%0, %arg0) : (!firrtl.asyncreset, !firrtl.asyncreset) -> ()
  }) : () -> ()
}) : () -> ()
```

The fundamental problem is that `FullResetAnnotation` is a "point-to-point" connection request. It's saying "Hook up this port to all the registers that don't have a reset under me." This has to create ports to do this. However, it assumes that this port can be connected to all of these registers. In the multi-top case, e.g., above where `Bar` is instantiated under `Foo` and `Bar`, it is completely ambiguous as to what should happen here. Specifically, it's unclear how the added port should be driven from an instantiation site that isn't reachable by the requested port.

Pragmatically, there are a couple of things that can help here, but don't address the fundamental problem:

1. Modify the `InferResets` pass to not create ports for modules which don't _need_ the port. I.e., for modules which have no reset-less registers underneath them (in their body or in any body of a module they instantiate).
2. The `InferResets` pass shouldn't create invalid IR. This needs to update instances to add the port, even if it doesn't know what to do with it, other than leaving it unconnected. The phase ordering of `InferResets` before `ExpandWhens` will catch this. (Relying on the phase ordering is dangerous, though...)
3. The other instantiations can create the port on all instances and then tie it to zero. I don't exactly like this, but it's about the only sane thing to do here. A register with a reset tied to zero is the same as a register without a reset in simulation (and we already do this optimization when we see it).

Note: the same problem does exist when there is a register. I.e., the problem here can't just be ignored with a solution to (1):

``` firrtl
FIRRTL version 6.0.0
circuit Foo: %[[
  {
    "class": "circt.FullResetAnnotation",
    "target": "~|Foo>reset",
    "resetType": "async"
  }
]]

  module Baz:
    input clock: Clock

    inst bar of Bar
    connect bar.clock, clock

  module Bar:
    input clock: Clock

    reg r: UInt<1>, clock

  public module Foo:
    input clock: Clock
    input reset: AsyncReset

    inst bar of Bar
    connect bar.clock, clock
```

### PR DESCRIPTION
**Pull request by fabianschuiki**
When a module is part of a full reset domain, we create an additional reset port on it to connect to reset-less registers. At the moment it is an error to instantiate a module which has such an added reset inside a context that has no full reset domain:

```firrtl
firrtl.circuit "Foo" {
  firrtl.module @Foo(
    in %reset: !firrtl.asyncreset
      [{class = "circt.FullResetAnnotation", resetType = "async"}]
  ) {
    firrtl.instance foo @Baz()  // instance within full reset domain
  }
  firrtl.module @Bar() {
    firrtl.instance foo @Baz()  // instance outside any domain; error
  }
  firrtl.module private @Baz() {
    // ...
  }
}
```

This commit explicitly allows instances of such modules inside a context that has no full reset. The added reset port is tied-off to a constant zero value, which effectively turns the reset-less registers that were transformed to be fully reset, back into reset-less registers.

Fixes #9396.

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/InferResets.cpp [hunk 1]
```diff
@@ -1708,16 +1721,24 @@ LogicalResult InferResetsPass::implementFullReset() {
...
-    LLVM_DEBUG(llvm::dbgs()
-               << "- Skipping because module explicitly has no domain\n");
+    SmallVector<InstanceOp> instances;
+    module.walk([&](InstanceOp instOp) { instances.push_back(instOp); });
+    if (!instances.empty()) {
+      LLVM_DEBUG(llvm::dbgs()
+                 << "Tie off instances in " << module.getName() << "\n");
+      for (auto instOp : instances)
+        implementFullReset(instOp, module, Value());
+    }
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/Transforms/InferResets.cpp]: Consider:

```suggestion
    LLVM_DEBUG {
      if (!instances.empty())
        lvm::dbgs()  << "Tie off instances in " << module.getName() << "\n";
    };
    for (auto instOp : instances)
      implementFullReset(instOp, module, Value());
```

**Review by seldridge — APPROVED** [review]
SGTM

I agree that this is about the only sane thing to do here given the "requirements" that the user have given when they apply this annotation. It's going to be too onerous to push this all on users. I am also looking forward to finding a way to do all this in Chisel and remove this feature entirely. 😅

File: lib/Dialect/FIRRTL/Transforms/InferResets.cpp (hunk 1 above)
Comment (fabianschuiki) [reply lib/Dialect/FIRRTL/Transforms/InferResets.cpp]: Oh yeah clever, thanks! 👍

**Comment by fabianschuiki** [comment]
> @seldridge [...] I am also looking forward to finding a way to do all this in Chisel and remove this feature entirely.

Absolutely! The whole reset inference stuff feels like something that should be handled in Chisel directly, and then we can rip out `InferResets` and the `!firrtl.reset` type entirely 🥳
