### PR TITLE
[FIRRTL] Drop domain associations w/ zero-width

### LINKED ISSUE #9471: [FIRRTL] Don't add domain associations for zero-width ports
Change the `LowerDomains` pass to not add associations for zero-width ports. At present, this will error during conversion to HW dialect.

Consider the following circuit:

``` mlir
firrtl.circuit "Foo" {
  firrtl.domain @ClockDomain
  firrtl.module @Foo(
    in %A: !firrtl.domain of @ClockDomain,
    in %a: !firrtl.uint<0> domains [%A]
  ) {}
}
```

When compiled, this errors:

``` console
# ./bin/circt-opt -pass-pipeline='builtin.module(firrtl.circuit(firrtl-lower-domains,firrtl-lower-classes),lower-firrtl-to-hw)' Foo.mlir                         
Foo.mlir:5:8: error: zero width port "a" is referenced by name [#hw<innerSym@sym>] (e.g. in an XMR) but must be removed
    in %a: !firrtl.uint<0> domains [%A]
       ^
```

### PR DESCRIPTION
**Pull request by seldridge**
Modify the `LowerDomains` pass to stop lowering domain association
information for zero-width ports.  The domain association is lowered to
property paths, which use inner symbols on the ports for the tracking.  If
the symbols are there, then this violates a `LowerToHW` assumption which
will cause that conversion to fail.

Fixes #9471.

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/LowerDomains.cpp [hunk 1]
```diff
@@ -407,13 +407,15 @@ LogicalResult LowerModule::lowerModule() {
...
+    // If this port has domain associations and is not zero width, then we need
+    // to add port annotation trackers.  These will be hooked up to the Object's
+    // associations later.  However, if there is no domain information or the
+    // port is zero width, then annotations do not need to be modified.  Early
+    // continue first, adding trackers otherwise.  Only create one tracker for
+    // all associations.
     ArrayAttr domainAttr = cast_or_null<ArrayAttr>(port.domains);
-    if (!domainAttr || domainAttr.empty()) {
+    if (!domainAttr || domainAttr.empty() ||
+        hasZeroBitWidth(type_cast<FIRRTLType>(port.type))) {
```
Comment (dtzSiFive) [inline lib/Dialect/FIRRTL/Transforms/LowerDomains.cpp]: I'm not 100% we require all ports to have `FIRRTLType`, do we?

If we do, then great.  If not, consider handling this case so we don't crash and just skip it / continue.

I tend to prefer defensive code that works regardless (without reason) without relying on remotely-checked properties to be true, but as long as this isn't a bug in the future sounds good to me.

( It may be the case (verifier-checked?) that a port must be FIRRTLType is it has domain information, which I think here would cause the expression to short-circuit?)

File: test/Dialect/FIRRTL/lower-domains.mlir [hunk 2]
```diff
@@ -501,3 +501,23 @@ firrtl.circuit "DeadDomainOps" {
...
+// did, then this would create symbols on zero-width ports which is not allowed
+// by the LowerToHW conversion.
+firrtl.circuit "ZeroWidthPort" {
+  firrtl.domain @ClockDomain
+  // CHECK-LABEL: firrtl.module @ZeroWidthPort(
+  firrtl.module @ZeroWidthPort(
+    in %A: !firrtl.domain of @ClockDomain,
+    in %a: !firrtl.uint<0> domains [%A]
+  ) {
+    // CHECK:       %[[associations_in:.+]] = firrtl.object.subfield %A_object[associations_in]
```
Comment (dtzSiFive) [inline test/Dialect/FIRRTL/lower-domains.mlir]: nit: vertical alignment

File: lib/Dialect/FIRRTL/Transforms/LowerDomains.cpp (hunk 1 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/Transforms/LowerDomains.cpp]: > I'm not 100% we require all ports to have FIRRTLType, do we?

We don't, surprisingly. The following is legal:

``` mlir
firrtl.circuit "Foo" {
  firrtl.module @Foo(in %a: i1) {
  }
}
```

Passes _do_ assume this. The first one I hit that assumed it is `LowerSignatures`. I can't see a reason why we should allow this, so it is probably best to add the verifier to lock this in. The only reason I can see to allow it is if the FIRRTL to HW conversion pipeline wants to be able to do incremental lowering in such a way.

For this PR, I will gate this to avoid the cast failure.

Comment (seldridge) [reply lib/Dialect/FIRRTL/Transforms/LowerDomains.cpp]: Fixed in: [1f6d8e4e3](https://github.com/llvm/circt/pull/9477/commits/1f6d8e4e33e4c55c2c7c3c9641d497b2fe562e50)

File: test/Dialect/FIRRTL/lower-domains.mlir (hunk 2 above)
Comment (seldridge) [reply test/Dialect/FIRRTL/lower-domains.mlir]: Fixed in: 860397f98

**Comment by dtzSiFive** [comment]
At some point it was explicitly carved out that non-FIRRTL types were
supported in wires and, I thought, ports.

This was a clear but maybe informal decision IIRC, motivated by uses with
tools that might wish to mix in data types early in FIRRTL-based designs.

Probably LowerSignatures just has a bug w.r.t to this, but I have no idea
how much of our compiler relies on this today.

(Since it doesn't support them, probably the use I'm thinking of is able to
avoid this or that policy has changed!)

Thanks for handling this regardless, appreciate it!
