### PR TITLE
[FIRRTL] ModuleInliner: new NLA support

### LINKED ISSUE #3334: [FIRRTL] New NLA Support in ModuleInliner
FIRRTL's Module Inliner definitely does not work with the new-style NLA paths. The problem is that [the NLA is marked dead if it ends in a module](https://github.com/llvm/circt/blob/c266174ef9410ff345a31a2af289f1d70d5d6147/lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp#L325). Instead, the NLA is still alive so long as it has uses within the module.

Consider:

```mlir
firrtl.circuit "Top" {
  firrtl.hierpath @path_component_old [@Top::@foo, @Foo::@bar1, @Bar::@b]
  firrtl.hierpath @path_component_new [@Top::@foo, @Foo::@bar1, @Bar]
  firrtl.module private @Bar() attributes {annotations = [{class = "firrtl.passes.InlineAnnotation"}]} {
    %b = firrtl.wire sym @b {annotations = [
      {circt.nonlocal = @path_component_old, "path_component_old"},
      {circt.nonlocal = @path_component_new, "path_component_new"}
    ]} : !firrtl.uint<1>
  }
  firrtl.module private @Foo() {
    firrtl.instance bar1 sym @bar1 @Bar()
    firrtl.instance bar2 sym @bar2 @Bar()
  }
  firrtl.module @Top() {
    firrtl.instance foo sym @foo @Foo()
  }
}
```

This currently drops `@path_component_new` because it gets marked dead when `@Bar` is inlined:

```
# circt-opt Bar.mlir -firrtl-inliner -debug-only=firrtl-inliner
===- Running Module Inliner Pass --------------------------------------------===
NLA modifications:
  - orig:           firrtl.hierpath @path_component_old [@Top::@foo, @Foo::@bar1, @Bar::@b]
    new:            firrtl.nla @path_component_old [#hw.innerNameRef<@Top::@foo>, #hw.innerNameRef<@Foo::@b>]
    dead:           0
    isDead:         0
    isLocal:        0
    inlinedSymbols: [3]
    flattenPoint:   -1
    renames:
  - orig:           firrtl.hierpath @path_component_new [@Top::@foo, @Foo::@bar1, @Bar]
    new:            
    dead:           1
    isDead:         1
    isLocal:        0
    inlinedSymbols: [3]
    flattenPoint:   -1
    renames:
===--------------------------------------------------------------------------===
module {
  firrtl.circuit "Top"  {
    firrtl.hierpath @path_component_old [@Top::@foo, @Foo::@b]
    firrtl.module private @Foo() {
      %bar1_b = firrtl.wire sym @b   {annotations = [{circt.nonlocal = @path_component_old, path_component_old}]} : !firrtl.uint<1>
      %bar2_b = firrtl.wire sym @b_0   : !firrtl.uint<1>
    }
    firrtl.module @Top() {
      firrtl.instance foo sym @foo  @Foo()
    }
  }
}
```

### PR DESCRIPTION
**Pull request by dtzSiFive**
Primarily focused on addressing issue with deleting NLA's that end in a module (FlatSymbolRefAttr).

Fixes #3334 .

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp [hunk 1]
```diff
@@ -974,6 +1047,9 @@ void Inliner::run() {
       if (auto ref = p.dyn_cast<InnerRefAttr>())
         instOpHierPaths[ref].push_back(nla.sym_nameAttr());
   }
+  // Mark 'module-only' the NLA's that only target modules.
+  // These may be deleted when their module is inlined/flattened.
+  identifyNLAsTargetingOnlyModules();
```
Comment (prithayan) [inline lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp:1052]: I was wondering if this preprocess step is really necessary , instead of doing this lazily ?
The `Inliner::cloneAndRename` will eventually visit every nonlocal annotation specified on an operation inside the module, that is inlined/flattened.  Maybe we can mark an NLA dead/live after a module is cloned ?
If this doesn't affect the performance much, then it maybe totally fine to just do this.

Comment (dtzSiFive) [reply lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp:1052]: I considered that, but since the code [is careful to update the (mutable)NLA's _before_ visiting operations](https://github.com/llvm/circt/blob/31511a79f153c7229ce7121ec0c41ffa03229da0/lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp#L914) (search for "Preorder" for other locations), I wasn't sure this approach would work (or that it'd be obviously correct if it did).  It does appear that the updating before cloning is more for the local/non-local handling, not dead/alive.

Thinking out loud a little...
As a small addition (that you likely already were thinking of), I think your suggested approach would also need to add something to `mapPortsToWires` so those keep their NLA's alive as well (for ports too not just operations visited in `cloneAndRename`), be that setting a flag on the MNLA ("referenced by a non-module target") for checking in a later GC-ish processing, and/or maintaining a set of "live" NLA's or mutable NLA's or however that would work (hmm, how would the Inliner know which NLA's to go through and check whether they are now dead ("mark an NLA dead/live after a module is cloned"), at the point after cloning the ops/ports-- re-walking to find them again ofc largely defeats the purpose of avoiding the pre-process, modulo locality I suppose; if we can defer determining dead-ness until the end then that simplifies things).   Not saying this isn't resolvable, just some details to sort I suppose :smile:.  Maybe this is simpler than I'm thinking :innocent: , my headspace is a bit full of other details at the moment.

I suspect we might be able to do as you say re:moving dead/live handling afterwards (and generally avoiding the preprocess step).  That does seem potentially more elegant, assuming it doesn't add much more complexity / tracking to things.

I can take a look soon (TM), or do you have a plan in mind? I know you've been working with this code and NLA's quite a bit.  We can chat offline about it too if you'd like! :+1: 

In the meantime I'll look at this some more/think a bit and go from there.  Thanks!

File: lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp [hunk 2]
```diff
@@ -205,6 +216,7 @@ class MutableNLA {
                  << "    new:            " << *this << "\n"
                  << "    dead:           " << dead << "\n"
                  << "    isDead:         " << isDead() << "\n"
+                 << "    isModuleOnly:   " << isModuleOnly() << "\n"
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp:219]: Thanks for keeping the debug info up-to-date.

File: lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp [hunk 3]
```diff
@@ -960,12 +978,67 @@ void Inliner::inlineInstances(FModuleOp parent) {
...
+
+    // Scan operations (and not the module itself):
+    mod.getBody()->walk([&](Operation *op) {
+      for (auto anno : AnnotationSet(op))
+        if (auto sym = anno.getMember<FlatSymbolRefAttr>("circt.nonlocal"))
+          referencedNLASyms.insert(sym.getAttr());
+    });
+
+    return referencedNLASyms;
+  };
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp:1008]: @youngar has brought up on a PR of mine that this isn't checking for two cases (which may or may not matter): (1) annotations on instance ports and (2) annotations on memory ports.

While I currently think a large part of this is unreachable (e.g., https://github.com/llvm/circt/issues/3340 shows the inability of CIRCT to even generate things of type (1) above), it would still be good to iterate over the ports of memories and instances to dig out any annotations that may reference hierpath symbols.

File: lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp [hunk 4]
```diff
@@ -960,12 +978,67 @@ void Inliner::inlineInstances(FModuleOp parent) {
...
+  // Gather set of NLA's referenced by each module's ports/operations.
+
+  // Vector of modules and vector for storing results of each walk:
+  SmallVector<FModuleOp, 16> mods(nlaTargetedModules.begin(),
+                                  nlaTargetedModules.end());
+  SmallVector<DenseSet<StringAttr>, 16> refSets;
+  refSets.resize(nlaTargetedModules.size());
+  mlir::parallelForEachN(
+      circuit->getContext(), 0, nlaTargetedModules.size(),
+      [&](size_t index) { refSets[index] = scanForNLARefs(mods[index]); });
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp:1020]: Is this `refSets[]` safe to use inside the `parallelForEachN` even if the `refSets` is properly sized above?

File: lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp [hunk 5]
```diff
@@ -960,12 +978,67 @@ void Inliner::inlineInstances(FModuleOp parent) {
...
+
+  // Combine sets into single "is referenced by a port/operation" set
+  DenseSet<StringAttr> nonModOnlyNLAs;
+  for (auto &set : refSets)
+    nonModOnlyNLAs.insert(set.begin(), set.end());
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp:1025]: You could consider using a `parallelTransformReduce` instead of `parallelForEachN` with a reduction after.

**Review by seldridge — APPROVED** [review]
LGTM with digging through Instance and Memory port lists for symbol references.

Super clean and easy to follow. Thanks for getting this together.

File: lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp (hunk 3 above)
Comment (dtzSiFive) [reply lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp]: Since the ModuleInliner itself doesn't look into these types of annotations, I'm not sure what happens if these are encountered.  I added support for MemOp ports to this portion of the code, and will look into InstanceOp port annotations-- will add that shortly-- `AnnotationSet` doesn't have the nice helpers for it, and FWIW `PortAnnoTarget::getType()` checks for `InstanceOp` (in same place checks for `MemOp`) but there's no constructor that makes that possible AFAICT.  Anyway, will add that shortly.  Better safe than sorry re:removing.

This all makes it seem, as mentioned previously elsewhere, that having something cleanup dead HierPathOp's would be a good idea, and would largely use this sort of code (or similar from the other NLA migration PR's), where we definitely want to handle all these things (regardless of what's reachable here :smile:).

Comment (seldridge) [reply lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp]: 😂  I didn't realize that `ModuleInliner` wasn't even looking at these. That is some empirical evidence that this may be pretty rare. Thanks for adding this, though.

File: lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp [hunk 6]
```diff
@@ -379,6 +394,34 @@ static void mapResultsToWires(BlockAndValueMapping &mapper,
   }
 }
 
+/// Wrapper for llvm::parallelTransformReduce that performs the transform_reduce
+/// serially when MLIR multi-threading is disabled.
+/// Does not add a ParallelDiagnosticHandler like mlir::parallelForEach .
```
[the remark this answers is not in the document]
Comment (dtzSiFive) [reply lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp:399]: Either way, they're both wrappers for `failableParallelForEach`.  Maybe this comment is unnecessary, just didn't want this to appear to be doing everything one might expect from the MLIR-multithreading-aware bits in `include/mlir/IR/Threading.h`, although if we end up using `parallelTransformReduce` more than 2x in our code base (and wanted parallel diagnostic support) that wouldn't be hard to put together, it's just overkill for this.

File: lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp (hunk 1 above)
Comment (dtzSiFive) [reply lib/Dialect/FIRRTL/Transforms/ModuleInliner.cpp:1091]: Okay!

Also, performance on large design seems to at least not be problematic, before/after timings producing rather overlapping distributions with maybe this shifting average up a small amount.

Finding a more integrated solution would be nice, thanks!

**Review by seldridge — APPROVED** [review]
LGTM

Thanks for taking care of the updates to the patch.
