### PR TITLE
[firtool] Move width inference before canonicalization

### LINKED ISSUE #1131: [FIRRTL] (andr, orr, xorr) folder missing
Not a bug, but missing constant folder for `andr, orr, xorr` operations.

The following FIRRTL program

```python
circuit top_mod :
  module top_mod :
    output tmp62: UInt<1>
    wire tmp42: SInt
    tmp42 <= SInt<13>("o-2562")
    tmp62 <= orr(tmp42)
```

Compiled with `firtool` produces this Verilog:

```verilog
module top_mod(
  output tmp62);

  wire [12:0] tmp42;	// a_top_mod.fir:4:5

  assign tmp42 = 13'h1A8E;	// a_top_mod.fir:5:{11,14}
  assign tmp62 = |tmp42;	// a_top_mod.fir:2:3, :6:14
endmodule
```

Compiled with `firrtl-1.5-SNAPSHOT` produces this Verilog:

```verilog
module top_mod(
  output  tmp62
);
  assign tmp62 = 1'h1;
endmodule
```

### LINKED ISSUE #1136: [FIRRTL] (tail) false negative
The following FIRRTL program

```python
circuit top_mod :
  module top_mod :
    output tmp5: UInt<16>
    output tmp55: SInt
    tmp55 <= mux(head(UInt<11>(57), 1), SInt("h66b9c5"), SInt("b-1"))
    tmp5 <= tail(tmp55, 8)
```

Compiled with `firtool` produces this Error:

```
a_top_mod.fir:6:13: error: amount must be less than or equal operand width
    tmp5 <= tail(tmp55, 8)
            ^
```

Compiled with `firrtl-1.5-SNAPSHOT` produces this Verilog:

```verilog
module top_mod(
  output [15:0] tmp5,
  output [23:0] tmp55
);
  assign tmp5 = tmp55[15:0];
  assign tmp55 = -24'sh1;
endmodule
```

### LINKED ISSUE #1139: [FIRRTL] width inference (dshr) mismatch
The following FIRRTL program

```python
circuit top_mod :
  module top_mod :
    output tmp73: UInt<4>
    tmp73 <= dshr(UInt<4>("b100"), UInt("h2a2"))
```

Compiled with `firtool` produces this Verilog:

```verilog
module top_mod(
  output [3:0] tmp73);

  assign tmp73 = 4'h1;	// a_top_mod.fir:2:3, :4:14
endmodule
```

Compiled with `firrtl-1.5-SNAPSHOT` produces this Verilog:

```verilog
module top_mod(
  output [3:0] tmp73
);
  assign tmp73 = 4'h0;
endmodule
```

`Yosys 0.9+3911 (git sha1 4b31223e, clang 11.0.1 -fPIC -Os)` reports formal mismatch:

```
ERROR: Found 1 unproven $equiv cells in 'equiv_status -assert'.
```

### LINKED ISSUE #1142: [FIRRTL] width inference (mux) mismatch
The following FIRRTL program

```python
circuit top_mod :
  module top_mod :
    input _tmp15: UInt<22>
    output tmp19: UInt
    tmp19 <= mux(UInt<1>(1), UInt(192), _tmp15)
```

Compiled with `firtool` produces this Verilog:

```verilog
module top_mod(
  input  [21:0] _tmp15,
  output [7:0]  tmp19);

  assign tmp19 = 8'hC0;	// a_top_mod.fir:2:3, :5:30
endmodule
```

Compiled with `firrtl-1.5-SNAPSHOT` produces this Verilog:

```verilog
module top_mod(
  input  [21:0] _tmp15,
  output [21:0] tmp19
);
  assign tmp19 = 22'hc0;
endmodule
```

tmp19 width is different

`Yosys 0.9+3911 (git sha1 4b31223e, clang 11.0.1 -fPIC -Os)` reports formal mismatch:

```
ERROR: Can't match gold port `tmp19_gold' to a gate port.
```

### PR DESCRIPTION
**Pull request by fabianschuiki**
Move the width inference pass up in the pipeline such that it runs before the canonicalization passes. This is useful since width inference itself does not depend on canonicalization, but in turn enables a lot of canonicalization patterns to run.

This is basically @darthscsi's https://github.com/llvm/circt/tree/dev/darthscsi/default.inferwidth branch, but without making width inference run by default.

### CODE REVIEW

**Review by seldridge — APPROVED** [review]
This looks fine. 

Is there any problem with moving the multithreaded context up? I know `InferWidths` does its own thing internally to handle threading, but I'm not sure about CSE/SimpleCanonicalizer?

File: tools/firtool/firtool.cpp [hunk 1]
```diff
@@ -177,6 +177,16 @@ processBuffer(std::unique_ptr<llvm::MemoryBuffer> ownedBuffer,
     assert(inputFormat == InputMLIRFile);
     module = parseSourceFile(sourceMgr, &context);
   }
+  if (!module)
+    return failure();
+
+  // Allow optimizations to run multithreaded.
+  context.enableMultithreading(isMultithreaded);
+
+  // Width inference creates canonicalization oppertunities
```
Comment (lattner) [inline tools/firtool/firtool.cpp:186]: typo "oppertunities"
nit: please end sentence comments with a period.

**Review by lattner — APPROVED** [review]
Thanks!

**Review by darthscsi — APPROVED** [review]

**Comment by darthscsi** [comment]
It doesn't fix those bugs until it runs by default though.

**Comment by lattner** [comment]
We should turn multithreading on right after the parser.

**Comment by fabianschuiki** [comment]
@darthscsi You're right this doesn't fix the bugs per se unless it runs by default. I'll drop the autofix.
