### PR TITLE
[HGLDD] Uniquify object names during emission

### LINKED ISSUE #6749: [HGLDD] Uniquify object names during emission
Make HGLDD emission add some form of uniquification suffix to objects with duplicate names. Right now, if there are two debug variables with the same name, the emitter will happily include both with the same name. This is likely to crash in the tool that ingests the debug information (some may materialize the debug variables as Verilog XMRs or similar kinds of "views").

Also prevent empty names from being printed.

### PR DESCRIPTION
**Pull request by fabianschuiki**
Ensure the object and variable names emitted by the `EmitHGLDD` translation are unique and don't collide with any known Verilog keywords.

Refactor the emission code by pulling most of the shared emission state into a `GlobalState` struct that is created by the `Emitter` and is shared by each `FileEmitter`.

Move the `objectNamespace` that is used to uniquify object names into the new global emitter state, and use `sv::legalizeName` to uniquify module names instead of `Namespace`. This avoids keyword collisions. Also add a per-module `moduleNamespace` that is prepopulated with the global `objectNamespace`, and use it to uniquify variable and instance names.

Fixes #6749.

### CODE REVIEW

File: lib/Target/DebugInfo/EmitHGLDD.cpp [hunk 1]
```diff
@@ -160,12 +160,41 @@ static bool makePathRelative(StringRef path, StringRef relativeTo,
   return outputIt == outputEnd;
 }
 
+static StringRef legalizeName(StringRef name, llvm::StringMap<size_t> &ns) {
+  return sv::legalizeName(name, ns, true);
```
Comment (uenoku) [inline lib/Target/DebugInfo/EmitHGLDD.cpp:164]: nit: Can you add a comment why it uses sv::legalizeName?

Comment (fabianschuiki) [reply lib/Target/DebugInfo/EmitHGLDD.cpp]: Great point, thanks. I have added a comment.

**Review by uenoku — APPROVED** [review]
LGTM!
