### PR TITLE
Can't cast to a non-passive type, need another node

### LINKED ISSUE #206: [FIRRTL] LowerToRTL Unhandled op failure
Consider:
module {
  firrtl.circuit "foo" {
    firrtl.module @bar(%io_cpu_flush: !firrtl.uint<1>) {}
    firrtl.module @foo() {
      %fetch = firrtl.instance @bar {name = "fetch"} : !firrtl.bundle<io_cpu_flush: flip<uint<1>>>
      %1454 = firrtl.subfield %fetch("io_cpu_flush") : (!firrtl.bundle<io_cpu_flush: flip<uint<1>>>) -> !firrtl.flip<uint<1>>
      %hits_1_7 = firrtl.node %1454 {name = "hits_1_7"} : !firrtl.flip<uint<1>>
      %1455 = firrtl.asPassive %hits_1_7 : (!firrtl.flip<uint<1>>) -> !firrtl.uint<1>
    }
  }
}

FIRRTLLowering::handleUnloweredOp inserts a StdIntCast to a flipped type which fails to verify.

### PR DESCRIPTION
**Pull request by darthscsi**
Closes #206

### CODE REVIEW

File: lib/Dialect/FIRRTL/LowerToRTL.cpp [hunk 1]
```diff
@@ -730,8 +730,13 @@ void FIRRTLLowering::handleUnloweredOp(Operation *op) {
       continue;
 
     // Otherwise, insert a cast from the lowered value.
-    Value mapped = builder->create<StdIntCast>(op->getLoc(),
-                                               origValue.getType(), it->second);
+    Value mapped = builder->create<StdIntCast>(
+        op->getLoc(), origValue.getType().cast<FIRRTLType>().getPassiveType(),
+        it->second);
+    if (!origValue.getType().cast<FIRRTLType>().isPassive())
+      mapped = builder->create<AsNonPassivePrimOp>(op->getLoc(),
```
Comment (lattner) [inline lib/Dialect/FIRRTL/LowerToRTL.cpp:737]: Nice catch.  Can you use the `castToFIRRTLType` helper on line ~213?

**Review by lattner — APPROVED** [review]
Test looks great!

**Comment by lattner** [comment]
very nice andrew
