### PR TITLE
[FIRRTL] Fix bug in GCT Taps XMRs

### LINKED ISSUE #3414: [FIRRTL] GCT Tap Upwards XMR Bug
The following produces an invalid XMR after the new GCT Taps "minimal XMR" patch:

```scala
circuit Top :
  extmodule DataTap_1 :
    output _0 : UInt<1>
    defname = DataTap_1

  module Submodule :

    inst DataTap_1 of DataTap_1

  module DUT :

    wire _foo : UInt<1>
    _foo <= UInt<1>(0)

    inst submodule of Submodule

  module Top :

    inst dut of DUT
```

```json
[
  {
    "class":"sifive.enterprise.grandcentral.DataTapsAnnotation",
    "blackBox":"~Top|DataTap_1",
    "keys":[
      {
        "class":"sifive.enterprise.grandcentral.ReferenceDataTapKey",
        "source":"~Top|Top/dut:DUT>_foo",
        "portName":"~Top|DataTap_1>_0"
      }
    ]
  }
]
```

This produces (`firtool Top.fir -annotation-file Top.anno.json -firrtl-grand-central`) a data tap with contents:

```verilog
module DataTap_1_impl_0(
  output _0);

  assign _0 = Top._foo;
endmodule
```

The XMR should be `DUT._foo`.

### PR DESCRIPTION
**Pull request by seldridge**
Fix a bug in Grand Central (GCT) Data/Mem Taps pass where Data Taps
could be produced with invalid XMRs.  An exhaustive test case is added
that checks all permutations of upwards and downwards XMRs including
corner cases where the tap module is a leaf and the root.

Fixes #3414.

Signed-off-by: Schuyler Eldridge <schuyler.eldridge@sifive.com>

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp [hunk 1]
```diff
@@ -847,36 +852,18 @@ void GrandCentralTapsPass::runOnOperation() {
...
-            port.nla.root() != rootModule.moduleNameAttr()) {
-          // This handles the case when nla is not considered for common prefix
-          // stripping.
-          auto rootMod = port.nla.root();
-          for (auto p : path) {
-            if (rootMod == p->getParentOfType<FModuleOp>().getNameAttr())
-              break;
-            addSymbol(getInnerRefTo(p));
-          }
-        }
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp:860]: This block of code was surprisingly not covered by existing tests after https://github.com/llvm/circt/commit/43035e72f55a35721c1dc9ea66799be3114d93b2. The logic that merged NLA path with the computed instance paths made this unreachable (for the tests we had).

**Review by youngar — APPROVED** [review]
LGTM!
