### PR TITLE
[FIRRTL] Error on Uninferred Abstract Reset

### LINKED ISSUE #779: [FIRRTL] Disallow Top-level Abstract Reset
The following circuit should be an error. Assumedly, this should be a verification hook added to either a FIRRTL circuit or to a module that is conditioned on it being the top module.

```scala
circuit Foo:
  module Foo:
    input a_d: UInt<1>
    output a_q: UInt<1>
    input r: Reset
    input c: Clock


    reg x: UInt<1>, c with:
      reset => (r, UInt<1>(0))

    x <= a_d
    a_q <= x
```

When running with the Scala FIRRTL Compiler, this errors quickly:

```bash
firrtl -i chiselTests/Reset.fir                     
# Exception in thread "main" firrtl.passes.CheckHighFormLike$ResetInputException: : [module Foo] Abstract Reset not allowed as top-level input: r
```

When compiling with CIRCT, this happily goes all the way to Verilog and generates a synchronous reset flip flop.

### PR DESCRIPTION
**Pull request by seldridge**
Augment `InferResets` to error if any abstract reset ports remain after it runs.  (Just looking for abstract reset ports should be sufficient.)

Fixes #779.

A number of tests has abstract reset ports in them. Remove these in the first commit (which I'll land separately).

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/InferResets.cpp [hunk 1]
```diff
@@ -439,6 +439,8 @@ struct InferResetsPass : public InferResetsBase<InferResetsPass> {
   LogicalResult implementAsyncReset(FModuleOp module, ResetDomain &domain);
   void implementAsyncReset(Operation *op, FModuleOp module, Value actualReset);
 
+  LogicalResult assertOnAbstractReset();
```
Comment (youngar) [inline lib/Dialect/FIRRTL/Transforms/InferResets.cpp:442]: Maybe `assertHasNoAbstractReset` or `assertHasNoAbstractResetPorts(FModule module)`. Otherwise maybe it should be `abortOnAbstractReset()` or something?

Comment (fabianschuiki) [reply lib/Dialect/FIRRTL/Transforms/InferResets.cpp:442]: How about `verifyNoAbstractReset()` since the code doesn't contain an `assert` or aborts in any way, but produces a proper diagnostic and returns gracefully?

Just random nitpicking 😁

**Review by fabianschuiki — APPROVED** [review]
This looks great to me!

File: lib/Dialect/FIRRTL/Transforms/InferResets.cpp (hunk 1 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/Transforms/InferResets.cpp]: Opting for Fabian's suggestion, though I'm totally fine with anything here.
