### PR TITLE
[FIRRTL] Verify public FModuleLike's don't have input probes.

### LINKED ISSUE #6432: [FIRRTL] Verifier Should Reject External Modules with Input Probes
Currently, the FIRRTL Parser will reject trivial input probes on external modules. However, this is not enshrined in the verifier. E.g., the following circuit has an illegal FIRRTL external module, yet it is only caught during `firrtl-probe-dce`:

```
FIRRTL version 3.3.0
circuit Foo:
  extmodule Bar:
    input a: {a: Probe<UInt<1>>}
    output b: {flip a: Probe<UInt<1>>}
    input c: Probe<UInt<1>>[1]
  module Foo:
    input a: UInt<1>

    inst bar of Bar
    define bar.a.a = probe(a)
    define bar.b.a = probe(a)
    define bar.c[0] = probe(a)
```

```
[firtool] Running fir parser
[firtool] -- Done in 0.000 sec
[firtool] Running "firrtl.circuit(firrtl-lower-open-aggs,firrtl-resolve-paths,firrtl-lower-annotations{disable-annotation-classless=false disable-annotation-unknown=false no-ref-type-ports=false},firrtl-lower-intrinsics,firrtl-inject-dut-hier,firrtl.module(firrtl-drop-names{preserve-values=none},cse,firrtl-lower-chirrtl,firrtl-lower-matches),firrtl-infer-widths,firrtl-mem-to-reg-of-vec{ignore-read-enable-mem=false repl-seq-mem=false},firrtl-infer-resets,firrtl-drop-const,firrtl-hoist-passthrough{hoist-hw=false},firrtl-probe-dce,firrtl-dedup,firrtl-dft,firrtl.module(firrtl-flatten-memory),firrtl-lower-types{flatten-mem=false preserve-aggregate=none preserve-memories=none},any(firrtl-expand-whens),firrtl.module(firrtl-sfc-compat,firrtl-group-merge,firrtl-group-sink),firrtl-lower-groups,firrtl-inliner,firrtl.module(firrtl-randomize-register-init),firrtl-check-comb-loops,firrtl.module(canonicalize{  max-iterations=10 max-num-rewrites=-1 region-simplify=false test-convergence=false top-down=true},firrtl-infer-rw),firrtl-prefix-modules,firrtl-imconstprop,firrtl-hoist-passthrough{hoist-hw=false})"
[firtool]   Running "firrtl-lower-open-aggs"
[firtool]   -- Done in 0.000 sec
[firtool]   Running "firrtl-resolve-paths"
[firtool]   -- Done in 0.000 sec
[firtool]   Running "firrtl-lower-annotations{disable-annotation-classless=false disable-annotation-unknown=false no-ref-type-ports=false}"
[firtool]   -- Done in 0.000 sec
[firtool]   Running "firrtl-lower-intrinsics"
[firtool]   -- Done in 0.000 sec
[firtool]   Running "firrtl-inject-dut-hier"
[firtool]   -- Done in 0.000 sec
[firtool]   Running "firrtl.module(firrtl-drop-names{preserve-values=none},cse,firrtl-lower-chirrtl,firrtl-lower-matches)"
[firtool]   -- Done in 0.000 sec
[firtool]   Running "firrtl-infer-widths"
[firtool]   -- Done in 0.000 sec
[firtool]   Running "firrtl-mem-to-reg-of-vec{ignore-read-enable-mem=false repl-seq-mem=false}"
[firtool]   -- Done in 0.000 sec
[firtool]   Running "firrtl-infer-resets"
[firtool]   -- Done in 0.000 sec
[firtool]   Running "firrtl-drop-const"
[firtool]   -- Done in 0.000 sec
[firtool]   Running "firrtl-hoist-passthrough{hoist-hw=false}"
[firtool]   -- Done in 0.000 sec
[firtool]   Running "firrtl-probe-dce"
firrtl-snippets/InputProbesExtmodule.fir:4:11: error: input probe not allowed on this module kind
    input a: {a: Probe<UInt<1>>}
```

Improve the verifier to categorically rejects this.

### PR DESCRIPTION
**Pull request by dtzSiFive**
Add verifier for public modules not having input-oriented probes.

Fixes #6432.

Previously: https://github.com/llvm/circt/pull/6121/files#r1334831540 .

### CODE REVIEW

File: lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp [hunk 1]
```diff
@@ -98,6 +98,31 @@ LogicalResult circt::firrtl::verifyModuleLikeOpInterface(FModuleLike module) {
   if (module->getNumRegions() != 1)
     return module.emitOpError("requires one region");
 
+  if (module.isPublic()) {
+    for (auto &pi : module.getPorts()) {
```
Comment (nandor) [inline lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp:102]: nit: this function has many other checks, how about moving this one to a function whose name also captures its functionality?

**Review by nandor — APPROVED** [review]
LGTM

File: lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp (hunk 1 above)
Comment (dtzSiFive) [reply lib/Dialect/FIRRTL/FIRRTLOpInterfaces.cpp:102]: Oh, great call, thanks! Will refactor accordingly :+1:
