### PR TITLE
[OM] Fix object field value is considered fully evaluated even it's not

### LINKED ISSUE #10264: [domaintool][OM] Assertion failure when bouncing through extra object
I've got a failure when using `domaintool` with the following example. This is likely a general bug (that I introduced) in the OM evaluator:

``` mlir
om.class @Domain(%in: !om.string)  -> (out: !om.string) {
  om.class.fields %in : !om.string
}
om.class @Foo_Class(%basepath: !om.frozenbasepath)  -> (test: i1) {
  %0 = om.constant "A" : !om.string
  %1 = om.object @Domain(%0) : (!om.string) -> !om.class.type<@Domain>
  %2 = om.object.field %1, [@out] : (!om.class.type<@Domain>) -> !om.string
  %3 = om.object @Domain(%2) : (!om.string) -> !om.class.type<@Domain>
  %4 = om.object.field %3, [@out] : (!om.class.type<@Domain>) -> !om.string
  %5 = om.constant "B" : !om.string
  %6 = om.prop.eq %4, %5 : !om.string
  om.class.fields %6 : i1
}
```

Running this, I hit an assertion:

``` console
# ./build/bin/domaintool ./build/Foo.reduced.mlir -module Foo
Assertion failed: (detail::isPresent(Val) && "dyn_cast on a non-existent value"), function dyn_cast, file Casting.h,
line 656.
zsh: abort      domaintool Foo.reduced.mlir -module Foo
```

The problem is that in `ReferenceValue::getStrippedValue`, while this is walking backwards, eventually this hits a
`currentValue.get()` which is nullptr:

```
(lldb) frame select 5
frame #5: 0x000000010339faa0
domaintool`circt::om::evaluator::ReferenceValue::getStrippedValue(this=0x000000010f30de58) const at Evaluator.h:136:22
   133    FailureOr<EvaluatorValuePtr> getStrippedValue() const {
   134      llvm::SmallPtrSet<ReferenceValue *, 4> visited;
   135      auto currentValue = value;
-> 136      while (auto *v = dyn_cast<ReferenceValue>(currentValue.get())) {
   137        // Detect a cycle.                                                                                          138        if (!visited.insert(v).second)                                                                              139          return failure();
(lldb) print currentValue.get()                                                                                        (std::shared_ptr<circt::om::evaluator::EvaluatorValue>::element_type *) nullptr                                        (lldb) print currentValue
(circt::om::evaluator::EvaluatorValuePtr) nullptr {                                                                      pointer = nullptr                                                                                                    }
```

If I remove the second `om.object`, then everything works.

### PR DESCRIPTION
**Pull request by uenoku**
This fixes an issue that object field is considered as evaluated even when it's still pending. The fix itself was only:
```
if (!finalField->isFullyEvaluated())
    return objectFieldValue;
```

However this change forces a more proper cycle detection mechanism for dataflow cycle, so this PR also added a counter that tracks the number of fully evaluated values. I'm hoping to replace these fixes with more simpler solution that actually mutates the IR as mentioned in https://github.com/llvm/circt/pull/10265

Fixes #10264.

Assisted-by: Augment: claude-sonnet-4.5

### CODE REVIEW

File: include/circt/Dialect/OM/Evaluator/Evaluator.h [hunk 1]
```diff
@@ -61,6 +61,14 @@ class EvaluatorValue : public std::enable_shared_from_this<EvaluatorValue> {
   void markFullyEvaluated() {
     assert(!fullyEvaluated && "should not mark twice");
     fullyEvaluated = true;
+    // Increment the counter if one is set.
+    if (fullyEvaluatedCounter)
+      (*fullyEvaluatedCounter)++;
```
Comment (seldridge) [inline include/circt/Dialect/OM/Evaluator/Evaluator.h:66]: Mega-nit: Pre- and post-increment are the same here, but pre-increment may be more canonical.

```suggestion
      ++(*fullyEvaluatedCounter);
```

File: lib/Dialect/OM/Evaluator/Evaluator.cpp [hunk 2]
```diff
@@ -380,18 +391,48 @@ circt::om::Evaluator::instantiate(
...
+      worklist.pop_back();
+      auto result = evaluateValue(value, args, loc);
+
+      if (failed(result))
+        return failure();
+
+      // If not fully evaluated, add to next worklist for retry
+      if (!result.value()->isFullyEvaluated()) {
+        nextWorklist.push_back({value, args});
+      }
```
Comment (seldridge) [inline lib/Dialect/OM/Evaluator/Evaluator.cpp:416]: Nit:
```suggestion
      if (!result.value()->isFullyEvaluated())
        nextWorklist.push_back({value, args});
```

File: unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp [hunk 3]
```diff
@@ -669,6 +670,51 @@ om.class @ReferenceEachOther() -> (field: !ty){
   ASSERT_TRUE(failed(result));
 }
 
+// Test for issue #10264 - nested object field references that previously
+// caused an assertion failure. This test verifies that the evaluator can
+// properly handle nested field accesses without hitting null pointers.
```
Comment (seldridge) [inline unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp:675]: Nit: Please include a direct link tot he GitHub issue. Also, please rewrite this LLM-generated comment.

File: lib/Dialect/OM/Evaluator/Evaluator.cpp [hunk 4]
```diff
@@ -380,18 +391,48 @@ circt::om::Evaluator::instantiate(
...
+                      << " nodes this pass\n");
+
+    // If nothing became fully evaluated in this pass, we have a cycle
+    if (evaluatedThisPass == 0 && !nextWorklist.empty()) {
+      return cls.emitError()
+             << "cycle detected: " << nextWorklist.size()
+             << " values remain partially evaluated after full pass with no "
+                "progress (total fully evaluated: "
+             << fullyEvaluatedCount << ")";
+    }
```
Comment (seldridge) [inline lib/Dialect/OM/Evaluator/Evaluator.cpp:431]: Nit:


```suggestion
    if (evaluatedThisPass == 0 && !nextWorklist.empty())
      return cls.emitError()
             << "cycle detected: " << nextWorklist.size()
             << " values remain partially evaluated after full pass with no "
                "progress (total fully evaluated: "
             << fullyEvaluatedCount << ")";
```

File: lib/Dialect/OM/Evaluator/Evaluator.cpp [hunk 5]
```diff
@@ -70,32 +70,38 @@ FailureOr<evaluator::EvaluatorValuePtr>
...
+          })
+          .Case([&](circt::om::StringType type) {
+            evaluator::EvaluatorValuePtr result =
+                evaluator::AttributeValue::get(type, loc);
+            return success(result);
+          })
+          .Default([&](auto type) { return failure(); });
+
+  if (succeeded(result))
+    attachCounter(result.value());
```
Comment (seldridge) [inline lib/Dialect/OM/Evaluator/Evaluator.cpp:102]: Given the checking in `attachCounter`, can this blindly call `attachCounter(result.value())`? I guess not given that the return type is `FailureOr<...>`? `result.value()` must then auto-unpack the `FailureOr` for you?

File: lib/Dialect/OM/Evaluator/Evaluator.cpp [hunk 6]
```diff
@@ -329,6 +338,7 @@ circt::om::Evaluator::evaluateObjectInstance(StringAttr className,
   // If it's external call, just allocate new ObjectValue.
   evaluator::EvaluatorValuePtr result =
       std::make_shared<evaluator::ObjectValue>(cls, fields, loc);
+  // Note: Object is already fully evaluated when created with fields
```
Comment (seldridge) [inline lib/Dialect/OM/Evaluator/Evaluator.cpp:341]: An assert would be better than an LLM comment. 😉

File: lib/Dialect/OM/Evaluator/Evaluator.cpp [hunk 7]
```diff
@@ -380,18 +391,48 @@ circt::om::Evaluator::instantiate(
...
   // unless there is a partially evaluated value.
   LLVM_DEBUG(dbgs() << "worklist:\n");
-  while (!worklist.empty()) {
-    auto [value, args] = worklist.front();
-    worklist.pop();
 
-    auto result = evaluateValue(value, args, loc);
+  // Use two-worklist approach: process all items from current worklist,
+  // and if at least one becomes fully evaluated, swap and continue.
+  // If a full pass completes with no progress, we have a cycle.
```
Comment (seldridge) [inline lib/Dialect/OM/Evaluator/Evaluator.cpp:397]: Nit: please word-wrap this.

File: lib/Dialect/OM/Evaluator/Evaluator.cpp [hunk 8]
```diff
@@ -380,18 +391,48 @@ circt::om::Evaluator::instantiate(
...
+  while (!worklist.empty()) {
+    uint64_t countBeforePass = fullyEvaluatedCount;
+    LLVM_DEBUG(dbgs() << "- processing " << worklist.size()
+                      << " items (fully evaluated count: "
+                      << fullyEvaluatedCount << ")\n");
+
+    // Process all items in the current worklist
```
Comment (seldridge) [inline lib/Dialect/OM/Evaluator/Evaluator.cpp:404]: Extreme nit throughout: end full comment sentences with a period. (I need to put this in the AGENTS.md...)

File: lib/Dialect/OM/Evaluator/Evaluator.cpp [hunk 9]
```diff
@@ -1045,8 +1089,10 @@ circt::om::Evaluator::createUnknownValue(Type type, Location loc) {
           });
 
   // Mark the result as unknown if successful
-  if (succeeded(result))
+  if (succeeded(result)) {
+    attachCounter(result.value());
     result->get()->markUnknown();
+  }
```
Comment (seldridge) [inline lib/Dialect/OM/Evaluator/Evaluator.cpp:1095]: `markUnknown` will mark it fully evaluated. Hence, is there any benefit in attaching a counter here?


```suggestion
  if (succeeded(result))
    result->get()->markUnknown();
```

I also see this throughout where values have a counter attached and are then marked unknown. Is this necessary?

File: unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp [hunk 10]
```diff
@@ -669,6 +670,51 @@ om.class @ReferenceEachOther() -> (field: !ty){
...
+  ASSERT_TRUE(succeeded(result));
+
+  // Verify the result is correct (false since "A" != "B")
+  auto fieldValue = llvm::cast<evaluator::ObjectValue>(result.value().get())
+                        ->getField("test")
+                        .value();
+  auto boolValue = llvm::cast<evaluator::AttributeValue>(fieldValue.get())
+                       ->getAs<BoolAttr>();
+  ASSERT_FALSE(boolValue.getValue());
+}
```
Comment (seldridge) [inline unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp:716]: Very happy to see this working. Nice!

**Review by seldridge — COMMENTED** [review]
I have a couple of questions. This looks great, though. The two worklist approach makes a lot of sense and simplifies the cycle detection.

File: unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp (hunk 3 above)
Comment (uenoku) [reply unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp:675]: Is there a policy for preferring a direct link over issue number? I don't have a strong opinion but certainly I've used both #<issue_number> and URL without much consideration. Certainly LLVM also doesn't have a policy for that, can you add to CIRCT coding guideine? 

https://github.com/llvm/circt/blob/babde3dae9e13231c9c5e608e59fa0b9c262e8da/test/Dialect/FIRRTL/legacy-wiring.mlir#L212-L213
https://github.com/llvm/llvm-project/blob/5892e34a96131821256f89c0555ba68c23c91dbe/mlir/test/Analysis/test-match-reduction.mlir#L118

Comment (seldridge) [reply unittests/Dialect/OM/Evaluator/EvaluatorTests.cpp:675]: Sure. I can do that.

There's a significant trend towards full links, but both are used:

```
# grep  -r "\(;\|//\).*#[0-9]\+" ../test  | grep -v "\(CHECK\|expected\|CONN\)" | wc -l
      55
# grep  -r "https://github.com/llvm/circt/issues" ../test | wc -l
     237
```

**Review by seldridge — APPROVED** [review]

File: lib/Dialect/OM/Evaluator/Evaluator.cpp (hunk 5 above)
Comment (uenoku) [reply lib/Dialect/OM/Evaluator/Evaluator.cpp:102]: I think result.value() causes assertion failure for FailureOr::failuare(= std::nullopt), so we need to add a guard for this.

File: lib/Dialect/OM/Evaluator/Evaluator.cpp (hunk 9 above)
Comment (uenoku) [reply lib/Dialect/OM/Evaluator/Evaluator.cpp]: Thanks, I agree it's safe to ignore these from counters.
