### PR TITLE
[ETC] Don't erase operations used by dead module instances

### LINKED ISSUE #5356: [ETC] Crash with null operand in instnace
```
hw.module.extern private @Baz(%a: i1) -> (b: i1)  
  hw.module @SomeExtracted(%clock: i1, %in: i1) -> (out0: i1) {
    %and = comb.and %in, %clock: i1
    %baz.dead = hw.instance "baz" @Baz(a: %and: i1) -> (b: i1)
    sv.always posedge %clock {
      sv.cover %and, immediate
    }
    hw.output %in: i1
  }
```
ETC produces the following error:
```
test.mlir:4:17: error: null operand found
    %baz.dead = hw.instance "baz" @Baz(a: %and: i1) -> (b: i1)
                ^
test.mlir:4:17: note: see current operation: %0 = "hw.instance"(<<NULL VALUE>>) {argNames = ["a"], instanceName = "baz", moduleName = @Baz, parameters = [], resultNames = ["b"]} : (<<NULL TYPE>>) -> i1
```
`%and` is mistakenly deleted since `%and` is used by test code and dead external module.

### PR DESCRIPTION
**Pull request by uenoku**
Fix #5356. There is an edge case that ETC wrongly erase an extracted operation which is still used by (dead) module instances. This issue can be fixed by appropriately updating `opsToErase` based on `opsAiive`. `inlineInputOnly` is reordered since it depends on `opsToErase`.

### CODE REVIEW

File: lib/Dialect/SV/Transforms/SVExtractTestCode.cpp [hunk 1]
```diff
@@ -712,10 +708,21 @@ void SVExtractTestCodeImplPass::runOnOperation() {
...
       // Walk the module and add dead operations to `opsToErase`.
       op.walk([&](Operation *operation) {
-        if (&op != operation && !opsAlive.count(operation))
+        // Skip the module itself.
+        if (&op == operation)
+          return;
+
+        // Update `opsToErase`.
+        if (opsAlive.count(operation))
+          opsToErase.erase(operation);
```
Comment (uenoku) [inline lib/Dialect/SV/Transforms/SVExtractTestCode.cpp:717]: Note that opsToErase is `SmallPtrSetImpl` so it won't cause an issue like fixed by https://github.com/llvm/circt/pull/5353

**Comment by uenoku** [comment]
I'm going to merge this to unblock release process. A post-commit is welcomed!

**Comment by mikeurbach** [comment]
Awesome, thanks for the quick fix, it looks good to me. Dealing with these extracted instances has always had annoying corners like this, so thanks for adding a test as well to cover it.
