### PR TITLE
[FIRRTL] Rework internal paths array, cover all ports, maintain.

### LINKED ISSUE #5859: [FIRRTL] internalPaths crash
Input:
```
firrtl.circuit "Test" {
  firrtl.extmodule @GCTDataTap(out probe: !firrtl.rwprobe<uint<5>>, out baz_qux: !firrtl.probe<uint<1>>, out baz_quz: !firrtl.probe<uint<1>>) attributes {defname = "BlackBox", internalPaths = ["baz.qux", "baz.quz"]}
  firrtl.module @Test() {
    %0:3 = firrtl.instance inst @GCTDataTap(out probe: !firrtl.rwprobe<uint<5>>, out baz_qux: !firrtl.probe<uint<1>>, out baz_quz: !firrtl.probe<uint<1>>)
  }
}
```

This is reachable from an input that already has a probe port and more are inserted using grand central taps.
"internalPaths" should be reworked to support having paths for some (use ABI) and not others.

This crashes in LowerXMR but really the IR model is wrong.

### PR DESCRIPTION
**Pull request by dtzSiFive**
We need to support having paths for some ref-type ports but not others (ABI + GCT's internalPath mechanism) so change to have entry per port, with empty entries for non-ref and ref ports that should use ABI.

Add verifier for internalPaths, drop entirely if all entries are empty.

Fixes #5859 .

### CODE REVIEW

**Comment by dtzSiFive** [comment]
LowerTypes (and code that changes signatures itself/not using utility methods) can break the invariant, fix coming.

File: lib/Dialect/FIRRTL/FIRRTLOps.cpp [hunk 1]
```diff
@@ -666,11 +715,13 @@ void FModuleOp::insertPorts(ArrayRef<std::pair<unsigned, PortInfo>> ports) {
...
 
 void FExtModuleOp::insertPorts(ArrayRef<std::pair<unsigned, PortInfo>> ports) {
-  ::insertPorts(cast<FModuleLike>((Operation *)*this), ports);
+  ::insertPorts(cast<FModuleLike>((Operation *)*this), ports,
+                /*supportsInternalPaths=*/true);
 }
 
 void FIntModuleOp::insertPorts(ArrayRef<std::pair<unsigned, PortInfo>> ports) {
-  ::insertPorts(cast<FModuleLike>((Operation *)*this), ports);
+  ::insertPorts(cast<FModuleLike>((Operation *)*this), ports,
```
Comment (prithayan) [inline lib/Dialect/FIRRTL/FIRRTLOps.cpp:723]: Interesting, even internal modules can have RefType ports.

**Review by prithayan — APPROVED** [review]
Thanks for explicitly specifying the size of the internal paths array and adding the verifier. It was confusing.
