### PR TITLE
[FIRRTL][LowerToHW] Use always instead of always_ff

### LINKED ISSUE #1707: `always_ff` LoweringOption isn't correct
Per @youngar 's comment in [this PR](https://github.com/llvm/circt/pull/1684):

> We [originally disabled](https://github.com/llvm/circt/pull/1310) always_ff generation because the way we were using it was illegal in some tools: you can't drive a value in both an initial block and an always_ff block. At the time I thought it might be a badly behaving tool, but it turns out this is the correct way to interpret the spec. This is a really unfortunate limitation, we might be able to get around it by changing how initialization works.

> I don't think we have a solid plan of action yet. I'm a little hesitant to turn on always_ff when we know the generated verilog is broken. I could enable the always_ff flag but only generate regular always statements when lowering from FIRRTL.

This isn't correct - the IR should have well defined semantics and be lowerable to different things for different tools - right now it sounds like we're using LoweringOptions because our previous lowering was incorrect.

It sounds like we're generating `sv.alwaysff` in invalid cases, and that lowering should be changed to make `sv.always` instead.  Given that change, we can rip out the LoweringOption.

### PR DESCRIPTION
**Pull request by uenoku**
This PR replaces `always_ff` with `always` at lower-to-hw to fix the invalid usages of always_ff with initialization blocks.
This PR also removes `alwaysFF` option in firtool😀

Will close #1707

### CODE REVIEW

File: lib/Conversion/FIRRTLToHW/LowerToHW.cpp [hunk 1]
```diff
@@ -1650,42 +1650,79 @@ Value FIRRTLLowering::getReadInOutOp(Value v) {
...
+          body();
+      };
+
+      if (resetStyle == ::ResetType::AsyncReset) {
+        sv::EventControl events[] = {clockEdge, resetEdge};
+        Value clocks[] = {clock, reset};
+
+        alwaysOp = builder.create<sv::AlwaysOp>(events, clocks, [&] {
+          // If reset is asnyc and negative-edge, then flip the reset value.
+          if (resetEdge == sv::EventControl::AtNegEdge) {
```
Comment (uenoku) [inline lib/Conversion/FIRRTLToHW/LowerToHW.cpp:1708]: I'm not sure we actually handle this case(async reset + negative edge). Is there any example in firrtl?

File: test/Conversion/FIRRTLToHW/lower-to-hw.mlir [hunk 2]
```diff
@@ -727,9 +727,11 @@ firrtl.circuit "Simple"   attributes {annotations = [{class =
...
     // CHECK-NEXT: %reg2 = sv.reg : !hw.inout<i32>
     // CHECK-NEXT: %1 = sv.read_inout %reg2 : !hw.inout<i32>
-    // CHECK-NEXT: sv.alwaysff(posedge %clock) {
-    // CHECK-NEXT: }(syncreset : posedge %reset) {
-    // CHECK-NEXT:    sv.passign %reg2, %c0_i32 : i32
+    // CHECK-NEXT: sv.always posedge %clock  {
+    // CHECK-NEXT:   sv.if %reset  {
+    // CHECK-NEXT:     sv.passign %reg2, %c0_i32 : i32
+    // CHECK-NEXT:   } else  {
+    // CHECK-NEXT:   }
```
Comment (seldridge) [inline test/Conversion/FIRRTLToHW/lower-to-hw.mlir:734]: It would be better if the else block was only constructed if needed.

**Review by seldridge — COMMENTED** [review]
Looking good. Can you modify this to not construct the else block unless it's needed?

File: test/Conversion/FIRRTLToHW/lower-to-hw.mlir (hunk 2 above)
Comment (uenoku) [reply test/Conversion/FIRRTLToHW/lower-to-hw.mlir:734]: I'm currently creating IfOp with `elseRegion` because `elseRegion` might be used in the feature. 
This is MLIR problem but I'm not sure how to create a region on demand. What is a conventional way to create a region on demand?

File: lib/Conversion/FIRRTLToHW/LowerToHW.cpp [hunk 3]
```diff
@@ -1650,42 +1649,78 @@ Value FIRRTLLowering::getReadInOutOp(Value v) {
...
+      runWithInsertionPointAtEndOfBlock(body, alwaysOp.body());
+    }
 
     // Move the earlier always block(s) down to where the last would have been
     // inserted.  This ensures that any values used by the always blocks are
     // defined ahead of the uses, which leads to better generated Verilog.
-    op->moveBefore(builder.getInsertionBlock(), builder.getInsertionPoint());
+    alwaysOp->moveBefore(builder.getInsertionBlock(),
+                         builder.getInsertionPoint());
   } else {
```
Comment (seldridge) [inline lib/Conversion/FIRRTLToHW/LowerToHW.cpp:1675]: Is there a way to rework this to share the code for the always block always exists.  E.g., can this do something like:

```c++
if (!alwaysOp) {
  /* Generate empty always block. */
  alwaysOp = /* ... */;
  insideIfOp = /* ... */;
}

if (reset) {
  runWithInsertionPointAtEndOfBlock(resetBody, /* ... */);
  runWithInsertionPointAtEndOfBlock(body, /* ... */);
} else {
  runWithInsertionPointAtEndOfBlock(body, /* ... */);
}
```

File: lib/Conversion/FIRRTLToHW/LowerToHW.cpp (hunk 1 above)
Comment (seldridge) [reply lib/Conversion/FIRRTLToHW/LowerToHW.cpp:1706]: As far as I know, FIRRTL cannot hit this. It will always try to lower to posedge reset.  You may want to change this to use an `llvm_unreachable()` as this is intended to _never_ be seen from FIRRTL.

File: test/Conversion/FIRRTLToHW/lower-to-hw.mlir (hunk 2 above)
Comment (seldridge) [reply test/Conversion/FIRRTLToHW/lower-to-hw.mlir:734]: I think this is fine to leave it as is, then. 👍

**Review by seldridge — APPROVED** [review]
Looks great.

I included a suggestion that may work to improve the `if`/`else` nesting where the always block is built or added to.  This change in this PR makes that member function a bit harder to follow.

File: lib/Conversion/FIRRTLToHW/LowerToHW.cpp [hunk 4]
```diff
@@ -1650,42 +1649,78 @@ Value FIRRTLLowering::getReadInOutOp(Value v) {
...
-  if (op) {
-    runWithInsertionPointAtEndOfBlock(body, op.bodyBlk());
-    runWithInsertionPointAtEndOfBlock(resetBody, op.resetBlk());
+void FIRRTLLowering::addToAlwaysBlock(sv::EventControl clockEdge, Value clock,
+                                      ::ResetType resetStyle,
+                                      sv::EventControl resetEdge, Value reset,
+                                      std::function<void(void)> body,
+                                      std::function<void(void)> resetBody) {
+  auto &op = alwaysBlocks[std::make_tuple(builder.getBlock(), clockEdge, clock,
+                                          resetStyle, resetEdge, reset)];
```
[the remark this answers is not in the document]
Comment (uenoku) [reply lib/Conversion/FIRRTLToHW/LowerToHW.cpp]: It worked. Thanks!

File: lib/Conversion/ExportVerilog/ExportVerilog.cpp [hunk 5]
```diff
@@ -2972,9 +2972,7 @@ LogicalResult StmtEmitter::visitSV(AlwaysFFOp op) {
   SmallPtrSet<Operation *, 8> ops;
   ops.insert(op);
 
-  StringRef opString = "always";
-  if (state.options.useAlwaysFF)
-    opString = "always_ff";
+  StringRef opString = "always_ff";
 
   indent() << opString << " @(" << stringifyEventControl(op.clockEdge()) << " ";
```
Comment (lattner) [inline lib/Conversion/ExportVerilog/ExportVerilog.cpp:2977]: nice, you can further simplify this to just use `indent() << "always_ff" << `...

**Review by lattner — APPROVED** [review]
Thank you for tackling this!

**Review by darthscsi — APPROVED** [review]
Thanks!
