### PR TITLE
[FIRRTL] Error on Annotations that Do Not Apply

### LINKED ISSUE #1013: Annotation Verification
FIRRTL Annotations that are parsed into FIRRTL Dialect should be verified in two ways:

1. Any annotations which do not apply to the circuit should be a disable-able error.
2. Annotations which are applied and include subfield/subindex sub-targets should be validated that they point to legal things.

(1) is important because it helps us to know that we're pulling in the right annotation file, that the annotation file isn't malformed, and that our annotation parsing works. By default, weird-looking annotations are promoted to circuit target annotations. This should start erroring so that we know what custom annotations we need to worry about.

(2) Matters for things like lowering. FIRRTL allows for field names to be numeric. This can result in annotations incorrectly aliasing to the wrong thing if they aren't verified first. Consider the following where `a[0]` doesn't exist and the lowering step will incorrectly apply this to a new wire `a_0`:

```scala
circuit Baz: %[[{"a":null,"target":"~Baz|Baz>a[0]"}]]
  module Baz:
    wire a: {0: UInt<1>}
```

There are more pedestrian cases of just incorrect annotations pointing to things that don't exist:

```scala
circuit Baz: %[[{"a":null,"target":"~Baz|Baz>a.b"}]]
  module Baz:
    wire a: UInt<1>
```

### PR DESCRIPTION
**Pull request by seldridge**
Change the FIRRTL parser to error if any Annotations are unapplied to
the circuit.  Put differently, this will error if any Target in an
Annotation (or a generated Target from Annotation scattering) points at
something which does not exist in the circuit.

Residual Annotations indicate either a user problem like inconsistent
FIRRTL and Annotation files or some problem with scattering logic or the
parser itself.  E.g., you can hit this if you have busted scattering
code (that creates targets that do not exist) or for cases where
non-local Annotations get through scattering logic.  This is a situation
that needs to be addressed and continuing compilation may result in
extremely tedious errors due to the compiler effectively dropping
Annotation information which is assumed to be critical to control
compilation in a way the user wants.

Together with a894ad8c and a08f15ca this should cause all unapplied
Annotations to produce parse-time errors.

Fixes #1013.  #1280 and #1327 do a great job of taking care of malformed Annotations where a field/index doesn't exist or the circuit is invalid.  This takes care of the remaining situations and catches anything that gets into the parser with invalid syntax (e.g., with hypothetical third-party Annotation scattering code or presently unchecked scattered annotations that have non-local targets).

~_Note: I am not happy about this implementation, but wanted to get something going._~

~This is currently implemented as exfiltrating the discovered module namespace into a `SmallVector<StringAttr>`, converting that to a `StringSet<>`, and then asserting that each key (a target) in the Annotation map exists in the set.  This set can be very large and the majority of it is thrown away.  Also, this is using `StringAttr`s (which should be uniqued and pretty cheap?), but it seems like switching to `StringRef`s pointing at things that will exist after the modules are parsed is better.  This is all done using `parallelTransformReduce` so that it's actually safe.~

~A better formulation would be to exfiltrate _annotations that do apply_ and then diffing this with the Annotation map.  The Annotation map cannot be mutated directly, but each parsing thread could append to an "applied annotations" data structure passed into `parseModuleBody` and its child calls.  (I initially didn't see a way to mutate the Annotation map and thought the `StringSet<>` approach was necessary...)~

*This PR was updated to use the better approach of recording what targets were found and applied by `getAnnotations` and `getSplitAnnotations`.  No massive set of all names is being built up anymore.*

### CODE REVIEW

File: lib/Dialect/FIRRTL/Import/FIRParser.cpp [hunk 1]
```diff
@@ -3506,24 +3531,66 @@ FIRCircuitParser::parseCircuit(const llvm::MemoryBuffer *annotationsBuf) {
...
   // go ahead and parse all their bodies.  This can be done in parallel.
   if (getContext()->isMultithreadingEnabled()) {
     mlir::ParallelDiagnosticHandler diagHandler(getContext());
     std::atomic<bool> anyFailed{false};
-    llvm::parallelForEachN(0, deferredModules.size(), [&](size_t index) {
-      diagHandler.setOrderIDForThread(index);
-      if (parseModuleBody(deferredModules[index]))
-        anyFailed = true;
-    });
+    std::atomic<unsigned> threadID{0};
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Import/FIRParser.cpp:3550]: Random FYI, but MLIR now has mlir/IR/Threading.h which we should adopt to clean up our threading stuff.  IT handles the diagnostics switch and the "if mlir paralllelism enabled" thing.  It doesn't have reduce though, it would be great to upstream that if you need it.

File: lib/Dialect/FIRRTL/Import/FIRParser.cpp [hunk 2]
```diff
@@ -3244,6 +3252,7 @@ ParseResult FIRCircuitParser::parseModule(CircuitOp circuit,
     return failure();
 
   auto moduleTarget = (circuitTarget + "|" + name.getValue()).str();
+  targets.push_back(StringAttr::get(getContext(), moduleTarget));
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Import/FIRParser.cpp:3255]: if I understand this correctly, this is proactively building up all the targets that get parsed, even if they don't get referenced.  This is going to build a huge set which is almost never used.

Can you add this to `FIRParser::getAnnotations` somehow?  It tries pretty hard to only triggers if there is actually an annotation.  You could make it add to your set whenever there is a hit.  That would ignore all the targets that never have an annotation on them.

File: lib/Dialect/FIRRTL/Import/FIRParser.cpp [hunk 3]
```diff
@@ -3506,24 +3531,66 @@ FIRCircuitParser::parseCircuit(const llvm::MemoryBuffer *annotationsBuf) {
...
   } else {
     for (DeferredModuleToParse &deferredModule : deferredModules) {
       if (parseModuleBody(deferredModule))
         return failure();
+      targets = reduceTargets(targets, deferredModule.targets);
+    }
+  }
+
+  // Verify that all annotations map to valid targets.  Error if any do not.
+  llvm::StringSet<> targetsSet;
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Import/FIRParser.cpp:3571]: BTW, StringSet takes an Allocator argument.  You might see if it is worth using a BumpPointerAllocator (if StringSet survives)

File: lib/Dialect/FIRRTL/Import/FIRParser.cpp (hunk 1 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/Import/FIRParser.cpp]: This was perhaps too cute.  I changed this to just do the merge in a loop after this.  I do agree that porting the `parallelTransformReduce` method to the new threading API would be great (and it would be good for me to actually do some upstream MLIR work...).  That method is used in `LowerToHW`.

Comment (seldridge) [reply lib/Dialect/FIRRTL/Import/FIRParser.cpp]: I can take care of changing to `mlir/IR/Threading.h` in a separate, unrelated commit.

File: lib/Dialect/FIRRTL/Import/FIRParser.cpp (hunk 2 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/Import/FIRParser.cpp]: I changed this towards that direction.  `StringSet`s are passed around where needed and these are mutated by any child calls to `getAnnotations` or `getSplitAnnotations`. 

(I had started off wanting to remove annotations from the map in `getAnnotations`, but that obviously wouldn't work due to the parallelism.  I then got sidetracked with the janky original approach of recording all names.  I had incorrectly thought that having to add parameters to a lot of methods was a bad idea.  That was ill-founded.)

Thanks for the great suggestion.  This is a way better implementation now.

File: lib/Dialect/FIRRTL/Import/FIRParser.cpp (hunk 3 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/Import/FIRParser.cpp]: `StringSet` did survive and I switched to using a `BumpPointerAllocator`.  Due to the other cases being caught in #1280 and #1327, `StringSet` works.  If, however, we want to unify the "Annotation does not apply" checks to all use the same infrastructure, this would need to change to something like a `SmallSet<StringRef, llvm::BitVector>` to track both which target was found _and which of its Annotations were applied_.  As it stands @hanchenye's approach can give better error messages than this alternative because he can point to a specific circuit location instead of a generic `~Foo|Bar>baz[0]` did not exist.

What would be a good way to test the choice of allocator?  See how the performance scales for the two approaches as annotations increase?  I may need to see if @drom can add a flag to generate large circuits where _everything_ is annotated. :smile:

**Comment by seldridge** [comment]
Ugh... this is compiling on my local clang 12, but apparently clang 10 doesn't like the `std::move` of the `StringSet<BumpPtrAllocator>` .  I can take a look tomorrow.

**Comment by seldridge** [comment]
Thanks to @fabianschuiki for helping track this down.  (The error messages are actually pretty good.  I should read them.)  

1) `std::vector` is pessimistic and requires a copy constructor.  (Apparently only for glibc and not for MacOS / BSD libc?)
2) `StringSet` has a copy constructor.  
3) `BumpPtrAllocator` has an implicitly deleted copy constructor because it has a move constructor.  

Therefore, you can wind up with problems when using a `std::vector` that involves `StringSet<BumpPtrAllocator>`, but not with a `StringSet<>`.  🤷‍♀️ 

This can all be rectified by actually following the LLVM Programmer's Manual and using `SmallVector<A, 0>`. 😌 I.e., I think this is exactly item (1) below:

Screen Shot 2021-07-19 at 15 49 56

File: lib/Dialect/FIRRTL/Import/FIRParser.cpp [hunk 4]
```diff
@@ -292,14 +303,16 @@ struct FIRParser {
                    ArrayRef<std::pair<StringAttr, Type>> ports);
 
   /// Return the set of annotations for a given Target.
-  ArrayAttr getAnnotations(ArrayRef<Twine> targets, SMLoc loc, Type type);
+  ArrayAttr getAnnotations(ArrayRef<Twine> targets, SMLoc loc,
+                           TargetSet &targetSet, Type type);
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Import/FIRParser.cpp:307]: Can you just use `getConstants().targetSet` instead of passing in `targetSet` as a parameter?

Comment (lattner) [reply lib/Dialect/FIRRTL/Import/FIRParser.cpp:307]: similar question for other methods below, we shouldn't need to explicitly thread this down the stack.

Comment (lattner) [reply lib/Dialect/FIRRTL/Import/FIRParser.cpp:307]: Wait wait wait, this is actually really subtle, because you are mutating local ones and then merging them in between.  We need to make this more explicit.  

Please add the set to `FIRModuleContext` (so it doesn't get passed down the stack through all the methods) and name it something like "moduleAnnotationTargetsSeen" or something like that.  The top level can then merge these into the per-circuit set.  Making it explicit that "moduleAnnotationTargetsSeen" is different than the per-circuit set seems really important.

Comment (seldridge) [reply lib/Dialect/FIRRTL/Import/FIRParser.cpp:307]: Bloody hell. How did I miss `FIRModuleContext`. 🤦  I didn't see that there was per-module context which is exactly what I needed.

Yeah, `getConstants().targetSet` won't work unless we lock on access to `targetSet`. (I don't think multiple threads can just mutate that safely?)

Will update...

Comment (seldridge) [reply lib/Dialect/FIRRTL/Import/FIRParser.cpp:307]: Fixed in the rebase. I can never seem to keep track of which mutable state is available where in the parser... (Even though I was doing exploiting `FIRModuleContext` with the initial naive patch. 🤷‍♀️ )

Third time's the charm. One more quick look, please, @lattner.

File: lib/Dialect/FIRRTL/Import/FIRParser.cpp [hunk 5]
```diff
@@ -3277,9 +3311,10 @@ ParseResult FIRCircuitParser::parseModule(CircuitOp circuit,
 
     // Parse the body of this module after all prototypes have been parsed. This
     // allows us to handle forward references correctly.
-
+    TargetSet targetSet;
     deferredModules.push_back({moduleOp, portLocs, getLexer().getCursor(),
-                               std::move(moduleTarget), indent});
+                               std::move(moduleTarget), indent,
+                               std::move(targetSet)});
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Import/FIRParser.cpp:3317]: I think you can pass `TargetSet()` directly instead of `std::move(targetSet)`

**Review by lattner — APPROVED** [review]
Looks great, thank you!

File: lib/Dialect/FIRRTL/Import/FIRParser.cpp (hunk 5 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/Import/FIRParser.cpp:3317]: I can if I don't use the `BumpPtrAllocator`, but if I do, it's implicitly deleted copy constructor causes problems 😬:

```
In file included from ../lib/Dialect/FIRRTL/Import/FIRParser.cpp:14:
In file included from ../lib/Dialect/FIRRTL/Import/FIRAnnotations.h:17:
../llvm/llvm/include/llvm/ADT/StringMap.h:139:9: error: call to implicitly-deleted copy constructor of 'llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096, 4096, 128>'
        Allocator(RHS.Allocator) {
        ^         ~~~~~~~~~~~~~
../llvm/mlir/include/mlir/Support/LLVM.h:60:39: note: in instantiation of member function 'llvm::StringMap<llvm::NoneType, llvm::BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096, 4096, 128>>::StringMap' requested here
template <typename AllocatorTy> class StringSet;
                                      ^
../llvm/llvm/include/llvm/Support/Allocator.h:88:3: note: copy constructor is implicitly deleted because 'BumpPtrAllocatorImpl<llvm::MallocAllocator, 4096, 4096, 128>' has a user-declared move constructor
  BumpPtrAllocatorImpl(BumpPtrAllocatorImpl &&Old)
  ^
1 error generated.
```

I'll punt on this change for now.

Comment (lattner) [reply lib/Dialect/FIRRTL/Import/FIRParser.cpp:3317]: Sounds good.  It took me like 42 tries, but I was able to get it to go in b6510fcd.  *shakes head at C++*
