### PR TITLE
[FIRRTL][InferWidths] Honor upper bounds on AttachOp

### LINKED ISSUE #4786: [FIRRTL] InferWidths infers width for Analog that's unsatisifiable, should error (?)
The FIRRTL specification says:

> As with integer types, an analog type can represent a multi-bit signal. When analog signals are not given a concrete width, their widths are inferred according to a highly restrictive width inference rule, which requires that the widths of all arguments to a given attach operation be identical.

The following example should be an error (cannot infer a width to make the Analog the same width in all attach's), but instead an inconsistent width is used resulting in an error later in the pipeline:

```
$ <analog-widths.fir 1>&2 | ./build/bin/firtool  --mlir-print-ir-after-failure -format=fir -debug-only=infer-widths --mlir-print-ir-after=firrtl-infer-widths
circuit Widths : 
  module Widths :
    input a : Analog
    output b : Analog<2>
    output c : Analog<1>
    attach(a, b)
    attach(a, c)


===----- Mapping ops to constraint exprs -----===

Expr var1618 for <block argument> of type '!firrtl.analog' at index: 0
Expr 2 for <block argument> of type '!firrtl.analog<2>' at index: 1
Expr 1 for <block argument> of type '!firrtl.analog<1>' at index: 2
Constrained var1618 >= *2
Constrained var1618 >= max(*2, 1)

===----- Constraints -----===

- var1618 >= max(*2, 1)

===----- Checking for unbreakable loops -----===

- Checking var1618 >= max(*2, 1)
      - Visited 2: x >= 2
    - Visited *2: x >= 2
    - Visited 1: x >= 1
  - Visited max(*2, 1): x >= 2
  = Breakable since x >= 2 satisfiable

===----- Solving constraints -----===

- Solving var1618 >= max(*2, 1)
  - Solving max(*2, 1)
    - Solving *2
    = Solved *2 = 2 (unique)
  = Solved max(*2, 1) = 2 (unique)
  - Solved var1618 = 2 (unique)

===----- Update types -----===

Update <block argument> of type '!firrtl.analog' at index: 0 to !firrtl.analog<2>
<stdin>:7:5: error: 'sv.assign' op failed to verify that type should be element of inout type
    attach(a, c)
    ^
<stdin>:7:5: note: see current operation: "sv.assign"(%arg0, %1) : (!hw.inout<i2>, i1) -> ()
// -----// IR Dump After LowerFIRRTLToHW Failed (lower-firrtl-to-hw) //----- //
#loc = loc("<stdin>":3:11)
#loc1 = loc("<stdin>":4:12)
#loc2 = loc("<stdin>":5:12)
"builtin.module"() ({
  "hw.module"() ({
  ^bb0(%arg0: !hw.inout<i2>, %arg1: !hw.inout<i2>, %arg2: !hw.inout<i1>):
    %0 = "sv.read_inout"(%arg1) : (!hw.inout<i2>) -> i2
    %1 = "sv.read_inout"(%arg2) : (!hw.inout<i1>) -> i1
    %2 = "sv.read_inout"(%arg0) : (!hw.inout<i2>) -> i2
    "sv.ifdef"() ({
      "sv.assign"(%arg0, %1) : (!hw.inout<i2>, i1) -> ()
      "sv.assign"(%arg0, %0) : (!hw.inout<i2>, i2) -> ()
      "sv.assign"(%arg2, %2) : (!hw.inout<i1>, i2) -> ()
      "sv.assign"(%arg2, %0) : (!hw.inout<i1>, i2) -> ()
      "sv.assign"(%arg1, %2) : (!hw.inout<i2>, i2) -> ()
      "sv.assign"(%arg1, %1) : (!hw.inout<i2>, i1) -> ()
    }, {
      "sv.ifdef"() ({
        "sv.verbatim"() {format_string = "`error \22Verilator does not support alias and thus cannot arbitrarily connect bidirectional wires and ports\22", symbols = []} : () -> ()
      }, {
        "sv.alias"(%arg0, %arg2, %arg1) : (!hw.inout<i2>, !hw.inout<i1>, !hw.inout<i2>) -> ()
      }) {cond = #sv<macro.ident "verilator">} : () -> ()
    }) {cond = #sv<macro.ident "SYNTHESIS">} : () -> ()
    "hw.output"() : () -> ()
  }) {argLocs = [#loc, #loc1, #loc2], argNames = ["a", "b", "c"], arg_attrs = [{}, {}, {}], comment = "", function_type = (!hw.inout<i2>, !hw.inout<i2>, !hw.inout<i1>) -> (), parameters = [], res_attrs = [], resultLocs = [], resultNames = [], sym_name = "Widths"} : () -> ()
}) : () -> ()
```

I think this is due to this:

https://github.com/llvm/circt/blob/978bccc69d87037e880963c292f186661977525c/lib/Dialect/FIRRTL/Transforms/InferWidths.cpp#L1707-L1711

That is, looks like the constraints from the `Analog<2>` and `Analog<1>` being `>=` the (inferred) width of the `Analog` are not added to the solver.

### PR DESCRIPTION
**Pull request by fabianschuiki**
Fix an issue in `InferWidths` where analog values attached to each other would not produce proper errors if the widths are unsatisfiable. For example, the following is unsatisfiable but successfully infers to an incorrect width:

```
firrtl.module @AnalogWidths(
  in %a: !firrtl.analog,
  out %b: !firrtl.analog<2>,
  out %c: !firrtl.analog<1>
) {
  firrtl.attach %a, %b : !firrtl.analog, !firrtl.analog<2>
  firrtl.attach %a, %c : !firrtl.analog, !firrtl.analog<1>
}
```

The `AttachOp` imposes a `lhs >= rhs` *and* `lhs <= rhs` constraint, which is supposed to devolve into `lhs == rhs`. However, `InferWidths` ignores upper bound constraints like `expr <= 42` since the original Scala implementation used to violate upper bounds in obscure and wild ways (see #1088).

This commit adds an optional upper bound to variables which is checked after width inference. Specifically `AttachOp` is made to generate these upper bound constraints. Proper error messages on unsatisfiable widths should now be produced.

Fixes #4786.

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/InferWidths.cpp [hunk 1]
```diff
@@ -1701,18 +1690,37 @@ void InferenceMapping::constrainTypes(Value larger, Value smaller) {
...
                << "Constrained " << *largerVar << " >= " << *c << "\n");
+    return;
+  }
+
+  // If the smaller expr is a free variable but the larger one is not, create a
+  // `expr <= k` upper bound that we can verify once all lower bounds have been
+  // satisfied. Since we are always picking the smallest width to satisfy all
+  // `>=` constraints, any `<=` constraints have no effect on the solution
+  // besides indicating that a width is unsatisfiable.
+  if (auto smallerVar = dyn_cast<VarExpr>(smaller)) {
```
Comment (fabianschuiki) [inline lib/Dialect/FIRRTL/Transforms/InferWidths.cpp:1717]:
```suggestion
  if (auto *smallerVar = dyn_cast<VarExpr>(smaller)) {
```

File: lib/Dialect/FIRRTL/Transforms/InferWidths.cpp [hunk 2]
```diff
@@ -1701,18 +1690,37 @@ void InferenceMapping::constrainTypes(Value larger, Value smaller) {
...
   // Mimic the Scala implementation here by simply doing nothing if the larger
   // expr is not a free variable. Apparently there are many cases where
   // useless constraints can be added, e.g. on multiple well-known values. As
   // long as we don't want to do type checking itself here, but only width
   // inference, we should be fine ignoring expr we cannot constraint anyway.
+
+  // If the larger expr is a free variable, create a `expr >= x` constraint for
+  // it that we can try to satisfy with the smallest width.
   if (auto largerVar = dyn_cast<VarExpr>(larger)) {
     LLVM_ATTRIBUTE_UNUSED auto c = solver.addGeqConstraint(largerVar, smaller);
```
Comment (fabianschuiki) [inline lib/Dialect/FIRRTL/Transforms/InferWidths.cpp:1706]:
```suggestion
    LLVM_ATTRIBUTE_UNUSED auto *c = solver.addGeqConstraint(largerVar, smaller);
```

File: lib/Dialect/FIRRTL/Transforms/InferWidths.cpp [hunk 3]
```diff
@@ -1701,18 +1690,37 @@ void InferenceMapping::constrainTypes(Value larger, Value smaller) {
...
+  }
+
+  // If the smaller expr is a free variable but the larger one is not, create a
+  // `expr <= k` upper bound that we can verify once all lower bounds have been
+  // satisfied. Since we are always picking the smallest width to satisfy all
+  // `>=` constraints, any `<=` constraints have no effect on the solution
+  // besides indicating that a width is unsatisfiable.
+  if (auto smallerVar = dyn_cast<VarExpr>(smaller)) {
+    if (imposeUpperBounds) {
+      LLVM_ATTRIBUTE_UNUSED auto c =
```
Comment (fabianschuiki) [inline lib/Dialect/FIRRTL/Transforms/InferWidths.cpp:1719]:
```suggestion
      LLVM_ATTRIBUTE_UNUSED auto *c =
```

File: lib/Dialect/FIRRTL/Transforms/InferWidths.cpp [hunk 4]
```diff
@@ -284,38 +271,8 @@ void Expr::print(llvm::raw_ostream &os) const {
...
-
 } // namespace
 
-//===----------------------------------------------------------------------===//
-// GraphTraits on constraint expressions
-//===----------------------------------------------------------------------===//
-
-namespace llvm {
-template <>
-struct GraphTraits<Expr *> {
```
Comment (dtzSiFive) [inline lib/Dialect/FIRRTL/Transforms/InferWidths.cpp:305]: Aww, but makes sense :smile: .

File: lib/Dialect/FIRRTL/Transforms/InferWidths.cpp [hunk 5]
```diff
@@ -1701,18 +1690,37 @@ void InferenceMapping::constrainTypes(Value larger, Value smaller) {
...
     LLVM_DEBUG(llvm::dbgs()
                << "Constrained " << *largerVar << " >= " << *c << "\n");
+    return;
+  }
+
+  // If the smaller expr is a free variable but the larger one is not, create a
+  // `expr <= k` upper bound that we can verify once all lower bounds have been
+  // satisfied. Since we are always picking the smallest width to satisfy all
+  // `>=` constraints, any `<=` constraints have no effect on the solution
+  // besides indicating that a width is unsatisfiable.
```
Comment (dtzSiFive) [inline lib/Dialect/FIRRTL/Transforms/InferWidths.cpp:1716]: Love the comments, thanks! :+1:

File: test/Dialect/FIRRTL/infer-widths-errors.mlir [hunk 6]
```diff
@@ -121,3 +121,16 @@ firrtl.circuit "Foo"  {
...
 }
+
+// -----
+// Unsatisfiable widths through AttachOp on analog types should error.
+// https://github.com/llvm/circt/issues/4786
+firrtl.circuit "AnalogWidths" {
+  // expected-error @+1 {{uninferred width: port "a" cannot satisfy all width requirements}}
+  firrtl.module @AnalogWidths(in %a: !firrtl.analog, out %b: !firrtl.analog<2>, out %c: !firrtl.analog<1>) {
+    firrtl.attach %a, %b : !firrtl.analog, !firrtl.analog<2>
+    // expected-note @+2 {{width is constrained to be at least 2 here:}}
```
Comment (dtzSiFive) [inline test/Dialect/FIRRTL/infer-widths-errors.mlir:132]: Great diagnostics, thanks!! :rocket: 

FWIW can use `@below` for both of these, helpful to avoid having to count or just to not think about it :wink:.

**Review by dtzSiFive — APPROVED** [review]
LGTM, thanks! :+1:

File: test/Dialect/FIRRTL/infer-widths-errors.mlir (hunk 6 above)
Comment (fabianschuiki) [reply test/Dialect/FIRRTL/infer-widths-errors.mlir:132]: Sweet, did not know about `@below`! Thanks!

File: test/Dialect/FIRRTL/infer-widths-errors.mlir [hunk 7]
```diff
@@ -121,3 +121,16 @@ firrtl.circuit "Foo"  {
...
+    // expected-note @+1 {{width is constrained to be at most 1 here:}}
```
[the remark this answers is not in the document]
Comment (dtzSiFive) [reply test/Dialect/FIRRTL/infer-widths-errors.mlir]: Oh, sorry.  Don't move the expected comments-- they still need to be pointing at the 'attach'es.  "@below" just lets you stack them without counting and seems a little more readable than +/-1 ("@above").

Out of curiosity, why are both note diagnostics located on the second attach ("at most 1" seems from the first attach)? Not a big deal just curious.  Anyway if using `@below` both notes would go above that.  For convenience since touched this up locally while poking at it:

File: test/Dialect/FIRRTL/infer-widths-errors.mlir [hunk 8]
```diff
@@ -121,3 +121,16 @@ firrtl.circuit "Foo"  {
...
+// -----
+// Unsatisfiable widths through AttachOp on analog types should error.
+// https://github.com/llvm/circt/issues/4786
+firrtl.circuit "AnalogWidths" {
+  // expected-error @below {{uninferred width: port "a" cannot satisfy all width requirements}}
+  // expected-note @below {{width is constrained to be at least 2 here:}}
+  // expected-note @below {{width is constrained to be at most 1 here:}}
+  firrtl.module @AnalogWidths(in %a: !firrtl.analog, out %b: !firrtl.analog<2>, out %c: !firrtl.analog<1>) {
+    firrtl.attach %a, %b : !firrtl.analog, !firrtl.analog<2>
+    firrtl.attach %a, %c : !firrtl.analog, !firrtl.analog<1>
```
Comment (dtzSiFive) [inline test/Dialect/FIRRTL/infer-widths-errors.mlir:134]:
```suggestion
  firrtl.module @AnalogWidths(in %a: !firrtl.analog, out %b: !firrtl.analog<2>, out %c: !firrtl.analog<1>) {
    firrtl.attach %a, %b : !firrtl.analog, !firrtl.analog<2>
    // expected-note @below {{width is constrained to be at least 2 here:}}
    // expected-note @below {{width is constrained to be at most 1 here:}}
    firrtl.attach %a, %c : !firrtl.analog, !firrtl.analog<1>
```

File: test/Dialect/FIRRTL/infer-widths-errors.mlir (hunk 7 above)
[the remark this answers is not in the document]
Comment (fabianschuiki) [reply test/Dialect/FIRRTL/infer-widths-errors.mlir]: Haha I'm such an idiot. Thanks for clarifying :100:, and thanks for the fix :smile: !

[the remark this answers is not in the document]
Comment (fabianschuiki) [reply test/Dialect/FIRRTL/infer-widths-errors.mlir]: > Out of curiosity, why are both note diagnostics located on the second attach ("at most 1" seems from the first attach)?

That stems from a bit of a design smell in `InferWidths` at the moment: the expressions being created in the solver are deduplicated, which makes it hard to pinpoint the *exact* location of where a constraint comes from. There's a bit of hackery going on where the pass roughly keeps track of the locations associated with a constraint, but that doesn't always point to the interesting thing if two expressions deduplicate (which is quite common for constants like `2` in the above case).

Ideally we wouldn't have to build up an entire expression graph to do the width inference, doing it on the ops directly instead. But I haven't had a chance to look into that yet :cry:. We could also just stop deduplicating expressions to be more precise in diagnostics, but that likely also increases the memory footprint of the pass (because it roughly clones the FIRRTL IR into this expression graph).

**Review by darthscsi — APPROVED** [review]
