### PR TITLE
[LowerToHW] Fix reg init via verbatim ops

### LINKED ISSUE #2310: [SV] Spilling Out of Procedural Region can produce Xs with disallowLocalVariables
If `-lowering-options=disallowLocalVariables` is used to generate Verilog, you can create situations where registers are not randomized in the evaluation of the initial block.

Consider the following source FIRRTL:

```scala
circuit Foo:
  module Foo:
    input clock: Clock
    input d: UInt<1>
    output q: UInt<1>

    reg r: UInt<1>, clock

    r <= d
    q <= r
```

This has a register smaller than 32-bit and will result in a bit select off of a `RANDOM` verbatim expression.  This will eventually produce the following Verilog using `firtool -verilog -lowering-options=disallowLocalVariables`:

```verilog
module Foo(	// Foo.fir:2:10
  input  clock, d,
  output q);

  reg r;	// Foo.fir:7:5

  `ifndef SYNTHESIS	// Foo.fir:7:5
    reg [31:0] _T;	// Foo.fir:7:5

  wire _T_0 = _T[0];	// Foo.fir:7:5
    initial begin	// Foo.fir:7:5
      `INIT_RANDOM_PROLOG_	// Foo.fir:7:5
      `ifdef RANDOMIZE_REG_INIT	// Foo.fir:7:5
        _T = `RANDOM;	// Foo.fir:7:5
        r = _T_0;	// Foo.fir:7:5
      `endif
    end // initial
  `endif
  always @(posedge clock)	// Foo.fir:9:7
    r <= d;	// Foo.fir:9:7
  assign q = r;	// Foo.fir:2:10
endmodule
```

The spilling of the wire out of the procedural initial region is wrong as far as I can tell.  What happens is this:

1. `_T` gets a random value
2. `r` gets the value of `_T_0` (which is currently `x`) and has not been updated to `_T[0]`
3. `_T_0` gets updated

This is tedious because we really can't spill outside of this procedural region without changing semantics.

For comparison, the SFC produces:
```verilog
module Foo(
  input   clock,
  input   d,
  output  q
);
`ifdef RANDOMIZE_REG_INIT
  reg [31:0] _RAND_0;
`endif // RANDOMIZE_REG_INIT
  reg  r;
  assign q = r;
  always @(posedge clock) begin
    r <= d;
  end
// Register and memory initialization
`ifdef RANDOMIZE_GARBAGE_ASSIGN
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_INVALID_ASSIGN
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_REG_INIT
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_MEM_INIT
`define RANDOMIZE
`endif
`ifndef RANDOM
`define RANDOM $random
`endif
`ifdef RANDOMIZE_MEM_INIT
  integer initvar;
`endif
`ifndef SYNTHESIS
`ifdef FIRRTL_BEFORE_INITIAL
`FIRRTL_BEFORE_INITIAL
`endif
initial begin
  `ifdef RANDOMIZE
    `ifdef INIT_RANDOM
      `INIT_RANDOM
    `endif
    `ifndef VERILATOR
      `ifdef RANDOMIZE_DELAY
        #`RANDOMIZE_DELAY begin end
      `else
        #0.002 begin end
      `endif
    `endif
`ifdef RANDOMIZE_REG_INIT
  _RAND_0 = {1{`RANDOM}};
  r = _RAND_0[0:0];
`endif // RANDOMIZE_REG_INIT
  `endif // RANDOMIZE
end // initial
`ifdef FIRRTL_AFTER_INITIAL
`FIRRTL_AFTER_INITIAL
`endif
`endif // SYNTHESIS
endmodule
```

### PR DESCRIPTION
**Pull request by seldridge**
Work around a bug in Verilog emission with the disallowLocalVariables
option where temporaries are spilled to wires which violates the
ordering of the initial block used for register randomization.  This
manifests as X's showing up in registers after initialization.  This
avoids this entirely by using explicit registers and verbatim operations
using those registers.

Fixes #2310.

Signed-off-by: Schuyler Eldridge <schuyler.eldridge@sifive.com>

For the example FIRRTL circuit shown in #2310:

```verilog
circuit Foo:
  module Foo:
    input clock: Clock
    input d: UInt<1>
    output q: UInt<1>

    reg r: UInt<1>, clock

    r <= d
    q <= r
```

This PR produces, with or without `-lowering-options=disallowLocalVariables`:

```verilog
module Foo(	// Bar.fir:2:10
  input  clock, d,
  output q);

  reg r;	// Bar.fir:7:5

  `ifndef SYNTHESIS	// Bar.fir:7:5
    `ifdef RANDOMIZE_REG_INIT	// Bar.fir:7:5
      reg [31:0] _RANDOM;	// Bar.fir:7:5

    `endif
    initial begin	// Bar.fir:7:5
      `INIT_RANDOM_PROLOG_	// Bar.fir:7:5
      `ifdef RANDOMIZE_REG_INIT	// Bar.fir:7:5
        _RANDOM = `RANDOM;	// Bar.fir:7:5
        r = _RANDOM[0];	// Bar.fir:7:5
      `endif
    end // initial
  `endif
  always @(posedge clock)	// Bar.fir:9:7
    r <= d;	// Bar.fir:9:7
  assign q = r;	// Bar.fir:2:10
endmodule
```

### CODE REVIEW

File: lib/Conversion/FIRRTLToHW/LowerToHW.cpp [hunk 1]
```diff
@@ -1084,11 +1085,31 @@ void FIRRTLModuleLowering::lowerModuleBody(
...
+      if (port.sym && !port.sym.getValue().empty())
+        internal.insert(port.sym.getValue());
+    module.walk([&](Operation *op) {
+      auto attr = op->getAttrOfType<StringAttr>("inner_sym");
+      if (attr)
+        internal.insert(attr.getValue());
+    });
+  }
+};
+
```
Comment (fabianschuiki) [inline lib/Conversion/FIRRTLToHW/LowerToHW.cpp:1106]: This looks very useful! Maybe we should move `NamespaceBase` into the HW dialect and provide `HWModuleOp` implementations there, and then have FIRRTL add its own namespaces on top.

File: lib/Conversion/FIRRTLToHW/LowerToHW.cpp [hunk 2]
```diff
@@ -2186,7 +2233,32 @@ void FIRRTLLowering::initializeRegister(Value reg) {
...
-    builder.create<sv::BPAssignOp>(dest, getRandomValue(intType));
+
+    SmallVector<SymbolAndRange> values;
+    getRandomValues(intType, values);
+
+    if (values.size() == 1) {
+      auto [value, range] = values[0];
+      builder.create<sv::VerbatimOp>(
+          builder.getStringAttr(Twine("{{0}} = {{1}}[") + Twine(range.first) +
+                                ":" + Twine(range.second) + "];"),
```
Comment (lattner) [inline lib/Conversion/FIRRTLToHW/LowerToHW.cpp:2244]: Pretty please change this to generate `x[0]` instead of `x[0:0]`.

**Comment by lattner** [comment]
This approach seems pragmatic to me

File: lib/Conversion/FIRRTLToHW/LowerToHW.cpp (hunk 2 above)
Comment (seldridge) [reply lib/Conversion/FIRRTLToHW/LowerToHW.cpp]: Good suggestion (and this aligns with how ExportVerilog works). This little stuff really makes a difference in the output quality. 😄 

Updated in the force-push to do:
1. `foo[high]` if high == low
2. `foo` if high == 31, low == 0
3. `foo[high:low]` otherwise

Comment (lattner) [reply lib/Conversion/FIRRTLToHW/LowerToHW.cpp]: Thank you!

File: lib/Conversion/FIRRTLToHW/LowerToHW.cpp (hunk 1 above)
Comment (seldridge) [reply lib/Conversion/FIRRTLToHW/LowerToHW.cpp:1106]: Great idea. Depending on timing, I'll either do this in an NFC commit before this lands or afterwards.

**Comment by seldridge** [comment]
This PR does introduce a lot more symbols (since every register that is randomly initialized now has to have a symbol and `sv.reg` for random values now have symbols).  However, this does not seem to have an appreciable performance penalty.

I ran this on a 200MB FIRRTL file and didn't see a worrisome difference:

`main`:
```
 1.9392 (  2.7%)    1.9392 (  6.8%)  LowerFIRRTLToHW
 1.5427 (  2.2%)    1.5427 (  5.4%)  ExportVerilog
71.6560 (100.0%)   28.6889 (100.0%)  Total
```

This PR:
```
 2.3764 (  3.1%)    2.3764 (  7.9%)  LowerFIRRTLToHW
 1.7761 (  2.3%)    1.7761 (  5.9%)  ExportVerilog
76.2251 (100.0%)   29.9648 (100.0%)  Total
```

File: lib/Conversion/FIRRTLToHW/LowerToHW.cpp (hunk 1 above)
Comment (seldridge) [reply lib/Conversion/FIRRTLToHW/LowerToHW.cpp]: I moved `NamespaceBase` out of FIRRTL and into `circt/Support` and renamed it `Namespace` in 85b24de8cb7f5e8db0a58a7dd50310b1dde4eb7e.

**Comment by seldridge** [comment]
I also tried this out on two designs and the tests for each still passed. 👍

File: lib/Conversion/FIRRTLToHW/LowerToHW.cpp [hunk 3]
```diff
@@ -2138,88 +2163,142 @@ void FIRRTLLowering::emitRandomizePrologIfNeeded() {
...
+    sv::RegOp randReg;
+    {
+      OpBuilder::InsertionGuard topBuilder(builder);
+      builder.restoreInsertionPoint(regInsertionPoint);
+      randReg = builder.create<sv::RegOp>(
+          reg.getLoc(), builder.getIntegerType(randomWidth),
+          /*name=*/builder.getStringAttr("_RANDOM"),
+          /*inner_sym=*/
+          builder.getStringAttr(moduleNamespace.newName(Twine("_RANDOM"))));
     }
```
Comment (fabianschuiki) [inline lib/Conversion/FIRRTLToHW/LowerToHW.cpp:2193]: This might be an extremely dumb idea, but could we reuse the `randReg` of a previous calls to `getRandom32Val`? Like adding at most one such reg to any given module, and then just reusing that as a temporary to write a new ``` `RANDOM ``` into? I don't think we ever use the value in that `randReg` once we've used up all bits.

File: lib/Conversion/FIRRTLToHW/LowerToHW.cpp [hunk 4]
```diff
@@ -2138,88 +2163,142 @@ void FIRRTLLowering::emitRandomizePrologIfNeeded() {
...
+      // Emit a single bit part select, e.g., emit "[0]" and not "[0:0]".
+      if (high == low) {
+        rhs.append(("[" + Twine(high) + "]").str());
+        continue;
+      }
+
+      // Emit a part select, e.g., "[4:2]"
+      rhs.append(
+          ("[" + Twine(range.first) + ":" + Twine(range.second) + "]").str());
+    }
```
Comment (fabianschuiki) [inline lib/Conversion/FIRRTLToHW/LowerToHW.cpp:2265]: I like how pragmatic this is :+1:

**Review by fabianschuiki — APPROVED** [review]

File: lib/Conversion/FIRRTLToHW/LowerToHW.cpp (hunk 3 above)
Comment (seldridge) [reply lib/Conversion/FIRRTLToHW/LowerToHW.cpp:2193]: This is an interesting idea that I didn't consider... 🤔 This would result in fewer (one) temporary variables. There would be more procedural assigns for types larger than 32-bits, though I'm not sure that matters.

```verilog
_RANDOM_0 = `RANDOM;
_RANDOM_1 = `RANDOM;
foo <= {_RANDOM_0, _RANDOM_1};
```

Would become:
```verilog
_RANDOM = `RANDOM;
foo[31:0] <= _RANDOM;
_RANDOM = `RANDOM;
foo[63:32] <= _RANDOM;
```

This unrolled loop could be rolled up for style reasons (if tools will accept variable part select assigns?).
