### PR TITLE
[FIRParser] Parse RawString ExtModule Parameters

### LINKED ISSUE #781: [FIRRTL] Parse RawString ExtModule Parameters
The Scala FIRRTL Compiler supports passing "raw string" parameters to blackboxes. These have single quotes as opposed to double quotes.

As an example, the following:

```scala
module BlackBoxTypeParam :
  extmodule BlackBoxTypeParam :                                                                                    
    output out : UInt<1>                                                                                           
    defname = BlackBoxTypeParam                                                                                    
    parameter T = 'bit'                                                                                            
```

Becomes in the Scala FIRRTL Compiler:

```verilog
module Foo(
  output  out
);
  wire  bar_out;
  BlackBoxTypeParam #(.T(bit)) bar (
    .out(bar_out)
  );
  assign out = bar_out;
endmodule
```

We currently barf on the `'` when trying to parse this `.fir` file with `firtool`:

```
BlackBoxTypeParam.fir:5:19: error: unexpected character
    parameter T = 'bit'
```

As far as I can tell, if something is a raw string, it should be reproduced exactly in the Verilog output.

### PR DESCRIPTION
**Pull request by abdelq**
Decided to tackle this as I'm familiarizing myself with the project. Please let me know of any needed changes.

Closes #781 and #874.

### CODE REVIEW

File: lib/Dialect/FIRRTL/Import/FIRLexer.cpp [hunk 1]
```diff
@@ -101,6 +111,38 @@ std::string FIRToken::getStringValue(StringRef spelling) {
...
+  return getRawStringValue(getSpelling());
+}
+
+std::string FIRToken::getRawStringValue(StringRef spelling) {
+  // Start by dropping the quotes.
+  StringRef bytes = spelling.drop_front().drop_back();
+
+  std::string result;
+  result.reserve(bytes.size());
+  for (unsigned i = 0, e = bytes.size(); i != e;) {
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Import/FIRLexer.cpp:128]: nit: please use size_t instead of unsigned.

File: lib/Dialect/FIRRTL/Import/FIRLexer.cpp [hunk 2]
```diff
@@ -390,16 +434,23 @@ void FIRLexer::skipComment() {
 }
 
 /// StringLit      ::= '"' UnquotedString? '"'
+/// RawString      ::= '\'' UnquotedString? '\''
 /// UnquotedString ::= ( '\\\'' | '\\"' | ~[\r\n] )+?
 ///
-FIRToken FIRLexer::lexString(const char *tokStart) {
+FIRToken FIRLexer::lexString(const char *tokStart, const bool isRaw) {
```
Comment (lattner) [inline lib/Dialect/FIRRTL/Import/FIRLexer.cpp:440]: nit: "const bool" -> "bool"

**Review by lattner — APPROVED** [review]
Awesome and welcome, thank you for tackling this!

**Review by darthscsi — APPROVED** [review]

**Comment by lattner** [comment]
Thank you for implementing this!
