### PR TITLE
[FIRRTL] Fix mask repeat order in FlattenMemory

### LINKED ISSUE #10105: [FIRRTL] Suspected incorrect memory mask lowering for aggregate partial write with dynamic subaccess
**firtool-1.144.0** (LLVM 23.0.0git)

## Reproducer

```firrtl
FIRRTL version 6.0.0
circuit MaskNested :
  public module MaskNested :
    input clock : Clock
    input wen : UInt<1>
    input addr : UInt<2>
    input sel : UInt<1>
    input in_a : UInt<3>
    input in_b : UInt<1>
    output out_a : UInt<3>
    output out_b : UInt<1>

    cmem mem : { a : UInt<3>, b : UInt<1>[2] }[4]
    infer mport rd = mem[addr], clock
    infer mport wr = mem[addr], clock

    when wen :
      connect wr.a, in_a
      connect wr.b[sel], in_b

    connect out_a, rd.a
    connect out_b, rd.b[sel]
```

```
./firtool m.fir -o m.sv
```

## Generated Verilog

```systemverilog
module MaskNested(
  input        clock, wen,
  input  [1:0] addr,
  input        sel,
  input  [2:0] in_a,
  input        in_b,
  output [2:0] out_a,
  output       out_b
);
  wire       mem_wr_mask_b_0 = wen & ~sel;
  wire       mem_wr_mask_b_1 = wen & sel;
  mem_4x5 mem_ext (
    ...
    .W0_data ({in_a, {2{in_b}}}),
    .W0_mask ({wen, mem_wr_mask_b_1, {3{mem_wr_mask_b_0}}})
  );
  assign out_a = _mem_ext_R0_data[4:2];
  assign out_b = sel ? _mem_ext_R0_data[1] : _mem_ext_R0_data[0];
endmodule
```

Memory writes are bit-granular:
```systemverilog
  always @(posedge W0_clk) begin
    if (W0_en & W0_mask[0]) Memory[W0_addr][0] <= W0_data[0];
    if (W0_en & W0_mask[1]) Memory[W0_addr][1] <= W0_data[1];
    if (W0_en & W0_mask[2]) Memory[W0_addr][2] <= W0_data[2];
    if (W0_en & W0_mask[3]) Memory[W0_addr][3] <= W0_data[3];
    if (W0_en & W0_mask[4]) Memory[W0_addr][4] <= W0_data[4];
  end
```

## The Bug

Read-side confirms the bit packing:

```
bit [4:2] = a       (3 bits)
bit [1]   = b[1]    (1 bit)
bit [0]   = b[0]    (1 bit)
```

Mask should match this layout. Expanding the generated mask concatenation:

```
Generated:  {wen, mem_wr_mask_b_1, mem_wr_mask_b_0, mem_wr_mask_b_0, mem_wr_mask_b_0}
             [4]       [3]              [2]               [1]               [0]

  bit 4  a[2]  → wen              ✓
  bit 3  a[1]  → wen & sel        ✗  (should be wen)
  bit 2  a[0]  → wen & ~sel       ✗  (should be wen)
  bit 1  b[1]  → wen & ~sel       ✗  (should be wen & sel)
  bit 0  b[0]  → wen & ~sel       ✓

Expected: {wen, wen, wen, (wen & sel), (wen & ~sel)}
           [4]  [3]  [2]     [1]           [0]
          a[2] a[1] a[0]    b[1]          b[0]
```

The `b[sel]` per-element masks bleed into the `a` field; only `a`'s MSB and `b[0]` are correctly masked.

## AI-Assisted-By
Claude-Opus-4.6

### PR DESCRIPTION
**Pull request by Waryc**
Fixes #10105

## Summary
The previous logic indexed repetition counts by FIRRTL bit index directly, while maskWidths is ordered MSB-to-LSB. This mismatch could assign repetition counts to the wrong mask bits for mixed-width aggregates.

## Changes
- Use reverse index mapping instead.
- Adjust flatten-memory.mlir checks to match corrected ordering.
- Add a MaskRepeatOrder regression case.

## AI-Assisted-by
- GPT-5.3-Codex
- DeepSeek-R1

### CODE REVIEW

**Comment by Waryc** [comment]
@darthscsi @seldridge , would you mind taking a look at this Issue when you get a chance? I'm a student with a strong interest in this area and would love to get more involved with the CIRCT/FIRRTL community. 

This is my first contribution to a major open-source project, so I'm really excited to get the ball rolling! :D

File: lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp [hunk 1]
```diff
@@ -189,7 +189,9 @@ struct FlattenMemoryPass
                 auto mBit = builder.createOrFold<BitsPrimOp>(
                     realOldField, m.index(), m.index());
                 // Check how many times the mask bit needs to be prepend.
-                for (size_t repeat = 0; repeat < m.value(); repeat++)
+                for (size_t repeat = 0;
+                     repeat < maskWidths[maskWidths.size() - 1 - m.index()];
+                     repeat++)
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp]: Nit: not recomputing the end ever iteration would be better:

```suggestion
                for (size_t repeat = 0, end = maskWidths[maskWidths.size() - 1 - m.index()];
                     repeat < end;
                     repeat++)
```

File: test/Dialect/FIRRTL/flatten-memory.mlir [hunk 2]
```diff
@@ -177,4 +177,31 @@ firrtl.module @MemoryRWSplit(in %clock: !firrtl.clock, in %rwEn: !firrtl.uint<1>
...
+    %3 = firrtl.subfield %memory_w[mask] : !firrtl.bundle<addr: uint<2>, en: uint<1>, clk: clock, data: bundle<a: uint<3>, b: vector<uint<1>, 2>>, mask: bundle<a: uint<1>, b: vector<uint<1>, 2>>>
+    %4 = firrtl.subfield %memory_w[data] : !firrtl.bundle<addr: uint<2>, en: uint<1>, clk: clock, data: bundle<a: uint<3>, b: vector<uint<1>, 2>>, mask: bundle<a: uint<1>, b: vector<uint<1>, 2>>>
+    firrtl.connect %0, %clock : !firrtl.clock, !firrtl.clock
+    firrtl.connect %1, %wEn : !firrtl.uint<1>, !firrtl.uint<1>
+    firrtl.connect %2, %wAddr : !firrtl.uint<2>, !firrtl.uint<2>
+    firrtl.connect %3, %wMask : !firrtl.bundle<a: uint<1>, b: vector<uint<1>, 2>>, !firrtl.bundle<a: uint<1>, b: vector<uint<1>, 2>>
+    firrtl.connect %4, %wData : !firrtl.bundle<a: uint<3>, b: vector<uint<1>, 2>>, !firrtl.bundle<a: uint<3>, b: vector<uint<1>, 2>>
+    // CHECK-LABEL: firrtl.module @MaskRepeatOrder
+    // CHECK: %[[MEM1:.+]] = firrtl.mem Undefined {{.*}} : !firrtl.bundle<addr: uint<2>, en: uint<1>, clk: clock, data: uint<5>, mask: uint<5>>
+    // CHECK: %[[W:.+]] = firrtl.subfield %[[MEM0:.+]][mask]
```
Comment (seldridge) [inline test/Dialect/FIRRTL/flatten-memory.mlir]: This seems to be adding another capture unnecessarily? I guess everything should then just be `MEM` for the capture name.


```suggestion
    // CHECK: %[[W:.+]] = firrtl.subfield %[[MEM1]][mask]
```

File: test/Dialect/FIRRTL/flatten-memory.mlir [hunk 3]
```diff
@@ -177,4 +177,31 @@ firrtl.module @MemoryRWSplit(in %clock: !firrtl.clock, in %rwEn: !firrtl.uint<1>
     // CHECK:    = firrtl.mem Undefined  {depth = 1 : i64, name = "ram", portNames = ["MPORT"], prefix = "foo_", readLatency = 0 : i32, writeLatency = 1 : i32} : !firrtl.bundle<addr: uint<1>, en: uint<1>, clk: clock, data: uint<13>, mask: uint<1>>
   }
 
+  firrtl.module @MaskRepeatOrder(in %clock: !firrtl.clock, in %wAddr: !firrtl.uint<2>, in %wEn: !firrtl.uint<1>, in %wMask: !firrtl.bundle<a: uint<1>, b: vector<uint<1>, 2>>, in %wData: !firrtl.bundle<a: uint<3>, b: vector<uint<1>, 2>>) {
```
Comment (seldridge) [inline test/Dialect/FIRRTL/flatten-memory.mlir]: The rest of this file does _not_ follow this convention. However, could the PR indent all the ports for readability? Same request for the memory parameters.

E.g.,:

``` mlir
firrtl.module @MaskRepeatOrder(
  in %clock: !firrtl.clock,
  in %wAddr: !firrtl.uint<2>,
  // ...
}
```

And:

```
%memory_w = firrtl.mem Undefined {
  depth = 4 : i64,
  name = "memory_w",
  // ...
} : !firrtl.bundle<...>
```

Comment (seldridge) [inline test/Dialect/FIRRTL/flatten-memory.mlir]: Please include a link to the GitHub issue that you originally reported.

File: test/Dialect/FIRRTL/flatten-memory.mlir [hunk 4]
```diff
@@ -177,4 +177,31 @@ firrtl.module @MemoryRWSplit(in %clock: !firrtl.clock, in %rwEn: !firrtl.uint<1>
...
+    %4 = firrtl.subfield %memory_w[data] : !firrtl.bundle<addr: uint<2>, en: uint<1>, clk: clock, data: bundle<a: uint<3>, b: vector<uint<1>, 2>>, mask: bundle<a: uint<1>, b: vector<uint<1>, 2>>>
+    firrtl.connect %0, %clock : !firrtl.clock, !firrtl.clock
+    firrtl.connect %1, %wEn : !firrtl.uint<1>, !firrtl.uint<1>
+    firrtl.connect %2, %wAddr : !firrtl.uint<2>, !firrtl.uint<2>
+    firrtl.connect %3, %wMask : !firrtl.bundle<a: uint<1>, b: vector<uint<1>, 2>>, !firrtl.bundle<a: uint<1>, b: vector<uint<1>, 2>>
+    firrtl.connect %4, %wData : !firrtl.bundle<a: uint<3>, b: vector<uint<1>, 2>>, !firrtl.bundle<a: uint<3>, b: vector<uint<1>, 2>>
+    // CHECK-LABEL: firrtl.module @MaskRepeatOrder
+    // CHECK: %[[MEM1:.+]] = firrtl.mem Undefined {{.*}} : !firrtl.bundle<addr: uint<2>, en: uint<1>, clk: clock, data: uint<5>, mask: uint<5>>
+    // CHECK: %[[W:.+]] = firrtl.subfield %[[MEM0:.+]][mask]
+    // CHECK: %[[MF:.+]] = firrtl.subfield %[[MEM1]][mask] : !firrtl.bundle<addr: uint<2>, en: uint<1>, clk: clock, data: uint<5>, mask: uint<5>>
```
Comment (seldridge) [inline test/Dialect/FIRRTL/flatten-memory.mlir]: Seeing these duplicate subfields was surprising, but I see that one of them is from the created wire and one of them is from the memory. It would be better to have the wire as an explicit capture and not `MEM0` as a capture on the RHS.

File: test/Dialect/FIRRTL/flatten-memory.mlir [hunk 5]
```diff
@@ -177,4 +177,31 @@ firrtl.module @MemoryRWSplit(in %clock: !firrtl.clock, in %rwEn: !firrtl.uint<1>
...
+    // CHECK: %[[B0:.+]] = firrtl.bits %[[BC]] 0 to 0 : (!firrtl.uint<3>) -> !firrtl.uint<1>
+    // CHECK: %[[B1:.+]] = firrtl.bits %[[BC]] 1 to 1 : (!firrtl.uint<3>) -> !firrtl.uint<1>
+    // CHECK: %[[C0:.+]] = firrtl.cat %[[B1]], %[[B0]] : (!firrtl.uint<1>, !firrtl.uint<1>) -> !firrtl.uint<2>
+    // CHECK: %[[A:.+]] = firrtl.bits %[[BC]] 2 to 2 : (!firrtl.uint<3>) -> !firrtl.uint<1>
+    // CHECK: %[[C1:.+]] = firrtl.cat %[[A]], %[[C0]] : (!firrtl.uint<1>, !firrtl.uint<2>) -> !firrtl.uint<3>
+    // CHECK: %[[C2:.+]] = firrtl.cat %[[A]], %[[C1]] : (!firrtl.uint<1>, !firrtl.uint<3>) -> !firrtl.uint<4>
+    // CHECK: %[[C3:.+]] = firrtl.cat %[[A]], %[[C2]] : (!firrtl.uint<1>, !firrtl.uint<4>) -> !firrtl.uint<5>
+    // CHECK: firrtl.matchingconnect %[[MF]], %[[C3]] : !firrtl.uint<5>
+  }
+
```
Comment (seldridge) [inline test/Dialect/FIRRTL/flatten-memory.mlir]: This test is hard to follow, but I don't know how to fix it! Every test in this file is hard to follow.

How about this: can the PR add an end-to-end test using `firtool` that _is_ the issue that was originally reported? That is a nice one line check to make sure that it works.

**Comment by Waryc** [comment]
@seldridge, Thanks for the feedback on the earlier MLIR test — agreed it wasn't the best fit here.

I've replaced it with an end-to-end `firtool` regression test based directly on the original reproducer from #10105, with the issue link included in the test comment for traceability.

If a narrower MLIR-level regression would still be valuable alongside the end-to-end test, happy to restore it — but for now I've kept just the end-to-end test as suggested.

File: test/firtool/mask-repeat-order.fir [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+
+; This test checks the end-to-end firtool lowering for the aggregate memory
+; mask repeat ordering bug reported in issue #10105.
+;
+; See: https://github.com/llvm/circt/issues/10105
+FIRRTL version 6.0.0
+
+circuit MaskNested:
+  ; CHECK-LABEL: module MaskNested(
+  ; CHECK: .W0_mask ({{[{][{]3[{]wen[}][}], mem_wr_mask_b_1, mem_wr_mask_b_0[}]}})
```
Comment (seldridge) [inline test/firtool/mask-repeat-order.fir]: Can this be cleaner with `CHECK{LITERAL}`?

Comment (Waryc) [reply test/firtool/mask-repeat-order.fir]: Absolutely. Sorry, I'm still getting used to FileCheck.

**Comment by Waryc** [comment]
BTW, I've found the minimal patch — just apply the `llvm::reverse` method.

File: test/firtool/mask-repeat-order.fir
Comment (seldridge) [inline test/firtool/mask-repeat-order.fir:1]: Is there any other end-to-end test that this can be merged with? (The LLMs love to create standalone tests, which I'm assuming is where this is coming from.)

Comment (Waryc) [reply test/firtool/mask-repeat-order.fir:1]: Updated as suggested — folded the test into the proper existing file.

**Comment by Waryc** [comment]
The previously failing CI check passes locally for me. I think this should be ready to merge.

File: test/firtool/memoryLowering.fir [hunk 7]
```diff
@@ -142,3 +142,34 @@ circuit test:
...
+;// -----
+
+; This regression checks the end-to-end masked aggregate memory lowering for
+; issue #10105.
+;
+; See: https://github.com/llvm/circt/issues/10105
+FIRRTL version 6.0.0
+circuit MaskNested:
+  ; CHECK-LABEL: module MaskNested(
+  ; CHECK{LITERAL}: .W0_mask ({{3{wen}}, mem_wr_mask_b_1, mem_wr_mask_b_0})
```
Comment (seldridge) [inline test/firtool/memoryLowering.fir:156]: Sorry, one final nit: could this also include a check line of the data ordering? That would really lock in the right behavior.

Comment (Waryc) [reply test/firtool/memoryLowering.fir:156]: No problem ~

**Comment by Waryc** [comment]
Fat-fingered the Copilot re-request ......
