### PR TITLE
[FIRRTL][FlattenMemory] Change FlattenMemory to also convert base types to UInt

### LINKED ISSUE #9444: [firtool] Error on SInt Memory with `-repl-seq-mem`
We are running into ~~crashes~~ an error when trying to compile a circuit containing SInt-typed memories with firtool using the `-repl-seq-mem` option:
```
../../ir/sint_mem.fir:12:5: error: memories should be flattened before running LowerMemory
    smem smem : SInt<8>[256]
```
(Reproducer below)

`firrtl-lower-memory` expects all memories to have UInt type. However, `firrtl-flatten-memory` will only convert aggregate types to UInt.
I can see two ways of fixing this, not sure which one is preferred:
- Change FlattenMemory to also convert base types
- Adapt LowerMemories (and potentially other downstream passes) to handle all base types

Repro:
```
FIRRTL version 6.0.0
circuit Top :
  public module Top :
    input clock : Clock
    input reset : UInt<1>
    output io_dout : SInt<8>
    input io_din : SInt<8>
    input io_addr : UInt<8>
    input io_en : UInt<1>
    input io_wr : UInt<1>

    smem smem : SInt<8>[256]
    wire _io_dout_WIRE : UInt<8>
    invalidate _io_dout_WIRE
    when io_en :
      connect _io_dout_WIRE, io_addr
      read mport io_dout_MPORT = smem[_io_dout_WIRE], clock
    connect io_dout, io_dout_MPORT
    node _T = and(io_en, io_wr)
    when _T :
      write mport MPORT = smem[io_addr], clock
      connect MPORT, io_din
```
```
./bin/firtool -repl-seq-mem -repl-seq-mem-file=seqmem.conf  ../../ir/sint_mem.fir
```

### PR DESCRIPTION
**Pull request by fzi-hielscher**
This PR changes the logic of `firrtl-flatten-memory` to also convert memories of SInt and Enum type to UInt. Previously, these would have been left untouched. It also affects aggregates containing only a single non-empty field.
This change is done to support downstream passes, like `firrtl-lower-memory`, which require memories to have UInt type.

Fixes #9444.

### CODE REVIEW

File: lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp [hunk 1]
```diff
@@ -238,8 +242,7 @@ struct FlattenMemoryPass
           })
           .Default([&](auto) { return false; });
     };
-    // Return true only if this is an aggregate with more than one element.
-    return flatten(type) && results.size() > 1;
+    return flatten(type);
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/Transforms/FlattenMemory.cpp:245]: Nice. I'm glad this was a simple fix.
