### PR TITLE
[circt-reduce] Fix connect-forwarder crash with layerblocks

### LINKED ISSUE #9562: [FIRRTL][circt-reduce] Connect Forwarder Crashes w/ Layers
Consider the following:

``` mlir
firrtl.circuit "Foo" {
  firrtl.layer @A bind {
  }
  firrtl.module private @Bar() {
    %c0_ui1 = firrtl.constant 0 : !firrtl.uint<1>
    %wire = firrtl.wire : !firrtl.probe<uint<1>, @A>
    firrtl.layerblock @A {
      %wire_0 = firrtl.wire {name = "wire"} : !firrtl.uint<1>
      firrtl.matchingconnect %wire_0, %c0_ui1 : !firrtl.uint<1>
      %0 = firrtl.ref.send %wire_0 : !firrtl.uint<1>
      %1 = firrtl.ref.cast %0 : (!firrtl.probe<uint<1>>) -> !firrtl.probe<uint<1>, @A>
      firrtl.ref.define %wire, %1 : !firrtl.probe<uint<1>, @A>
    }
  }
  firrtl.extmodule @Foo()
}
```

Running the connect forwarder on this will crash:

``` console
# circt-reduce -skip-initial -test='exit 0' connect-forwarder.0.mlir -include connect-forwarder -o /dev/null 
Reading input
Testing input with `exit 0`
Initial module has size 625
Trying reduction `connect-forwarder`
Assertion failed: (other && other->block == block && "Expected other operation to have the same parent block."), function isBeforeInBlock, file Operation.cpp, line 386.
PLEASE submit a bug report to https://github.com/llvm/circt and include the crash backtrace.
Stack dump:
0.	Program arguments: circt-reduce -skip-initial "-test=exit 0" connect-forwarder.0.mlir -include connect-forwarder -o /dev/null
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  circt-reduce             0x0000000102f9bc34 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  circt-reduce             0x0000000102f99b1c llvm::sys::RunSignalHandlers() + 172
2  circt-reduce             0x0000000102f9c6dc SignalHandler(int, __siginfo*, void*) + 300
3  libsystem_platform.dylib 0x000000018fd516a4 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000018fd17848 pthread_kill + 296
5  libsystem_c.dylib        0x000000018fc209e4 abort + 124
6  libsystem_c.dylib        0x000000018fc1fc18 err + 0
7  circt-reduce             0x00000001041794dc mlir::Operation::isBeforeInBlock(mlir::Operation*) (.cold.2) + 0
8  circt-reduce             0x0000000103f65048 mlir::Operation::isBeforeInBlock(mlir::Operation*) + 112
9  circt-reduce             0x0000000103ed464c (anonymous namespace)::ConnectForwarder::match(mlir::Operation*) + 252
10 circt-reduce             0x0000000103ebdd44 circt::Reduction::matches(mlir::Operation*, llvm::function_ref<void (unsigned long long, unsigned long long)>) + 36
11 circt-reduce             0x0000000102f2c580 void llvm::function_ref<void (mlir::Operation*)>::callback_fn<execute(mlir::MLIRContext&)::$_2>(long, mlir::Operation*) + 64
12 circt-reduce             0x0000000102f2c4dc void mlir::detail::walk<mlir::ForwardIterator>(mlir::Operation*, llvm::function_ref<void (mlir::Operation*)>, mlir::WalkOrder) + 180
13 circt-reduce             0x0000000102f2c4dc void mlir::detail::walk<mlir::ForwardIterator>(mlir::Operation*, llvm::function_ref<void (mlir::Operation*)>, mlir::WalkOrder) + 180
14 circt-reduce             0x0000000102f2c4dc void mlir::detail::walk<mlir::ForwardIterator>(mlir::Operation*, llvm::function_ref<void (mlir::Operation*)>, mlir::WalkOrder) + 180
15 circt-reduce             0x0000000102f2c4dc void mlir::detail::walk<mlir::ForwardIterator>(mlir::Operation*, llvm::function_ref<void (mlir::Operation*)>, mlir::WalkOrder) + 180
16 circt-reduce             0x0000000102f26d48 execute(mlir::MLIRContext&) + 3072
17 circt-reduce             0x0000000102f25ebc main + 300
18 dyld                     0x000000018f976b98 start + 6076
zsh: abort      circt-reduce -skip-initial -test='exit 0' connect-forwarder.0.mlir -include  
```

### PR DESCRIPTION
**Pull request by seldridge**
The connect-forwarder reduction was crashing with an isBeforeInBlock
assertion failure when operations were in different blocks (layerblocks).
The issue was that isBeforeInBlock requires both operations to be in the
same block, but layerblocks create nested blocks.

Use DominanceInfo::properlyDominates to handle cross-block operations.

Fixes #9562.

Signed-of-by: Schuyler Eldridge <schuyler.eldridge@sifive.com>
AI-assisted-by: Augment (Claude Sonnet 4)
AI-assisted-by: Augment (Claude Sonnet 4.5)

### CODE REVIEW

File: lib/Dialect/FIRRTL/FIRRTLReductions.cpp [hunk 1]
```diff
@@ -331,6 +331,20 @@ static void connectToLeafs(ImplicitLocOpBuilder &builder, Value dest,
   firrtl::ConnectOp::create(builder, dest, value);
 }
 
+/// Return true if `a` happens before `b`, i.e., `a` or one of its ancestors
+/// properly dominates `b` and `b` is not inside `a`. This handles cross-block
+/// cases where operations might be in different blocks (e.g., layerblocks).
+static bool happensBefore(Operation *a, Operation *b) {
```
Comment (uenoku) [inline lib/Dialect/FIRRTL/FIRRTLReductions.cpp]: Any chance DominanceInfo::properlyDominates works?  https://mlir.llvm.org/doxygen/classmlir_1_1DominanceInfo.html#a9b5b6aadbdcfc3be72d934d7d0432602

Comment (seldridge) [reply lib/Dialect/FIRRTL/FIRRTLReductions.cpp]: Yeah, that can work. I had the LLM help me with a `--squash` commit to do this refactoring. Nice suggestion.

Fixed in: [e6ee22d](https://github.com/llvm/circt/pull/9581/commits/e6ee22d36ae7cdbbd06664092045ac71958b23a2)
