### PR TITLE
[circt-reduce] Fix extmodule-instance-remover crash with strings

### LINKED ISSUE #9563: [FIRRTL][circt-reduce] extmodule-instance-remover crash w/ properties
Consider the following:

``` mlir
firrtl.circuit "Foo" {
  firrtl.extmodule @Bar(out a: !firrtl.string)
  firrtl.module @Baz() {
    %a = firrtl.instance Bar @Bar(out a: !firrtl.string)
    %wire = firrtl.wire : !firrtl.string
    firrtl.propassign %wire, %a : !firrtl.string
  }
  firrtl.extmodule @Foo()
}
```

This will crash with the following command:

``` console
# circt-reduce -skip-initial -test='exit 0' extmodule-instance-remover.mlir -include extmodule-instance-remover -o /dev/null
Reading input
Testing input with `exit 0`
Initial module has size 311
Trying reduction `extmodule-instance-remover`
Assertion failed: (isa<To>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file Casting.h, line 560.
PLEASE submit a bug report to https://github.com/llvm/circt and include the crash backtrace.
Stack dump:
0.	Program arguments: circt-reduce -skip-initial "-test=exit 0" extmodule-instance-remover.mlir -include extmodule-instance-remover -o /dev/null
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  circt-reduce             0x0000000104563c34 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  circt-reduce             0x0000000104561b1c llvm::sys::RunSignalHandlers() + 172
2  circt-reduce             0x00000001045646dc SignalHandler(int, __siginfo*, void*) + 300
3  libsystem_platform.dylib 0x000000018fd516a4 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000018fd17848 pthread_kill + 296
5  libsystem_c.dylib        0x000000018fc209e4 abort + 124
6  libsystem_c.dylib        0x000000018fc1fc18 err + 0
7  circt-reduce             0x00000001056b7c2c llvm::StdThreadPool::wait() (.cold.1) + 0
8  circt-reduce             0x000000010489a0d8 circt::firrtl::patterns::AddOfPad::~AddOfPad() + 0
9  circt-reduce             0x00000001054a0f38 (anonymous namespace)::ExtmoduleInstanceRemover::rewrite(circt::firrtl::InstanceOp) + 680
10 circt-reduce             0x00000001044ef0dc execute(mlir::MLIRContext&) + 3988
11 circt-reduce             0x00000001044edebc main + 300
12 dyld                     0x000000018f976b98 start + 6076
zsh: abort      circt-reduce -skip-initial -test='exit 0' extmodule-instance-remover.mlir   -
```

### PR DESCRIPTION
**Pull request by seldridge**
The extmodule-instance-remover reduction was crashing with a cast
assertion failure when trying to create InvalidValueOp for !firrtl.string
types. The issue was that InvalidValueOp only accepts FIRRTLBaseType,
but !firrtl.string is a PropertyType (which inherits from FIRRTLType
but not FIRRTLBaseType).

This commit adds a check to only create InvalidValueOp for FIRRTLBaseType
ports. Property types like !firrtl.string cannot be invalidated and are
left unconnected.

Fixes #9563.

AI-assisted-by: Augment (Claude Sonnet 4)

### CODE REVIEW

File: lib/Dialect/FIRRTL/FIRRTLReductions.cpp [hunk 1]
```diff
@@ -952,8 +952,12 @@ struct ExtmoduleInstanceRemover : public OpReduction<firrtl::InstanceOp> {
...
                       .getResult();
       if (info.isOutput()) {
-        auto inv = firrtl::InvalidValueOp::create(builder, info.type);
-        firrtl::ConnectOp::create(builder, wire, inv);
+        // Only create InvalidValueOp for FIRRTLBaseType. Property types like
+        // !firrtl.string cannot be invalidated.
+        if (auto baseType = dyn_cast<firrtl::FIRRTLBaseType>(info.type)) {
+          auto inv = firrtl::InvalidValueOp::create(builder, baseType);
+          firrtl::ConnectOp::create(builder, wire, inv);
+        }
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/FIRRTLReductions.cpp]: This would be better to handle via how https://github.com/llvm/circt/pull/9580 is now creating dummy, invalidate wires for probes and using unknown value for properties.

I'll plan to hold off on this as https://github.com/llvm/circt/pull/9580 adds a `tieOffCache` that can be used here, too.

Comment (seldridge) [reply lib/Dialect/FIRRTL/FIRRTLReductions.cpp]: Fixed in: https://github.com/llvm/circt/pull/9582/commits/6b00f58b6168ba5aeec56c3b33322adaf923ca15

**Review by fabianschuiki — APPROVED** [review]
LGTM! Windows having a Windows day again 😅
