### PR TITLE
[HWArith] Support signedness values inside sv wire/reg/read_inout

### LINKED ISSUE #4301: [hwarith] lower to hw cast from `sv.read_inout`
```mlir
hw.module @foo () -> () {
  %r52 = sv.wire  : !hw.inout<ui2>
  %0 = sv.read_inout %r52 : !hw.inout<ui2>
  %33 = hwarith.cast %0 : (ui2) -> i2
  %34 = hwarith.cast %0 : (ui2) -> i2
  %35 = comb.icmp eq %34, %33 : i2

  %c0_ui2 = hwarith.constant 2 : ui2
  sv.assign %r52, %c0_ui2 : ui2
}
```

```
$ circt-opt test.mlir --lower-hwarith-to-hw
test.mlir:6:9: error: null operand found
  %35 = comb.icmp eq %34, %33 : i2
        ^
test.mlir:6:9: note: see current operation: %2 = "comb.icmp"(<<NULL VALUE>>, <<NULL VALUE>>) {predicate = 0 : i64} : (<<NULL TYPE>>, <<NULL TYPE>>) -> i1
```

### PR DESCRIPTION
**Pull request by mortbopet**
Fixes #4301.

### CODE REVIEW

File: lib/Conversion/HWArithToHW/HWArithToHW.cpp [hunk 1]
```diff
@@ -305,35 +306,63 @@ struct ArgResOpConversion : public OpConversionPattern<TOp> {
   using OpConversionPattern<TOp>::OpConversionPattern;
   using OpAdaptor = typename OpConversionPattern<TOp>::OpAdaptor;
 
+  // Function that will replace the op with a type-converted new op.
+  using ReplacementFunc = std::function<void(
+      ConversionPatternRewriter &, TOp, llvm::SmallVector<Type>, OpAdaptor &)>;
```
Comment (teqdruid) [inline lib/Conversion/HWArithToHW/HWArithToHW.cpp:311]: `llvm::SmallVector<Type>` -> `ArrayRef`?

File: lib/Conversion/HWArithToHW/HWArithToHW.cpp [hunk 2]
```diff
@@ -305,35 +306,63 @@ struct ArgResOpConversion : public OpConversionPattern<TOp> {
...
+       target, patterns, typeConverter,
+       [](ConversionPatternRewriter &rewriter, TOp op,
+          llvm::ArrayRef<Type> convResTypes,
+          typename ArgResOpConversion<TOp>::OpAdaptor &adaptor) {
+         // Use the generic builder to allow this pattern to apply to all ops
+         // with default builders.
+         rewriter.replaceOpWithNewOp<TOp>(
+             op, convResTypes, adaptor.getOperands(), op->getAttrs());
+       }),
+   ...);
```
Comment (teqdruid) [inline lib/Conversion/HWArithToHW/HWArithToHW.cpp:363]: WTF black c++ magic is this? What does it even do? I'm only familiar with the ellipses in function arguments.

Is it possible to rewrite this code in a way which doesn't use this syntax? For readability?

File: lib/Conversion/HWArithToHW/HWArithToHW.cpp [hunk 3]
```diff
@@ -476,11 +521,19 @@ class HWArithToHWPass : public HWArithToHWBase<HWArithToHWPass> {
 
     // Generic conversion and legalization patterns for operations that we
```
Comment (teqdruid) [inline lib/Conversion/HWArithToHW/HWArithToHW.cpp:522]: Not for this PR, but having to list out all the ops from all of the dialects which may use ui/si is not ideal. Is there some way to deal with this generically?

**Review by teqdruid — APPROVED** [review]
I never wrapped my head around the type conversion framework, but this looks reasonable to me.

File: lib/Conversion/HWArithToHW/HWArithToHW.cpp (hunk 2 above)
Comment (mortbopet) [reply lib/Conversion/HWArithToHW/HWArithToHW.cpp:363]: Template fold expressions (https://en.cppreference.com/w/cpp/language/fold). It's actually found quite a few places in both LLVM and CIRCT (and the alternative looks much, much worse) - so I'd be inclined to keep it as-is.

File: lib/Conversion/HWArithToHW/HWArithToHW.cpp (hunk 3 above)
Comment (mortbopet) [reply lib/Conversion/HWArithToHW/HWArithToHW.cpp:522]: As i see it, this would require:
1. ui/si usage is defined through an op interface
2. The `OpConversionPattern`s of this PR are then replaced with `OpInterfaceConversionPattern`s to target this interface.

File: lib/Conversion/HWArithToHW/HWArithToHW.cpp (hunk 2 above)
Comment (teqdruid) [reply lib/Conversion/HWArithToHW/HWArithToHW.cpp:363]: That was the link I couldn't find. Thanks!
