### PR TITLE
PartialConnectOp Verification, Lowering

### LINKED ISSUE #419: [FIRRTL] Extend lower types with partial connect support
Add support to FIRRTL type lowering to work with partial connects `<-`. 

This is both used by "Chisel 2 compatibility mode" and it's been discussed that Chisel should emit these instead of normal connects (`<=`) for the reason that Chisel and the Scala FIRRTL Compiler (SFC) incorrectly truncate `<=` (which is supposed to only be a feature of `<-`).

Currently, `firtool` will throw a stack trace if you have any partial connects.

Example input that currently fails:

```scala
circuit Foo:
  module Foo:
    input a: { a: UInt<1>, b: UInt<1> }
    output b: { a: UInt<1> }

    b <- a
```

With the SFC, you get the following lowered circuit:

```scala
circuit Foo :
  module Foo :
    input a_a : UInt<1>
    input a_b : UInt<1>
    output b_a : UInt<1>

    b_a <= a_a
```

Currently CIRCT will crash with this.

### PR DESCRIPTION
**Pull request by seldridge**
This PR does two major things:

1. Add PartialConnectOp verification (and utilities required to compute this).
2. Add lowering of PartialConnectOps in LowerTypes (which relies on invariants that the verification is checking).
3. Test (1) and (2) and remove expected failing tests that now pass (or are otherwise irrelevant).

Verification is checking weak type equivalence between LHS and RHS in a partial connect. This uses the FIRRTL specification definition of weak type equivalence. Flow is checked in the same way as connect is.

The connection algorithm works as follows:

1. Initialize a flippedness flag to false.
2. Recursively traverse, simultaneously, the LHS type and the RHS passive type.
  a. If the LHS type is a fliptype, toggle the flippedness flag and recurse on the LHS element type and the RHS type.
  b. If the LHS type is an aggregate, recurse into _matching_ elements with the same name.
  c. If the type is a ground type and the flippedness flag is false, connect. If the flippedness flag is true, reverse connect. (The types have already been verified, so this is fine.)

Ground type partial connects are ignored by LowerTypes.

### Metadata

- Fixes #419.

### CODE REVIEW

**Comment by seldridge** [comment]
This should go in after #944. This is now rebased on that branch.

File: lib/Dialect/FIRRTL/FIRRTLOps.cpp [hunk 1]
```diff
@@ -968,6 +968,56 @@ static LogicalResult verifyConnectOp(ConnectOp connect) {
...
+
+  // If the source or destination is a port or instance port, then an optional
+  // outer flip, indicating the direction (input or output), should be stripped
+  // for type checking.
+  if (isPortOrInstancePort(partialConnect.dest()))
+    if (auto destTypeFlip = destType.dyn_cast<FlipType>())
+      destType = destTypeFlip.getElementType();
+  if (isPortOrInstancePort(partialConnect.src()))
+    if (auto srcTypeFlip = srcType.dyn_cast<FlipType>())
+      srcType = srcTypeFlip.getElementType();
```
Comment (youngar) [inline lib/Dialect/FIRRTL/FIRRTLOps.cpp:988]: This might not be worth asking about, since input and output are going to become bitvectors on the op, but are block arguments and ports the only things that can have an outer flip type? Should we just strip the outer flip type without checking where it comes from?

File: lib/Dialect/FIRRTL/FIRRTLTypes.cpp [hunk 2]
```diff
@@ -388,6 +388,59 @@ bool firrtl::areTypesEquivalent(FIRRTLType destType, FIRRTLType srcType) {
   return destType.getWidthlessType() == srcType.getWidthlessType();
 }
 
+/// Returns whether the two types are weakly equivalent.
```
Comment (youngar) [inline lib/Dialect/FIRRTL/FIRRTLTypes.cpp:391]: You might mention that weak type equivalence comes from section 4.6 Weak Type Equivalence

File: lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp [hunk 3]
```diff
@@ -756,6 +761,77 @@ void TypeLoweringVisitor::visitStmt(ConnectOp op) {
...
+        auto bVector = bType.dyn_cast_or_null<FVectorType>();
+        if (!bVector)
+          return;
+
+        for (size_t i = 0, e = std::min<unsigned>(aType.getNumElements(),
+                                                  bVector.getNumElements());
+             i != e; ++i) {
+          if (suffix.isTriviallyEmpty())
+            recursivePartialConnect(
+                a, aType.getElementType().template dyn_cast<FIRRTLType>(), b,
```
Comment (youngar) [inline lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp:795]: Would it work to use `dyn_cast<FIRRTLType>(aType.getElementType())` instead?

File: lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp [hunk 4]
```diff
@@ -756,6 +761,77 @@ void TypeLoweringVisitor::visitStmt(ConnectOp op) {
...
+        }
+      })
+      .Case<FVectorType>([&](auto aType) {
+        auto bVector = bType.dyn_cast_or_null<FVectorType>();
+        if (!bVector)
+          return;
+
+        for (size_t i = 0, e = std::min<unsigned>(aType.getNumElements(),
+                                                  bVector.getNumElements());
+             i != e; ++i) {
```
Comment (youngar) [inline lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp:792]: I would put the length min in a temporary, this is pretty hard to read.  Up to you though.

File: lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp [hunk 5]
```diff
@@ -756,6 +761,77 @@ void TypeLoweringVisitor::visitStmt(ConnectOp op) {
...
+        for (auto aElt : aType.getElements()) {
+          auto aField = aElt.name.getValue();
+          auto bElt = bBundle.getElement(aField);
+          if (bElt) {
+            if (suffix.isTriviallyEmpty())
+              recursivePartialConnect(a, aElt.type, b, bElt.getValue().type,
+                                      aField, aFlip);
+            else
+              recursivePartialConnect(a, aElt.type, b, bElt.getValue().type,
+                                      suffix + "_" + aField, aFlip);
```
Comment (youngar) [inline lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp:781]: I'm trying to buy a bit more horizontal space here.  It might be worth it to create a String instead of using a Twine like I did here: https://github.com/llvm/circt/pull/909#discussion_r615287133

```c++
if (!bElt)
  continue;
auto fieldSuffix = aField;
if (!suffix.isTriviallyEmpty())
  fieldSuffix = (suffix + "_" + a_field).str();
recursivePartialConnect(a, aElt.type, b, bElt.getValue().type,
                        fieldSuffix, aFlip);
 ```

File: lib/Dialect/FIRRTL/FIRRTLOps.cpp (hunk 1 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/FIRRTLOps.cpp:988]: Good idea. Yes, this should work. The one other case (that this is actually missing) is that outer flips should be stripped for memory ports, too. Blindly stripping the flip is the simplest solution here.

File: lib/Dialect/FIRRTL/FIRRTLTypes.cpp (hunk 2 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/FIRRTLTypes.cpp:391]: Will update on the header definition. (Which one is supposed to get the documentation?)

File: lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp (hunk 3 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp:795]: Empirically, no. However, I'm not even sure why I was casting here. `aType.getElementType()` returns a `FIRRTLType` which is what I need. 🤔  I'll just switch to that.

File: lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp (hunk 5 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp:781]: I was trying _very_ hard to use `Twine` here until I actually needed the string. I do think the usage here is safe. However, this is pretty unclear because a safe usage seems to require two kind paths.

I'll switch to your solution here and remove the two code paths. I'll also remove the two code paths in later `FVectorType` case. That should save both horizontal and vertical space as well as improve clarity.

File: lib/Dialect/FIRRTL/FIRRTLOps.cpp (hunk 1 above)
Comment (seldridge) [reply lib/Dialect/FIRRTL/FIRRTLOps.cpp]: As this is now basically duplicating the flip stripping lambda in `areTypesWeaklyEquivalent` I added a commit that creates `std::pair<FIRRTLType, bool> FIRRTLType::stripFlip()`. This will live until the bitvector gets added.

**Comment by seldridge** [comment]
Ping @youngar: anything further you'd like in terms of updates on this or is this alright to land?

**Review by youngar — APPROVED** [review]
@seldridge LGTM
