### PR TITLE
[NFC][Support] Factor out TypeConversionPattern into support lib

### LINKED ISSUE #4899: [MSFT] Assertion triggered if printing `msft.module` during pattern rewrite debugging
Triggered by #4898, but i'd expect it to be reproduceable by other passes.

Running (... after #4898 lands):
```mlir
// RUN: circt-opt --lower-hwarith-to-hw %s
msft.module @AddInts {} (%a: ui32, %b: ui32) -> (c: ui33) {
  %0 = hwarith.add %a, %b : (ui32, ui32) -> ui33
  msft.output %0 : ui33
}
```
finishes successfully. However, Doing the same thing with `--debug` (enabling the pattern rewriter debugging infra, which will print operations in their intermediate states), a crash occurs:
```
//===-------------------------------------------===//
Legalizing operation : 'msft.module'(0x4c4e4b0) {
  * Fold {
ImplicitTypeIDRegistry::lookupOrInsert(mlir::OpTrait::ConstantLike<Empty>)
ImplicitTypeIDRegistry::lookupOrInsert(mlir::DialectFoldInterface)
  } -> FAILURE : unable to fold

  * Pattern : 'msft.module -> ()' {
Trying to match "(anonymous namespace)::TypeConversionPattern"
    ** Insert  : 'msft.module'(0x4c656c0)
    ** Replace : 'msft.module'(0x4c4e4b0)
"(anonymous namespace)::TypeConversionPattern" result 1

    //===-------------------------------------------===//
    Legalizing operation : 'msft.module'(0x4c656c0) {
    } -> SUCCESS : operation marked legal by the target
    //===-------------------------------------------===//
  } -> SUCCESS : pattern applied successfully
// *** IR Dump After Pattern Application ***
mlir-asm-printer: Verifying operation: builtin.module
circt-opt: /home/mortbopet/Work/circt/llvm/mlir/lib/IR/Region.cpp:46: mlir::Region *mlir::Region::getParentRegion(): Assertion `container && "region is not attached to a container"' failed.
```

I suspect that this might be an issue with the `msft.module` builder.

### PR DESCRIPTION
**Pull request by teqdruid**
This `ConversionPattern` is used in two places and is likely generally useful. Move it into the support lib.

Fixes #4899 as a side-effect.

### CODE REVIEW

**Comment by mortbopet** [comment]
Are you sure that this fixes the root cause for #4899? As written in the issue, I'm a little suspect of the `msft.module` builder, seeing as this pattern worked fine on all other (re. `hw.module`) container ops.

File: lib/Support/ConversionPatterns.cpp [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+  Operation *newOp = rewriter.create(state);
+
+  // Move the regions over, converting the signatures as we go.
+  rewriter.startRootUpdate(newOp);
+  for (size_t i = 0, e = op->getNumRegions(); i < e; ++i) {
+    Region &region = op->getRegion(i);
+    Region *newRegion = &newOp->getRegion(i);
+
+    // TypeConverter::SignatureConversion drops argument locations, so we need
+    // to manually copy them over (a verifier in e.g. HWModule checks this).
```
Comment (mortbopet) [inline lib/Support/ConversionPatterns.cpp:70]: Nit: if we plan on upstreaming this, then `(a verifier in e.g. HWModule checks this)` seems unnecessary.

**Comment by teqdruid** [comment]
> Are you sure that this fixes the root cause for #4899? As written in the issue, I'm a little suspect of the `msft.module` builder, seeing as this pattern seems to work fine on all other (re. `hw.module`) container ops

I'm not sure why it works differently in the hwarith lowering, but I definitely saw that same assertion on `hw.module` in the data window lowering pass.

File: lib/Support/ConversionPatterns.cpp (hunk 1 above)
Comment (teqdruid) [reply lib/Support/ConversionPatterns.cpp:70]: I’m thinking before we try to upstream this, someone should fix the signature conversion in MLIR. There is a fixme in there.

**Comment by teqdruid** [comment]
This `ConversionPattern` is used in two places and is likely generally useful. Move it into the support lib.

Fixes #4899 as a side-effect.
