### PR TITLE
[ExportVerilog] Don't emit a constant if it has zero width

### LINKED ISSUE #4204: [ExportVerilog] Zero width error in commented out SV
```mlir
hw.module @A() {
  %c = hw.constant 0 : i0
  hw.instance "b" @B(c: %c: i0) -> ()
}
hw.module @B(%c: i0) {}
```

Correctly emits:
```verilog
module A();	// spurious_error.mlir:1:1
  B b (	// spurious_error.mlir:3:3
  //.c (<<unsupported zero width constant: hw.constant>>)	// spurious_error.mlir:2:8
  );
endmodule

module B(	// spurious_error.mlir:5:1
  // input /*Zero Width*/ c
   );

endmodule
```

However, it also produces an error:

```
$ circt-opt spurious_error.mlir -export-verilog > output.sv
spurious_error.mlir:2:8: error: 'hw.constant' op will not emit zero width constants in the general case
  %c = hw.constant 0 : i0
       ^
spurious_error.mlir:2:8: note: see current operation: %0 = "hw.constant"() {value = 0 : i0} : () -> i0
```

### PR DESCRIPTION
**Pull request by teqdruid**
Fixes #4204

### CODE REVIEW

**Comment by teqdruid** [comment]
I couldn't figure out a better way to do this without losing some signal tracing capability in the output verilog.

File: lib/Conversion/ExportVerilog/ExportVerilog.cpp [hunk 1]
```diff
@@ -3795,7 +3795,10 @@ LogicalResult StmtEmitter::visitStmt(InstanceOp op) {
     // lowered to wire.
     OutputOp output;
     if (!elt.isOutput()) {
-      emitExpression(portVal, ops, LowestPrecedence);
+      if (isZeroWidth && isa_and_nonnull<ConstantOp>(portVal.getDefiningOp()))
+        os << "/* Zero width */";
+      else
```
Comment (uenoku) [inline lib/Conversion/ExportVerilog/ExportVerilog.cpp:3800]: Probably we don't have to restrict the op to be ConstantOp. 
nit: please use `emitZeroWidthIndexingValue` for consistency.
```suggestion
      if (isZeroWidth)
        emitZeroWidthIndexingValue(os);
      else
```

**Review by uenoku — APPROVED** [review]
LGTM

File: lib/Conversion/ExportVerilog/ExportVerilog.cpp (hunk 1 above)
Comment (teqdruid) [reply lib/Conversion/ExportVerilog/ExportVerilog.cpp:3800]: If I don't restrict to constant op, a few cases get omitted. like results from other instances and module arguments. based on the tests, they appear useful and intentional. is this functionality we're willing to lose for implementation generality?

Comment (uenoku) [reply lib/Conversion/ExportVerilog/ExportVerilog.cpp:3800]: Thanks, that makes sense to me. It sounds better :)
