### PR TITLE
[Arc][Conversion] Lower sim.clocked_terminate to exit in LowerArcToLLVM

### LINKED ISSUE #10087: [arcilator] Failed to legalize 'sim.clocked_terminate' and dangling macro references
### Describe the bug

When using arcilator to compile MLIR generated by recent versions of firtool (which now emits sim.clocked_terminate for stop() and assert() statements), the compilation fails with two consecutive issues:

Undefined Symbol Error: The StripSV pass removes sv.macro.decl but leaves sv.macro.ref.expr (e.g., @STOP_COND_) untouched if they are used as operands for sim.clocked_terminate outside of an sv.always block.

Legalization Failure: After manually resolving the symbol issue, the lower-arc-to-llvm pass fails to legalize sim.clocked_terminate, as there are no lowering patterns for the sim dialect in arcilator.

### Steps to Reproduce

Create a file `reproduce.mlir`:

```
module {
  sv.macro.decl @STOP_COND_
  
  hw.module @SimTop(in %clock: !seq.clock, in %cond: i1) {
    %STOP_COND_ = sv.macro.ref.expr @STOP_COND_() : () -> i1
    %1 = comb.and bin %STOP_COND_, %cond : i1
    
    sim.clocked_terminate %clock, %1, success, verbose
  }
}
```
Run arcilator:

```bash
arcilator reproduce.mlir
```

### Expected Behavior
arcilator should be able to handle sim.clocked_terminate by lowering it to a C-style exit() or a similar simulation-ending runtime call, and it should correctly handle macro references used in these contexts.

### Actual Behavior
The compiler crashes with:

error: references an undefined symbol: @STOP_COND_ (in StripSV)

If symbols are fixed: error: failed to legalize operation 'sim.clocked_terminate' (in lower-arc-to-llvm)

### Additional Context

I have a pending PR #10086 to fix the first issue (replacing i1 condition macros with constants in StripSV). However, the second issue (missing lowering for sim.clocked_terminate) requires a proper lowering pattern in LowerArcToLLVM.cpp.

This issue is critical for users moving to newer firtool versions, as it breaks all designs containing stop() or assert() when using arcilator.

### PR DESCRIPTION
**Pull request by nanjo712**
### Description

This PR addresses the issue that ArcToLLVM Pass cannot correctly downgrade from sim.clocked_terminate to LLVM IR. The current implementation strategy adds 8 bytes to the reserved portion of the Model State header (8 bytes were already reserved for simulation timing; the additional 8 bytes are for alignment), with the first byte used as the terminateFlag.

### Technical Changes

Reserved offset 8 in the simulation state for a termination flag by increasing kStateOffset to 16 in AllocateState.cpp.

Updated ArcToLLVM to write status codes (1 for success, 2 for failure) to this flag.

### Testing

Added a new regression test: test/arcilator/sim_clocked_terminate.mlir.

Updated sim_clocked_terminate.mlir and allocate_state.mlir to verify the new memory layout and store logic.

### Reference

Fixes #10087.

Assisted-by: Gemini 3 Flash (Used for English translation)

### CODE REVIEW

**Comment by fzi-hielscher** [comment]
Thank you for your contribution, @nanjo712. It would be great to finally have support for the terminate operation in arcilator. However, I'm skeptical if simply calling `exit` is the right approach here. We need to differentiate between terminating the simulated instance vs. terminating the entire simulation process. There is a bunch of code that we may have to execute after something like `$finish` is called:
- Anything contained in an `arc.final` op
- The clean-up routine of the ArcRuntime library
- Code that is part of the simulation driver, e.g., `arcilator` itself in case of JIT executions

One option to solve this would be to add a return value to the `eval` function that indicates whether the simulation should continue. Alternatively, we could add a dedicated flag to the simulation state (similar to how the simulation time is currently stored), which gets set by the terminate operation and has to be checked before or after each `eval` call.

Please also consider our policy on AI assisted contributions: https://llvm.org/docs/AIToolPolicy.html

**Comment by nanjo712** [comment]
@fzi-hielscher 
I have updated the PR to use a dedicated flag in the simulation state (the second option you suggested).

Regarding the LLVM AI Tool Policy: I used AI tools solely for documentation translation and to assist in navigating and understanding the existing CIRCT codebase. All code, logic designs, and test cases included in this PR were manually authored and verified by me.

**Comment by uenoku** [comment]
To echo @fzi-hielscher, AI policy applies to PR descriptions as well. Please avoid directly pasting verbose LLM output into PR description since it's unnecessary verbose and hard to understand the real intent of the PR. (My apologies if the current description was written manually!) SI Even if the code was developed entirely without AI, verbose PR description can give the impression that the entire PR was created by LLM, which ultimately diminishes your hard work. 

This is from LLVM AI policy:
> To ensure sufficient self review and understanding of the work, it is strongly recommended that contributors write PR descriptions themselves (if needed, using tools for translation or copy-editing). The description should explain the motivation, implementation approach, expected impact, and any open questions or uncertainties to the same extent as a contribution made without tool assistance.

**Comment by nanjo712** [comment]
@uenoku 
Thank you for the pointer and the reminder! I sincerely apologize for the verbose description.
As a non-native speaker, I sometimes rely on AI tools like Gemini 3 Flash to refine my English phrasing and ensure the description meets the community's standards for formality and clarity. I will rewrite the PR description to be more concise.

**Comment by uenoku** [comment]
No need to apologize! Thank you for sending a PR :smile: It's totally fine to use LLM or other tools for translation.

**Comment by nanjo712** [comment]
Hi, I noticed that the CI job "Build and Test / Build and Test (clang, clang++, Debug, ON, ON) (pull_request)" is consistently failed with 'The operation was canceled.'

I've checked the logs, and there are no explicit build errors; the process simply stops. Could you help check if this is due to a specific environment timeout, a resource limit？

File: lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp [hunk 1]
```diff
@@ -987,6 +987,56 @@ struct SimPrintFormattedProcOpLowering
...
+    Value cond = adaptor.getCondition();
+
+    auto funcOp = op->getParentOfType<LLVM::LLVMFuncOp>();
+    if (!funcOp || funcOp.getNumArguments() == 0) {
+      return rewriter.notifyMatchFailure(
+          op, "Could not find parent LLVM function or state pointer");
+    }
+
+    Value statePtr = funcOp.getArgument(0);
+
```
Comment (fzi-hielscher) [inline lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp]: While this will likely work for now, just assuming the first function argument to be the state pointer is not a great solution. We should specify this in the IR instead. Unless @fabianschuiki has a better idea, we probably need to introduce an Arc dialect specific terminate operation, which carries a pointer to the state/storage as context and adapt the LowerState pass to do the conversion. Again, similar to how `CurrentTimeOp` is handled.

Sorry for making this more work, but if I had seen an easy solution, I would have already implemented it myself. 😉

File: lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp [hunk 2]
```diff
@@ -987,6 +987,56 @@ struct SimPrintFormattedProcOpLowering
...
+    auto *currentBlock = rewriter.getInsertionBlock();
+    auto *continueBlock =
+        rewriter.splitBlock(currentBlock, rewriter.getInsertionPoint());
```
Comment (fzi-hielscher) [inline lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp]: Consider replacing the current operation with an `scf::IfOp` instead of splitting the blocks manually. It will produce the same result, but makes the code simpler.

File: lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp [hunk 3]
```diff
@@ -1328,6 +1378,9 @@ void LowerArcToLLVMPass::runOnOperation() {
                     sim::FormatBinOp, sim::FormatOctOp, sim::FormatCharOp,
                     sim::FormatStringConcatOp>();
 
+  // Mark sim::ClockedTerminateOp as illegal
+  target.addIllegalOp<sim::ClockedTerminateOp>();
```
Comment (fzi-hielscher) [inline lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp]: Nit: I don't think this is necessary.

File: lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp [hunk 4]
```diff
@@ -1429,6 +1482,8 @@ void LowerArcToLLVMPass::runOnOperation() {
                SimGetPortOpLowering, SimStepOpLowering>(
       converter, &getContext(), modelMap);
 
+  patterns.add<SimClockedTerminateOpLowering>(converter, &getContext());
```
Comment (fzi-hielscher) [inline lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp]: Nit: Please add the pattern to the list of other patterns.

File: lib/Dialect/Arc/Transforms/AllocateState.cpp [hunk 5]
```diff
@@ -14,9 +14,13 @@
...
 #define DEBUG_TYPE "arc-allocate-state"
 
-// Offset for model state allocations. The first bytes of model storage are
+// Offset for model state allocations. The first 8 bytes of model storage are
 // reserved for the model header (currently just the i64 simulation time).
-static constexpr unsigned kStateOffset = 8;
+// The next 8 bytes are reserved for the termination flag used by
+// `SimTerminateOp`. The actual model state starts at offset 16.
+static constexpr unsigned kTimeOffset = 0;
+static constexpr unsigned kTerminateFlagOffset = 8;
```
Comment (fzi-hielscher) [inline lib/Dialect/Arc/Transforms/AllocateState.cpp]: It would make more sense to place this in a common header so we can use it in LowerArcToLLVM. We could introduce an `ArcConstants.h` file.

File: test/arcilator/sim_clocked_terminate.mlir [hunk 6]
```diff
@@ -0,0 +1,25 @@
+// RUN: arcilator %s | FileCheck %s
```
Comment (fzi-hielscher) [inline test/arcilator/sim_clocked_terminate.mlir]: If possible, check the MLIR result of the conversion pattern in `test/Conversion/ArcToLLVM/lower-arc-to-llvm.mlir` instead of doing an end-to-end test.

File: lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp (hunk 2 above)
Comment (nanjo712) [reply lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp]: Done.

File: lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp (hunk 3 above)
Comment (nanjo712) [reply lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp]: Done.

File: lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp (hunk 4 above)
Comment (nanjo712) [reply lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp]: Done.

File: lib/Dialect/Arc/Transforms/AllocateState.cpp (hunk 5 above)
Comment (nanjo712) [reply lib/Dialect/Arc/Transforms/AllocateState.cpp]: Done.

File: test/arcilator/sim_clocked_terminate.mlir (hunk 6 above)
Comment (nanjo712) [reply test/arcilator/sim_clocked_terminate.mlir]: Done. I splited the test into 2 stages.

File: lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp (hunk 1 above)
Comment (nanjo712) [reply lib/Conversion/ArcToLLVM/LowerArcToLLVM.cpp]: I've tried to implement this solution according to my understanding, and I've already committed it.

**Comment by nanjo712** [comment]
I have tried to implement it according to the suggestion. Please take a look when you have time. Thank you.

File: include/circt/Dialect/Arc/ArcConstants.h [hunk 7]
```diff
@@ -0,0 +1,27 @@
...
+// `SimTerminateOp`. The actual model state starts at offset 16.
+inline constexpr unsigned kTimeOffset = 0;
+inline constexpr unsigned kTerminateFlagOffset = 8;
+inline constexpr unsigned kStateOffset = 16;
+
+} // namespace arc
+
+} // namespace circt
+
+#endif // CIRCT_DIALECT_ARC_ARCCONSTANTS_H
```
Comment (fzi-hielscher) [inline include/circt/Dialect/Arc/ArcConstants.h]: Nit: Please add a newline at the end here and for the other files too.

File: include/circt/Dialect/Arc/ArcOps.td [hunk 8]
```diff
@@ -626,6 +626,30 @@ def CurrentTimeOp : ArcOp<"current_time", [
   }];
 }
 
+def TerminateOp : ArcOp<"terminate", [
+  MemoryEffects<[MemWrite]>
+]> {
+  let summary = "Request simulation termination";
+  let description = [{
+    Sets a termination flag in the model's storage at offset 8.
```
Comment (fzi-hielscher) [inline include/circt/Dialect/Arc/ArcOps.td]:
```suggestion
    Sets a termination flag in the model's storage.
```
Nit: That's an implementation detail which should not be relevant for users.

File: include/circt/Dialect/Arc/ArcOps.td [hunk 9]
```diff
@@ -626,6 +626,30 @@ def CurrentTimeOp : ArcOp<"current_time", [
...
+    evaluation cycle.
+  }];
+
+  let arguments = (ins 
+    StorageType:$storage, 
+    I1:$condition, 
+    BoolAttr:$success
+  );
+  
+  let results = (outs);
```
Comment (fzi-hielscher) [inline include/circt/Dialect/Arc/ArcOps.td]: This is not necessary.

File: lib/Dialect/Arc/Transforms/LowerState.cpp [hunk 10]
```diff
@@ -1044,6 +1046,29 @@ LogicalResult OpLowering::lower(llhd::CurrentTimeOp op) {
...
+  if (!ifClockOp)
+    return failure();
+  OpBuilder::InsertionGuard guard(module.builder);
+  module.builder.setInsertionPoint(ifClockOp.thenYield());
+
+  auto loc = op.getLoc();
+  Value cond = lowerValue(op.getCondition(), phase);
+
+  arc::TerminateOp::create(module.builder, loc, module.storageArg, cond,
+                           op.getSuccessAttr());
```
Comment (fzi-hielscher) [inline lib/Dialect/Arc/Transforms/LowerState.cpp:1075]: Can we use `createOrReuseIf` here instead of carrying the condition on the new operation?

File: include/circt/Dialect/Arc/ArcConstants.h [hunk 11]
```diff
@@ -0,0 +1,27 @@
...
+//===----------------------------------------------------------------------===//
+
+#ifndef CIRCT_DIALECT_ARC_ARCCONSTANTS_H
+#define CIRCT_DIALECT_ARC_ARCCONSTANTS_H
+
+namespace circt {
+namespace arc {
+
+// Offset for model state allocations. The first 8 bytes of model storage are
+// reserved for the model header (currently just the i64 simulation time).
```
Comment (fzi-hielscher) [inline include/circt/Dialect/Arc/ArcConstants.h]: Nit: I would consider the termination code part of the header E.g.: The first 16 bytes of model storage are reserved for the model header. The first 8 bytes contain the current simulation time.

File: include/circt/Dialect/Arc/ArcConstants.h (hunk 7 above)
Comment (nanjo712) [reply include/circt/Dialect/Arc/ArcConstants.h]: Done.

File: include/circt/Dialect/Arc/ArcOps.td (hunk 8 above)
Comment (nanjo712) [reply include/circt/Dialect/Arc/ArcOps.td]: Done.

File: include/circt/Dialect/Arc/ArcOps.td (hunk 9 above)
Comment (nanjo712) [reply include/circt/Dialect/Arc/ArcOps.td]: A leftover with my template. Removed.

File: lib/Dialect/Arc/Transforms/LowerState.cpp (hunk 10 above)
Comment (nanjo712) [reply lib/Dialect/Arc/Transforms/LowerState.cpp:1075]: This makes arc.terminate an unconditional termination operation. Condition control is now managed by an external if statement.

File: include/circt/Dialect/Arc/ArcConstants.h (hunk 11 above)
Comment (nanjo712) [reply include/circt/Dialect/Arc/ArcConstants.h]: Done.

File: lib/Dialect/Arc/Transforms/LowerState.cpp [hunk 12]
```diff
@@ -1044,6 +1046,38 @@ LogicalResult OpLowering::lower(llhd::CurrentTimeOp op) {
...
 }
 
+LogicalResult OpLowering::lower(sim::ClockedTerminateOp op) {
+  if (phase != Phase::New)
+    return success();
+
+  if (initial) {
+    return success();
+  }
+
```
Comment (fzi-hielscher) [inline lib/Dialect/Arc/Transforms/LowerState.cpp]: Nit: LLVM style
https://llvm.org/docs/CodingStandards.html#don-t-use-braces-on-simple-single-statement-bodies-of-if-else-loop-statements

**Review by fzi-hielscher — APPROVED** [review]
One last nit, otherwise LGTM. 👍

File: lib/Dialect/Arc/Transforms/LowerState.cpp (hunk 12 above)
Comment (nanjo712) [reply lib/Dialect/Arc/Transforms/LowerState.cpp]: Done.
