### PR TITLE
[FIRRTL] Fix zero-width head and tail ops and their lowering

### LINKED ISSUE #430: [FIRRTL] (head) parameter 0 error
The following FIRRTL program

```python
circuit top_mod :
  module top_mod :
    output tmp27: UInt<28>
    tmp27 <= head(UInt<28>(42), 0)
```

Compiled with `firtool --lower-to-rtl` gives an error:

```mlir
a_top_mod.fir:4:14: error: operand must have integer type and amount must be >= 1
    tmp27 <= head(UInt<28>(42), 0)
             ^
```

Compiled with `firrtl-1.4.0` produces this Verilog:

```verilog
module top_mod(
  output [27:0] tmp27
);
  assign tmp27 = 28'h0;
endmodule
```

### PR DESCRIPTION
**Pull request by darthscsi**
Fixed #430 #431

### CODE REVIEW

File: lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp [hunk 1]
```diff
@@ -1857,9 +1856,11 @@ LogicalResult FIRRTLLowering::visitExpr(InvalidValuePrimOp op) {
 LogicalResult FIRRTLLowering::visitExpr(HeadPrimOp op) {
   auto input = getLoweredValue(op.input());
   if (!input)
-    return failure();
+    return handleZeroBit(op.input(), [&]() { return setLowering(op, Value()); });
```
Comment (lattner) [inline lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp:1859]: I don't think this is needed.  A zero bit input will necessarily result in a zero bit result, which is handled elsewhere.

File: lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp [hunk 2]
```diff
@@ -1908,9 +1909,11 @@ LogicalResult FIRRTLLowering::visitExpr(ShrPrimOp op) {
 LogicalResult FIRRTLLowering::visitExpr(TailPrimOp op) {
   auto input = getLoweredValue(op.input());
   if (!input)
-    return failure();
+    return handleZeroBit(op.input(), [&]() { return setLowering(op, Value()); });
```
Comment (lattner) [inline lib/Conversion/FIRRTLToRTL/LowerToRTL.cpp:1912]: I don't think this is needed.  A zero bit input will necessarily result in a zero bit result, which is handled elsewhere.

**Review by lattner — APPROVED** [review]
Nice!  I think you can drop two minor pieces, but otherwise LGTM.  Thanks for fixing this!
