### PR TITLE
[FIRParser] Don't optimize validif in the parser

### LINKED ISSUE #1186: [FIRRTL] (validif) mismatch
The following FIRRTL program

```python
circuit top_mod :
  module top_mod :
    input inp_o: SInt<6>
    output tmp11: SInt<6>
    tmp11 <= validif(UInt<1>(0), inp_o)
```

Compiled with `firtool` produces this Verilog:

```verilog
module top_mod(
  input  [5:0] inp_o,
  output [5:0] tmp11);

  assign tmp11 = 6'h0;	// a_top_mod.fir:2:3, :5:14
endmodule
```

Compiled with `firrtl-1.5-SNAPSHOT` produces this Verilog:

```verilog
module top_mod(
  input  [5:0] inp_o,
  output [5:0] tmp11
);
  assign tmp11 = inp_o;
endmodule
```

`Yosys 0.9+3911 (git sha1 4b31223e, clang 11.0.1 -fPIC -Os)` reports formal mismatch:

```
ERROR: Found 6 unproven $equiv cells in 'equiv_status -assert'
```

### PR DESCRIPTION
**Pull request by youngar**
This pattern is already handled by the FIRRTL folders.  As a side effect
of this change, we are now aligning with how the Scala FIRRTL compiler
handles validif with a constant condition:

`validif(0, invalid, value)`:
 - old: condition always false, return invalid.
 - new: mux with an invalid operand, return the other operand.

This fixes #1186.

### CODE REVIEW

File: lib/Dialect/FIRRTL/Import/FIRParser.cpp [hunk 1]
```diff
@@ -1705,17 +1705,7 @@ ParseResult FIRStmtParser::parsePrimExp(Value &result) {
...
-      // validif(0, x) -> always invalid.
-      if (cst.value().isNullValue()) {
-        result = builder.create<InvalidValueOp>(opTypes[1]);
-        return success();
-      }
-    }
-
-    // Otherwise, fold to the non-invalid value.
+    // non-invalid operand. 
     result = operands[1];
```
Comment (youngar) [inline lib/Dialect/FIRRTL/Import/FIRParser.cpp:1709]: This is still folding the `validif()` away in the parser, should I be generating the `MuxPrimOp` properly?

Comment (seldridge) [reply lib/Dialect/FIRRTL/Import/FIRParser.cpp:1709]: If it's functionally equivalent (it is) then it seems fine to do it this way and emit less IR.

**Review by seldridge — APPROVED** [review]

**Review by lattner — APPROVED** [review]
nice, thanks!
