### PR TITLE
[HWArithToHW] Add type conversions for 'other' ops

### LINKED ISSUE #3635: [hwarith] Failed to materialize error
```
hw.module @test1() -> (out: ui8) {
  %1 = hwarith.constant 1 : ui8
  hw.output %1 : ui8
}
```

yields

```
hwarith_test.mlir:2:8: error: failed to materialize conversion for result #0 of operation 'hwarith.constant' that remained live after conversion
  %1 = hwarith.constant 1 : ui8
       ^
hwarith_test.mlir:2:8: note: see current operation: %1 = "hwarith.constant"() {rawValue = 1 : ui8} : () -> ui8
hwarith_test.mlir:3:3: note: see existing live user here: hw.output %0 : ui8
  hw.output %1 : ui8
```

### PR DESCRIPTION
**Pull request by mortbopet**
Fixes #3635. Adds signature conversion for `hw::HWModuleOp,hw:HWExternalModuleOp` (`mlir::populateFunctionOpInterfaceTypeConversionPattern` unfortunately can't be provided an interface, i.e. `HWModuleLike`) as well as conversions for 'other' operations which we expect to be mixed in with `hwarith` operations.

Let me know if I've missed any ops for the `ArgResOpConversion` pattern. Any operation which we expect to be used in conjunction with the `ui/si` types of the `hwarith` operations must (unfortunately) be explicitly mentioned.

### CODE REVIEW

**Comment by mortbopet** [comment]
@7FM can't assign you as a reviewer - you do have commit access to the repo, right?

**Comment by 7FM** [comment]
> @7FM can't assign you as a reviewer - you do have commit access to the repo, right?

I do not have access, I have to explicitly request it, right?
Nevertheless, I will make a review later today.

**Comment by mortbopet** [comment]
>  I have to explicitly request it, right?

Correct - see https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access.

File: lib/Conversion/HWArithToHW/HWArithToHW.cpp [hunk 1]
```diff
@@ -253,23 +255,179 @@ struct BinaryOpLowering : public OpConversionPattern<BinOp> {
...
+      return it->second.type;
+
+    auto convertedType =
+        llvm::TypeSwitch<Type, Type>(type)
+            .Case<IntegerType>([](auto type) {
+              if (type.isSignless())
+                return type;
+              return IntegerType::get(
+                  type.getContext(), type.getIntOrFloatBitWidth(),
+                  IntegerType::SignednessSemantics::Signless);
```
Comment (7FM) [inline lib/Conversion/HWArithToHW/HWArithToHW.cpp:300]: Nit: could be simplified to `IntegerType::get(type.getContext(), type.getWidth())`

File: lib/Conversion/HWArithToHW/HWArithToHW.cpp [hunk 2]
```diff
@@ -253,23 +255,179 @@ struct BinaryOpLowering : public OpConversionPattern<BinOp> {
...
+                                 HWArithToHWTypeConverter &typeConverter) {
+  patterns.add<ArgResOpConversion<TOp>>(typeConverter, patterns.getContext());
+  target.addDynamicallyLegalOp<TOp>([&](TOp op) {
+    return !typeConverter.hasSignednessSemantics(op->getOperandTypes()) &&
+           !typeConverter.hasSignednessSemantics(op->getResultTypes());
+  });
+}
+
+template <typename TOp, typename TOp2, typename... OpTs>
+static void addOperandConversion(ConversionTarget &target,
```
Comment (7FM) [inline lib/Conversion/HWArithToHW/HWArithToHW.cpp:386]: No need for this helper if [fold expressions](https://en.cppreference.com/w/cpp/language/fold) are used.
I.e. the functions could be unified to:
```C++
template <typename... TOp>
static void addOperandConversion(ConversionTarget &target,
                                 RewritePatternSet &patterns,
                                 HWArithToHWTypeConverter &typeConverter) {
  (patterns.add<ArgResOpConversion<TOp>>(typeConverter, patterns.getContext()),
   ...);
  (target.addDynamicallyLegalOp<TOp>([&](TOp op) {
    return !typeConverter.hasSignednessSemantics(op->getOperandTypes()) &&
           !typeConverter.hasSignednessSemantics(op->getResultTypes());
  }),
   ...);
}
```
Though, I could understand if that is considered as too obscure for maintainability.

File: lib/Conversion/HWArithToHW/HWArithToHW.cpp [hunk 3]
```diff
@@ -253,23 +255,179 @@ struct BinaryOpLowering : public OpConversionPattern<BinOp> {
...
 
     target.addIllegalDialect<HWArithDialect>();
     target.addLegalDialect<comb::CombDialect, hw::HWDialect>();
+    target.addDynamicallyLegalOp<hw::HWModuleOp, hw::HWModuleExternOp>(
+        [&](auto moduleLikeOp) {
+          // Legal if all results and args have no signedness integers.
+          bool legalResults = !typeConverter.hasSignednessSemantics(
+              cast<FunctionOpInterface>(moduleLikeOp).getResultTypes());
+          bool legalArgs = !typeConverter.hasSignednessSemantics(
+              cast<FunctionOpInterface>(moduleLikeOp).getArgumentTypes());
```
Comment (7FM) [inline lib/Conversion/HWArithToHW/HWArithToHW.cpp:420]: removing the `cast<FunctionOpInterface>`'s and using `FunctionOpInterface` instead of `auto` might be cleaner?

File: lib/Conversion/HWArithToHW/HWArithToHW.cpp [hunk 4]
```diff
@@ -253,23 +255,179 @@ struct BinaryOpLowering : public OpConversionPattern<BinOp> {
...
 class HWArithToHWPass : public HWArithToHWBase<HWArithToHWPass> {
 public:
   void runOnOperation() override {
     ModuleOp module = getOperation();
 
     ConversionTarget target(getContext());
     RewritePatternSet patterns(&getContext());
+    HWArithToHWTypeConverter typeConverter;
+    mlir::populateFunctionOpInterfaceTypeConversionPattern<hw::HWModuleOp>(
+        patterns, typeConverter);
```
[the remark this answers is not in the document]
Comment (7FM) [reply lib/Conversion/HWArithToHW/HWArithToHW.cpp:410]: If that's the case, then it might be worth considering introducing analogously to `addOperandConversion` a templated `addSignatureConversion` to apply both `populateFunctionOpInterfaceTypeConversionPattern` as well as `target.addDynamicallyLegalOp`.

File: lib/Conversion/HWArithToHW/HWArithToHW.cpp [hunk 5]
```diff
@@ -253,23 +255,179 @@ struct BinaryOpLowering : public OpConversionPattern<BinOp> {
...
+              cast<FunctionOpInterface>(moduleLikeOp).getArgumentTypes());
+          return legalResults && legalArgs;
+        });
+
+    // Generic conversion and legalization patterns for operations that we
+    // expect to be using in conjunction with the signedness values of hwarith.
+    addOperandConversion<
+        hw::OutputOp, comb::MuxOp, seq::CompRegOp, hw::ArrayCreateOp,
+        hw::ArrayGetOp, hw::ArrayConcatOp, hw::ArraySliceOp, hw::StructCreateOp,
+        hw::StructExplodeOp, hw::StructExtractOp, hw::StructInjectOp>(
```
Comment (7FM) [inline lib/Conversion/HWArithToHW/HWArithToHW.cpp:429]: Just skimming the ops of HW and Comb, this should hopefully meet most use cases. Any particular reason why unions (`UnionCreateOp`, `UnionExtractOp`) are not included here? Or do you think we should start with a small set and extend once required?

Comment (mortbopet) [reply lib/Conversion/HWArithToHW/HWArithToHW.cpp:429]: No particular reason, mainly due to them being used so rarely that I forgot about them!

File: lib/Conversion/HWArithToHW/HWArithToHW.cpp (hunk 2 above)
Comment (mortbopet) [reply lib/Conversion/HWArithToHW/HWArithToHW.cpp:386]: Awesome - I like it, i like templates, and i like code reductions!

File: lib/Conversion/HWArithToHW/HWArithToHW.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (mortbopet) [reply lib/Conversion/HWArithToHW/HWArithToHW.cpp:410]: factored out into `addSignatureConversion`.

**Review by 7FM — APPROVED** [review]
LGTM
