### PR TITLE
[FIRRTL] Update output ports in IMCP lattice

### LINKED ISSUE #1478: [FIRRTL] IMConstProp Bug: Output used as wire
One more IMConstProp bug.  Registers in instances that read from an output port are getting incorrectly optimized away. Note: this bug doesn't seem to exist for modules where the register is in the top module.  

Consider the following circuit where register `%r` reads from output port `%a` and also writes to it (effectively creating a self connection):

```mlir
firrtl.circuit "Foo"   {
  firrtl.module @Bar(in %clock: !firrtl.clock, out %a: !firrtl.uint<1>) {
    %r = firrtl.reg %clock  : (!firrtl.clock) -> !firrtl.uint<1>
    %0 = firrtl.not %a : (!firrtl.uint<1>) -> !firrtl.uint<1>
    firrtl.connect %r, %0 : !firrtl.uint<1>, !firrtl.uint<1>
    firrtl.connect %a, %r : !firrtl.uint<1>, !firrtl.uint<1>
  }
  firrtl.module @Foo(in %clock: !firrtl.clock, out %a: !firrtl.uint<1>) {
    %bar_clock, %bar_a = firrtl.instance @Bar  {name = "bar"} : !firrtl.clock, !firrtl.uint<1>
    firrtl.connect %bar_clock, %clock : !firrtl.clock, !firrtl.clock
    firrtl.connect %a, %bar_a : !firrtl.uint<1>, !firrtl.uint<1>
  }
}
```

IMConstProp is deleting the register `%r` when it should keep it around.  After IMConstProp, the circuit is:

```mlir
firrtl.circuit "Foo"   {
  firrtl.module @Bar(in %clock: !firrtl.clock, out %a: !firrtl.uint<1>) {
    %invalid_ui1 = firrtl.invalidvalue : !firrtl.uint<1>
    firrtl.connect %a, %invalid_ui1 : !firrtl.uint<1>, !firrtl.uint<1>
  }
  firrtl.module @Foo(in %clock: !firrtl.clock, out %a: !firrtl.uint<1>) {
    %invalid_ui1 = firrtl.invalidvalue : !firrtl.uint<1>
    %bar_clock, %bar_a = firrtl.instance @Bar  {name = "bar"} : !firrtl.clock, !firrtl.uint<1>
    firrtl.connect %bar_clock, %clock : !firrtl.clock, !firrtl.clock
    firrtl.connect %a, %invalid_ui1 : !firrtl.uint<1>, !firrtl.uint<1>
  }
}
```

### Background

The source FIRRTL for this is:

```scala
circuit Foo :
  module Bar :
    input clock : Clock
    output a : UInt<1>

    reg r : UInt<1>, clock
    r <= not(a)
    a <= r

  module Foo :
    input clock : Clock
    output a : UInt<1>

    inst bar of Bar
    bar.clock <= clock
    a <= bar.a
```

Running this through the Scala FIRRTL Compiler produces the following:

```verilog
module Bar(
  input   clock,
  output  a
);
  reg  r;
  assign a = r;
  always @(posedge clock) begin
    r <= ~a;
  end
endmodule
module Foo(
  input   clock,
  output  a
);
  wire  bar_clock;
  wire  bar_a;
  Bar bar (
    .clock(bar_clock),
    .a(bar_a)
  );
  assign a = bar_a;
  assign bar_clock = clock;
endmodule

```

Running this through CIRCT produces:

```verilog
module Bar(
  input  clock,
  output a);

  assign a = 1'h0;	// Foo.fir:2:10, :6:5
endmodule

module Foo(
  input  clock,
  output a);

  wire bar_a;	// Foo.fir:14:5

  Bar bar (	// Foo.fir:14:5
    .clock (clock),
    .a     (bar_a)
  );
  assign a = 1'h0;	// Foo.fir:10:10, :14:5
endmodule
```

I was surprised that formulations where the register is in the top module work. I.e., the following compiles just fine:

```scala
circuit Foo :
  module Foo :
    input clock : Clock
    output a : UInt<1>

    reg r : UInt<1>, clock
    r <= not(a)
    a <= r
```

### LINKED ISSUE #1488: [FIRRTL] imconstprop mismatch
The following FIRRTL program

```python
circuit top_mod :
  module Bar :
    input a: UInt<1>
    input b: UInt<1>
    output c: UInt<1>
    output d: UInt<1>
    c <= b
    wire _c: UInt<1>
    _c <= xor(a, c)
    d <= _c
  module top_mod :
    input a: UInt<1>
    input b: UInt<1>
    output c: UInt<1>
    output d: UInt<1>
    inst bar of Bar
    bar.a <= a
    bar.b <= b
    c <= bar.c
    d <= bar.d
```

Compiled with `firtool -imconstprop` produces this Verilog:

```verilog
module Bar(
  input  a, b,
  output c, d);

  assign c = b;	// a_top_mod.fir:2:10
  assign d = 1'h0;	// a_top_mod.fir:2:10, :8:5
endmodule

module top_mod(
  input  a, b,
  output c, d);

  wire bar_d;	// a_top_mod.fir:16:5

  Bar bar (	// a_top_mod.fir:16:5
    .a (a),
    .b (b),
    .c (c),
    .d (bar_d)
  );
  assign d = 1'h0;	// a_top_mod.fir:11:10, :16:5
endmodule
```

image

Compiled with `firrtl-1.5-SNAPSHOT` produces this Verilog:

```verilog
module Bar(
  input   a,
  input   b,
  output  c,
  output  d
);
  assign c = b;
  assign d = a ^ c;
endmodule
module top_mod(
  input   a,
  input   b,
  output  c,
  output  d
);
  wire  bar_a;
  wire  bar_b;
  wire  bar_c;
  wire  bar_d;
  Bar bar (
    .a(bar_a),
    .b(bar_b),
    .c(bar_c),
    .d(bar_d)
  );
  assign c = bar_c;
  assign d = bar_d;
  assign bar_a = a;
  assign bar_b = b;
endmodule

```
image

`Yosys 0.9+3911 (git sha1 4b31223e, clang 11.0.1 -fPIC -Os)` reports formal mismatch:

```
ERROR: Found 1 unproven $equiv cells in 'equiv_status -assert'.
```

### PR DESCRIPTION
**Pull request by seldridge**
Change IMCP to update output ports and not just _external_ users of
output ports.  Output ports have wire-like semantics and may be read
from as well as written to.

Fixes #1478.
Fixes #1488.

### CODE REVIEW

**Review by prithayan — APPROVED** [review]
Looks good, the lattice values for the output port was not being updated.

File: lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp [hunk 1]
```diff
@@ -505,6 +505,8 @@ void IMConstPropPass::visitConnect(ConnectOp connect) {
     if (!AnnotationSet::get(blockArg).hasDontTouch())
       for (auto userOfResultPort : resultPortToInstanceResultMapping[blockArg])
         mergeLatticeValue(userOfResultPort, srcValue);
+    // Output ports are wire-like and may have users.
+    mergeLatticeValue(connect.dest(), srcValue);
```
Comment (prithayan) [inline lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp:509]: Can we move this to line 501, out of all the conditions ? That should handle all the cases.

Comment (seldridge) [reply lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp:509]: Yes, probably. I'll leave this for an NFC cleanup after this lands.

**Comment by lattner** [comment]
nice, thanks!
