### PR TITLE
[HW][FIRRTL] Let ops specify inner symbol behavior.

### LINKED ISSUE #4873: [HW] verifyInnerSymAttr uses hw::InstanceOp instead of firrtl::InstanceOp
Just wanted to note this, see:

https://github.com/llvm/circt/blob/11f8e0701b6cb0006b8118c0e49411b71e2f2169/lib/Dialect/HW/HWOpInterfaces.cpp#L30

I believe this is meant to reject per-field symbols on instances, since inner symbols on instances target the instance itself and not its results, which is badness and requires special handling in a various places (and leads to bugs like #4559).

We can fix easily enough if okay mentioning FIRRTL bits from HW, which I don't think is what we want.

Anyway mostly means we don't verify what we should/did previously and this code is wrong/dead in that sense for 1-result FIRRTL instance ops.  Not a big deal, probably not worth fixing separate from the needed rework already needed (at very least so this works w/HW).

### PR DESCRIPTION
**Pull request by dtzSiFive**
* Which result, if any, do inner symbols target?
* Are per-field symbols sensible for this operation kind?

No longer need to know this information in the verifier or passes, query through the interface.

Fixes per-field inner symbol support on forceable declarations.

Fixes #4873 .

### CODE REVIEW

File: lib/Dialect/FIRRTL/FIRRTLOps.cpp [hunk 1]
```diff
@@ -2184,6 +2189,8 @@ void MemOp::getAsmResultNames(OpAsmSetValueNameFn setNameFn) {
   }
 }
 
+std::optional<size_t> MemOp::getTargetResultIndex() { return 0; }
```
Comment (prithayan) [inline lib/Dialect/FIRRTL/FIRRTLOps.cpp:2192]: I'm not sure if its result 0, this should be same behavior as `InstanceOp`

Comment (dtzSiFive) [reply lib/Dialect/FIRRTL/FIRRTLOps.cpp:2192]: Thanks for bringing this up, figuring out what the answers are and being explicit about it in a single place is part of the fun here! :smile: .

InstanceOp's have no "result" value corresponding to the symbol, and so field-specific symbols are rejected for that reason.  For memories, [this test](https://github.com/llvm/circt/blob/963f5e5518ab52164d3ebd1975c92461bd74d16f/test/Dialect/FIRRTL/errors.mlir#L922) looks to me to be specifically checking that a memory with symbols is considered to have fields (max of 0, presumably because of the empty bundle type)? (compare to the instance test)

Should we instead treat this as inner symbols do not target the result for these (and no per-field symbols)? Sounds good to me, but not the current behavior, consider the following example we currently accept:

```firrtl
firrtl.circuit "Foo" {
  firrtl.module @Foo() {
    %m = firrtl.mem sym [<@x,1,public>,<@y,2,public>] Undefined {depth = 16 : i64, name = "ReadMemory", portNames = ["read0"], readLatency = 1 : i32, writeLatency = 1 : i32} : !firrtl.bundle<addr: uint<4>, en: uint<1>, clk: clock, data flip: sint<8>>
  }
}
```

File: include/circt/Dialect/HW/HWOpInterfaces.td [hunk 2]
```diff
@@ -265,6 +265,19 @@ def InnerSymbol : OpInterface<"InnerSymbolOpInterface"> {
               circt::hw::InnerSymbolTable::getInnerSymbolAttrName());
       }]
     >,
+    StaticInterfaceMethod<"Returns whether per-field symbols are supported for this operation type.",
+      "bool", "supportsPerFieldSymbols", (ins), [{}], /*defaultImplementation=*/[{
```
Comment (prithayan) [inline include/circt/Dialect/HW/HWOpInterfaces.td:269]: At first glance, I was not sure of when would per-field symbol be not supported. Seems like earlier per field symbol did not make any sense, if any op had more than one result. This changes with RefType results. 
If you have a better explanation of why this method can return false, you can add it to the comments, else this is good.

File: lib/Dialect/HW/HWOpInterfaces.cpp [hunk 3]
```diff
@@ -27,20 +27,24 @@ LogicalResult hw::verifyInnerSymAttr(InnerSymbolOpInterface op) {
   // If does not have any inner sym then ignore.
   if (!innerSym)
     return success();
-  if (isa<InstanceOp>(&op) || op->getNumResults() != 1) {
+
+  if (!op.supportsPerFieldSymbols()) {
```
Comment (prithayan) [inline lib/Dialect/HW/HWOpInterfaces.cpp:31]: This is so much better. Thanks for abstracting it.

File: lib/Dialect/FIRRTL/FIRRTLOps.cpp (hunk 1 above)
Comment (dtzSiFive) [reply lib/Dialect/FIRRTL/FIRRTLOps.cpp]: Updated accordingly!  Presumably same for the CHIRRTL memory operations (cc #4874 -- they're not officially supported targets for inner symbols, and aren't verified presently), right? :+1:

File: lib/Dialect/HW/HWOpInterfaces.cpp [hunk 4]
```diff
@@ -27,20 +27,24 @@ LogicalResult hw::verifyInnerSymAttr(InnerSymbolOpInterface op) {
...
       return failure();
     }
     return success();
   }
 
-  auto resultType =
-      op->getResultTypes()[0].dyn_cast<hw::FieldIDTypeInterface>();
+  auto result = op.getTargetResult();
+  // If op supports per-field symbols, but does not have a target result,
+  // its up to the operation to verify itself.
```
Comment (prithayan) [inline lib/Dialect/HW/HWOpInterfaces.cpp:42]: Do you have a use case in mind ? No target result but still valid per-field inner sym, when can that occur ?

**Review by prithayan — APPROVED** [review]
I think this is great cleanup. Thanks !

File: lib/Dialect/FIRRTL/FIRRTLOps.cpp (hunk 1 above)
Comment (prithayan) [reply lib/Dialect/FIRRTL/FIRRTLOps.cpp]: I think it doesn't make sense to allow per-field sym on memories. It becomes difficult to interpret it for multiple ports. So, no result should be good. If we need it in the future we can relax this.

File: include/circt/Dialect/HW/HWOpInterfaces.td (hunk 2 above)
Comment (dtzSiFive) [reply include/circt/Dialect/HW/HWOpInterfaces.td:269]: I don't have any concrete use cases in mind, but other than being an unnecessary extension point I think having a separate "are per-field symbols supported" query is useful for readability / semantic clarity, if perhaps a bit overkill given our current known needs.  The default implementation is "does the inner symbol target a specific result" for the reason you say :+1: .

I don't expect anything to change this behavior anytime soon, you're not wrong :+1:.

---

> Seems like earlier per field symbol did not make any sense, if any op had more than one result.

Pedantically, the "has more than one result" (or less than one result) was incorrect for instances (and in the other direction, for memories, as we've found in our chat above) and this led to things like #4559 and generally required code to "know" the "meaning" per-op and hopefully get it right.  This was a known limitation of "what do inner symbols and per-field inner symbols /mean/" since they were added, where no answer was identified... so until now has been a bit of "inner symbol names what you want it to" (which has merits of its own, tbh).  The documentation is careful to not say what an inner symbol actually identifies specifically (especially per-field), for this reason.  I guess now we can say "ask the operation what it means!" :rofl: .

> This changes with RefType results.

You're 100% right that adding/extending operations to have multiple results (forceable, reftype's) is what motivated addressing this head-on and making explicit what the result target was, since suddenly the adhoc `getNumResults() != 1` checks throughout are not sufficient and can't easily be made to work without FIRRTL-op/FIRRTL-type-specific knowledge, which shouldn't be used in, e.g., HW.  Should've seen that coming, oops.

Design was driven by "what does HW need to know about each op to accurately verify inner symbols on the op?".  And, on a technical note, motivated by the inability to reasonably change our HW-dialect InnerSym verifier to understand what FIRRTL results to check for which ops (our InstanceOp check has been wrong for some time, using `hw` not `firrtl` for this reason-- don't want to link FIRRTL into HW dialect).

----

As for why the default implementation of `supportsPerFieldSymbols` might not be accurate for some future op:

1) May wish to have a "target result" without supporting per-field symbols within it (this returns true, but false is what the op wants).
2) May wish to not have the (top-level) inner symbol target any result, but per-field inner symbols would have some other meaning.  Maybe selecting which result, or some op-specific behavior.

Mostly want to make whether this is true a clearly different and explicit question to ask an operation, instead of inferring whether this is true from other things (without providing mechanism for agreeing/disagreeing with the default).

File: lib/Dialect/HW/HWOpInterfaces.cpp (hunk 4 above)
Comment (dtzSiFive) [reply lib/Dialect/HW/HWOpInterfaces.cpp:42]: No, just trying to be careful about assumptions.  Does this seem like a problem specifically, or more of a "this suggests that would be useful and as far as (we) can tell it's probably not so why pretend it's allowed?".  LMK re:former, and re:latter, good call.  I can add a comment saying this isn't currently intended to be how things work (and similarly on the interface method the other comment thread is on)?

Comment (dtzSiFive) [reply lib/Dialect/HW/HWOpInterfaces.cpp:42]: (Added comments as suggested here and at the other spot, thanks!!)

**Comment by dtzSiFive** [comment]
Test failure in circt-reduce? Log: https://gist.github.com/dtzSiFive/3d0eeafbce38363820914a0e92360c97 .  Investigating (didn't fire earlier)...

**Comment by dtzSiFive** [comment]
I believe I've identified the problem, will PR a fix and it's unrelated to this AFAIK (and as shown by re-running the test, doesn't consistently fire).
