### PR TITLE
[firtool] Run CheckWidths pass, add option for InferWidths

### LINKED ISSUE #1032: [firtool] Run InferWidths and CheckWidths passes
`firtool` should run the new `CheckWidths` pass before lowering to RTL, to ensure that the lowering won't fail due to uninferred widths. Additionally, there should be a `--infer-widths` switch to run the `InferWidths` pass on the input FIRRTL.

### PR DESCRIPTION
**Pull request by fabianschuiki**
Run the `CheckWidths` pass when lowering to the RTL dialect to ensure there are no uninferred widths that will cause the lowering to fail. Add a `--infer-widths` option that runs the `InferWidths` pass.

Fixes #1032.

### CODE REVIEW

File: tools/firtool/firtool.cpp [hunk 1]
```diff
@@ -210,9 +215,14 @@ processBuffer(std::unique_ptr<llvm::MemoryBuffer> ownedBuffer,
   if (blackboxMemory)
     pm.nest<firrtl::CircuitOp>().addPass(firrtl::createBlackBoxMemoryPass());
 
+  if (inferWidths)
+    pm.nest<firrtl::CircuitOp>().addPass(firrtl::createInferWidthsPass());
```
Comment (lattner) [inline tools/firtool/firtool.cpp:219]: Should this run before BB memory?

**Review by lattner — APPROVED** [review]
