### PR TITLE
[FIRRTL] Fix crash in getPort(size_t) when missing inner symbols.

### LINKED ISSUE #6399: [FIRRTL] FModuleOp::getPort() is broken
FModuleOp::getPort(size_t) seems to be implemented but it is neither used nor tested. It always crashes when calling `module.getPort(..)`. 
```
PLEASE submit a bug report to https://github.com/llvm/circt and include the crash backtrace.
 #0 0x0000000000747087 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /scratch/hidetou/circt/llvm/llvm/lib/Support/Unix/Signals.inc:723:13
 #1 0x0000000000744fd0 llvm::sys::RunSignalHandlers() /scratch/hidetou/circt/llvm/llvm/lib/Support/Signals.cpp:106:18
 #2 0x00000000007479cf SignalHandler(int) /scratch/hidetou/circt/llvm/llvm/lib/Support/Unix/Signals.inc:413:1
 #3 0x00007f95e8c05cf0 __restore_rt (/lib64/libpthread.so.0+0x12cf0)
 #4 0x00007f95e7cbcaff raise (/lib64/libc.so.6+0x4eaff)
 #5 0x00007f95e7c8fea5 abort (/lib64/libc.so.6+0x21ea5)
 #6 0x00007f95e7c8fd79 _nl_load_domain.cold.0 (/lib64/libc.so.6+0x21d79)
 #7 0x00007f95e7cb5456 (/lib64/libc.so.6+0x47456)
 #8 0x0000000000aa0354 mlir::NamedAttribute::NamedAttribute(mlir::StringAttr, mlir::Attribute) /scratch/hidetou/circt/llvm/mlir/lib/IR/Attributes.cpp:46:3
 #9 0x0000000000cf4850 getPortImpl(circt::firrtl::FModuleLike, unsigned long) /scratch/hidetou/circt/lib/Dialect/FIRRTL/FIRRTLOps.cpp:579:11
#10 0x0000000000cf4762 circt::firrtl::FModuleOp::getPort(unsigned long) /scratch/hidetou/circt/lib/Dialect/FIRRTL/FIRRTLOps.cpp:589:3
```

### LINKED ISSUE #9278: [FIRRTL] Confusing API between `getPort(size_t)` and `getPorts`
# Issue

**Related**: https://github.com/llvm/circt/issues/6399

In `FIRRTLOps.cpp`, `FModuleLike` has two seemingly similiar operations called `getPorts()` and `getPort(size_t)`. `getPorts()` works reliably, but `getPort(size_t)` can crash `firtool` (and `circt-opt`) with an assertion failure when the port does not have a symbol.

## Reproduction

Given following pass,

```cpp
namespace {
struct GetPortExperimentPass
    : public GetPortExperimentBase<GetPortExperimentPass> {
  void runOnOperation() override {
    CircuitOp circuit = getOperation();
    OpBuilder classBuilder(circuit);
    classBuilder.setInsertionPointToStart(circuit.getBodyBlock());

    ClassOp generatedWithPort =
        createSimpleClassWithPortSym(&circuit, classBuilder);
    printOutClassOpPorts(generatedWithPort);

    ClassOp generatedWithoutPort =
        createSimpleClassWithoutPortSym(&circuit, classBuilder);
    printOutClassOpPorts(generatedWithoutPort);
  }

private:
  void printOutClassOpPorts(ClassOp &generated) {
    LLVM_DEBUG(llvm::dbgs() << "Found ports with getPorts() API: \n");
    for (auto port : generated.getPorts())
      LLVM_DEBUG(llvm::dbgs() << "- " << port.name << "\n");

    LLVM_DEBUG(llvm::dbgs() << "Direct access with getPort(size_t): \n");
    LLVM_DEBUG(llvm::dbgs() << "- " << generated.getPort(0).name << "\n");
    LLVM_DEBUG(llvm::dbgs() << "- " << generated.getPort(1).name << "\n");
  }

  ClassOp createSimpleClassWithoutPortSym(CircuitOp *circuit,
                                          OpBuilder builder) {
    MLIRContext *context = circuit->getContext();

    StringType portType = StringType::get(context);
    PortInfo nameOut(StringAttr::get(context, "name"), portType,
                     Direction::Out);
    PortInfo nameIn(StringAttr::get(context, "nameIn"), portType,
                    Direction::In);
    const SmallVector<PortInfo, 2> instInfoPorts = {nameOut, nameIn};

    ClassOp instInfoClass = builder.create<ClassOp>(
        circuit->getLoc(), StringAttr::get(context, "ClassWithoutPortSym"),
        instInfoPorts);

    // PropAssign is deliberately omitted to minimize the reproduction code.
    return instInfoClass;
  }

  ClassOp createSimpleClassWithPortSym(CircuitOp *circuit, OpBuilder builder) {
    MLIRContext *context = circuit->getContext();

    StringType portType = StringType::get(context);
    StringAttr nameAttr = StringAttr::get(context, "name");
    PortInfo nameOut(nameAttr, portType, Direction::Out, nameAttr);

    StringAttr nameInAttr = StringAttr::get(context, "nameIn");
    PortInfo nameIn(nameInAttr, portType, Direction::In, nameInAttr);
    const SmallVector<PortInfo, 2> instInfoPorts = {nameOut, nameIn};

    ClassOp instInfoClass = builder.create<ClassOp>(
        circuit->getLoc(), StringAttr::get(context, "ClassWithPortSym"),
        instInfoPorts);

    // PropAssign is deliberately omitted to minimize the reproduction code.
    return instInfoClass;
  }
};
} // namespace
```

Using this trivial input:

```
firrtl.circuit "BlankModule" {
    firrtl.module @BlankModule() {}
}
```

The generated IR is

```
module {
  firrtl.circuit "BlankModule" {
    firrtl.class @ClassWithPortSym(out %name: !firrtl.string sym @name, in %nameIn: !firrtl.string sym @nameIn) {
    }
    firrtl.class @ClassWithoutPortSym(out %name: !firrtl.string, in %nameIn: !firrtl.string) {
    }
    firrtl.module @BlankModule() {
    }
  }
}
```

**Behavior**:
- **Without debug option**: No crashes.
- **With debug** (`--debug` or `--debug-only=<pass>`): accessing ports via `getPort(size_t)` on the symbol-less class causes an assertion failure.

```
Found ports with getPorts() API: 
- "name"
- "nameIn"
Direct access with getPort(size_t): 
- "name"
- "nameIn"
Found ports with getPorts() API: 
- "name"
- "nameIn"
Direct access with getPort(size_t): 
- circt-opt: /home/nergy-host/circt/llvm/mlir/lib/IR/Attributes.cpp:45: mlir::NamedAttribute::NamedAttribute(mlir::StringAttr, mlir::Attribute): Assertion `name && value && "expected valid attribute name and value"' failed.
PLEASE submit a bug report to https://github.com/llvm/circt and include the crash backtrace.
Stack dump:
0.      Program arguments: ./circt-opt --firrtl-port-experiment ./temp/blank.mlir --debug-only=get-port-experiment
 #0 0x00007339e58b281d llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/nergy-host/circt/llvm/llvm/lib/Support/Unix/Signals.inc:723:11
 #1 0x00007339e58b2d0b PrintStackTraceSignalHandler(void*) /home/nergy-host/circt/llvm/llvm/lib/Support/Unix/Signals.inc:798:1
 #2 0x00007339e58b0d36 llvm::sys::RunSignalHandlers() /home/nergy-host/circt/llvm/llvm/lib/Support/Signals.cpp:105:5
 #3 0x00007339e58b3525 SignalHandler(int) /home/nergy-host/circt/llvm/llvm/lib/Support/Unix/Signals.inc:413:1
 #4 0x00007339e3c42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x00007339e3c969fc __pthread_kill_implementation ./nptl/./nptl/pthread_kill.c:44:76
 #6 0x00007339e3c969fc __pthread_kill_internal ./nptl/./nptl/pthread_kill.c:78:10
 #7 0x00007339e3c969fc pthread_kill ./nptl/./nptl/pthread_kill.c:89:10
 #8 0x00007339e3c42476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #9 0x00007339e3c287f3 abort ./stdlib/./stdlib/abort.c:81:7
#10 0x00007339e3c2871b _nl_load_domain ./intl/./intl/loadmsgcat.c:1177:9
#11 0x00007339e3c39e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#12 0x000062b0bb4b15d1 mlir::NamedAttribute::NamedAttribute(mlir::StringAttr, mlir::Attribute) /home/nergy-host/circt/llvm/mlir/lib/IR/Attributes.cpp:46:3
```

Note that `getPort(size_t)` works fine when `symName` was supplied, as shown on first case but crashes otherwise.

## Analysis

`getPorts()` constructs `firrtl::PortInfo` with `getPortSymbolAttr(i)` directly.
```cpp
static SmallVector<PortInfo> getPortImpl(FModuleLike module) {
  SmallVector<PortInfo> results;
  for (unsigned i = 0, e = module.getNumPorts(); i < e; ++i) {
    results.push_back({module.getPortNameAttr(i), module.getPortType(i),
                       module.getPortDirection(i), module.getPortSymbolAttr(i),
                       module.getPortLocation(i),
                       AnnotationSet::forPort(module, i)});
  }
  return results;
}

SmallVector<PortInfo> FModuleOp::getPorts() { return ::getPortImpl(*this); }

// ...
```

while `getPort(size_t)` constructs `hw::PortInfo` with `NamedAttribute`. Whenever `getPortSymbolAttr(idx)` is null, this will trigger assertion.
```cpp
static hw::PortInfo getPortImpl(FModuleLike module, size_t idx) {
  return {{module.getPortNameAttr(idx), module.getPortType(idx),
           dirFtoH(module.getPortDirection(idx))},
          idx,
          DictionaryAttr::get(
              module.getContext(),
              ArrayRef<mlir::NamedAttribute>{NamedAttribute{
                  StringAttr::get(module.getContext(),
                                  hw::HWModuleLike::getPortSymbolAttrName()),
                  module.getPortSymbolAttr(idx)}}),
          module.getPortLocation(idx)};
}

::circt::hw::PortInfo FModuleOp::getPort(size_t idx) {
  return ::getPortImpl(*this, idx);
}

// ...
```

This code was originated from https://github.com/llvm/circt/commit/8722a98a7b0464d2c95498c6e4a68e7e98e0e70d and as of 12/02/25 the `main` branch remains unchanged. (https://github.com/llvm/circt/blame/main/lib/Dialect/FIRRTL/FIRRTLOps.cpp)

# Reason this issue should be fixed

Even though it's a small issue, it's easy to trip over for unexperienced developers.

- One API silently assumes that a symbol must exist, without documenting that requirement.
- As a result, this result can surprise newcomers.

# Possible workarounds

1. **Supply the optional `symName` or `hw::InnerSymAttr` when constructing `PortInfo`.**

```cpp
    StringType portType = StringType::get(context);
    StringAttr nameAttr = StringAttr::get(context, "name");
    PortInfo nameOut(nameAttr, portType, Direction::Out, nameAttr);
```

2.  **Use `getPorts()` and index access instead.** (This returns `firrtl::PortInfo`)

```cpp
generated.getPorts()[2]
```

### PR DESCRIPTION
**Pull request by dtzSiFive**
Add unittest checking FIRRTL PortInfo's against HW PortInfo's.

Fixes #6399.
Fixes #9278.

### CODE REVIEW

File: lib/Dialect/FIRRTL/FIRRTLOps.cpp [hunk 1]
```diff
@@ -718,15 +718,17 @@ SmallVector<::circt::hw::PortInfo> FMemModuleOp::getPortList() {
 }
 
 static hw::PortInfo getPortImpl(FModuleLike module, size_t idx) {
+  auto aname = StringAttr::get(module.getContext(),
+                               hw::HWModuleLike::getPortSymbolAttrName());
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/FIRRTLOps.cpp]: `mlir::NamedAttribute` has a constructor that takes a `StringRef`. Creation of the `StringAttr` here can be avoided. (The original code didn't do this, though!)

File: lib/Dialect/FIRRTL/FIRRTLOps.cpp [hunk 2]
```diff
@@ -718,15 +718,17 @@ SmallVector<::circt::hw::PortInfo> FMemModuleOp::getPortList() {
...
+  auto sym = module.getPortSymbolAttr(idx);
+  auto attrs =
+      sym ? DictionaryAttr::getWithSorted(
+                module.getContext(), ArrayRef(mlir::NamedAttribute(aname, sym)))
```
Comment (seldridge) [inline lib/Dialect/FIRRTL/FIRRTLOps.cpp]: Nice use of `getWithSorted`.

File: unittests/Dialect/FIRRTL/PortsTest.cpp [hunk 3]
```diff
@@ -0,0 +1,141 @@
...
+
+class PortsTest : public ::testing::Test {
+protected:
+  void SetUp() override { context.loadDialect<FIRRTLDialect>(); }
+
+  MLIRContext context;
+  OpBuilder builder{&context};
+
+  template <typename T, typename... Args>
+  void checkPortsAgainstHWPortInfo(const Twine &name, Args &&...args) {
```
Comment (seldridge) [inline unittests/Dialect/FIRRTL/PortsTest.cpp:37]: This is nice reuse in these tests. Some of the gtests get super verbose without this. 👍

File: lib/Dialect/FIRRTL/FIRRTLOps.cpp (hunk 1 above)
Comment (dtzSiFive) [reply lib/Dialect/FIRRTL/FIRRTLOps.cpp]: Oh, TIL.  Let's use that constructor as you suggest, thanks!
